Repository openshift/verification-tests, pull requests merged in 2018-12, with the labels that each got.

#20 Add rules for ocp-19672
  lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
  lib/rules/web/admin_console/3.11/deployment.xyaml
  lib/rules/web/admin_console/3.11/goto.xyaml
  lib/rules/web/admin_console/4.0/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.0/deployment.xyaml
  lib/rules/web/admin_console/4.0/goto.xyaml
Labels: size/L

#38 update webauto libs and remove ureliable ff legacy support
  Gemfile
  lib/webauto/web4cucumber.rb
  tools/jenkins/slaves/Dockerfile
Labels: size/S

#39 for OpenShift build we need context dir to be the dir of Dockerfile
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: size/XS

#30 Init Dockerfiles for openshift-ci
  tools/openshift-ci/Dockerfile.centos
Labels: size/M

#43 add installer destroy abilities
  lib/error.rb
  lib/openshift/resource_not_found_error.rb
  tools/launch_instance.rb
Labels: size/M

#42 change base and remove oc installation
  tools/openshift-ci/Dockerfile.centos
Labels: size/XS

#47 support getting network name
  lib/launchers/openstack10.rb
Labels: size/XS

#45 replace set_pair_value by set_textarea_value
  lib/rules/web/admin_console/4.0/secrets.xyaml
Labels: size/XS

#46 rules update of remove check_desired_pod_count
  lib/rules/web/admin_console/3.11/deployment.xyaml
  lib/rules/web/admin_console/4.0/actions.xyaml
  lib/rules/web/admin_console/4.0/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.0/deployment.xyaml
Labels: size/L

#52 Updated case_id_splitter utility to return a simple list of filenames…
  tools/case_id_splitter.rb
Labels: approved, size/S

#54 more debuggable curl and reliable github api access
  tools/jenkins/slaves/Dockerfile.centos
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved, size/S

#53 Fail ealier if package missing
  tools/jenkins/slaves/Dockerfile.centos
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: lgtm, size/S

#50 Fix web case
  lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.0/secrets.xyaml
Labels: lgtm, size/S

#49 Change base to centos.
  tools/openshift-ci/Dockerfile.centos
Labels: size/S

#48 rescheuled-report and report functionality has been combined into report
  features/step_definitions/metering.rb
  features/test/metering.feature
  lib/openshift/flakes/condition.rb
  lib/openshift/report.rb
Labels: CoreAutomation, Metering, size/L

#55 Update readme
  README.adoc
Labels: lgtm, size/XS

#51 added installation of metering using shell script that comes with the…
  features/step_definitions/admin.rb
  features/step_definitions/metering.rb
  features/test/metering.feature
Labels: CoreAutomation, Metering, size/M
