Repository openshift/verification-tests, pull requests merged in 2018-11, with the labels that each got.

#27 added comment for alternative suggested by Jianlin
  lib/environment.rb
Labels: size/XS

#21 Add rules for OCP-19717
  lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.0/common_ui_elements.xyaml
Labels: size/M

#22 logstash helper service
  features/step_definitions/helper_services.rb
  lib/openshift/service.rb
Labels: size/M

#28 Update the dockerfile for containerized tests running BushSlicer.
  tools/jenkins/slaves/Dockerfile.centos
Labels: size/XS

#29 allow multiple AWS configs
  Gemfile
  config/config.yaml
  lib/iaas/iaas.rb
  lib/launchers/amz.rb
  lib/launchers/cloud_helper.rb
  tools/launch_instance.rb
Labels: size/M

#32 added a class for metering CRD, and a post installation check to make…
  features/step_definitions/logging_metrics.rb
  features/step_definitions/metering.rb
  lib/openshift/metering.rb
Labels: CoreAutomation, Metering, size/S

#33 avoid making AWS and AWS-CI the same object
  config/config.yaml
Labels: size/XS

#35 Log error is enough when failed to create pv
  features/step_definitions/pv.rb
Labels: size/XS

#34 Fix some cases
  features/cli/oc_set_deployment_hook.feature
  features/cli/oc_set_probe.feature
Labels: size/S
