Repository openshift/verification-tests, pull requests merged in 2019-12, with the labels that each got.

#478 Fix failing
  features/cli/secrets.feature
Labels: approved, lgtm, size/XS

#482 Add options to create_secret and sort them alphanumeric
  lib/rules/cli/4.0.yaml
Labels: approved, lgtm, size/S

#483 Update variables names for OCP4 paltform.
  config/config.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#479 allow name suffix when matching scenarios to allow upgrade prepare test use case
  features/test/upgrade.feature
  lib/polarshift/request.rb
  lib/polarshift/test_case.rb
  lib/polarshift/test_suite.rb
Labels: approved, do-not-merge/hold, size/M

#485 4.3 rules fixes
  lib/rules/web/admin_console/4.2/overview.xyaml
  lib/rules/web/admin_console/4.3/overview.xyaml
Labels: approved, lgtm, size/M

#473 update rules for OCP-20172
  features/step_definitions/admin_console.rb
  features/step_definitions/logging_metrics.rb
  lib/rules/web/images/logging/logging.xyaml
  lib/rules/web/images/logging/login.xyaml
Labels: approved, lgtm, size/S

#488 document upgrade testing implementation
  doc/upgrade_testing.adoc
  features/test/upgrade.feature
Labels: approved, lgtm, size/L

#487 Upgrade ocp 22606
  features/upgrade/etcd/upgrade.feature
Labels: size/M

#493 upgrade-scenario-cleanup
  features/test/upgrade.feature
Labels: approved, lgtm, size/M

#486 Add owners for storage part
  features/storage/OWNERS
Labels: approved, lgtm, size/XS

#491 rule fixes
  lib/openshift/console_cli_download_console_openshift_io.rb
  lib/rules/web/admin_console/4.3/check_links.xyaml
  lib/rules/web/admin_console/4.3/customizations.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
Labels: approved, lgtm, size/M

#376 utilty to summarize instance usages for various cloud vendors
  lib/instance_summary.rb
  lib/jenkins.rb
  lib/launchers/amz.rb
  lib/launchers/azure.rb
  lib/launchers/gce.rb
  lib/launchers/openstack10.rb
  tools/cloud_cop.rb
Labels: approved, lgtm, size/XL

#495 Remove jenkins login steps from pipeline cases
  features/build/buildconfig.feature
  features/build/env.feature
  features/cli/build.feature
  features/images/jenkins.feature
Labels: approved, lgtm, size/M

#498 Add owners for admin-console
  lib/rules/web/admin_console/OWNERS
Labels: approved, lgtm, size/XS

#497 Limit PV/PVC in storage class, so OCP-10107 no longer destructive
  features/storage/pre-bind.feature
Labels: approved, lgtm, size/S

#481 Add rules for OCP-22308
  features/step_definitions/machineconfig.rb
  lib/openshift/flakes/machine_config_pool_spec.rb
  lib/openshift/machine_config.rb
  lib/openshift/machine_config_pool.rb
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/filters.xyaml
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/filters.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
Labels: approved, lgtm, size/L

#504 Fix failing
  features/cli/build.feature
  features/cli/create.feature
Labels: approved, lgtm, size/M

#500 Limit pre-bind PV/PVC in storage class to not interfere with each other
  features/storage/pre-bind.feature
Labels: approved, lgtm, size/L

#501 Fix scripts
  features/rest/webhook.feature
Labels: approved, lgtm, size/XS

#432 More multus cases
  features/networking/multus.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/L

#509 accomodate different cli prefix
  lib/cli_executor.rb
  lib/environment.rb
Labels: approved, lgtm, size/XS

#427 multus automation
  features/networking/multus.feature
  lib/openshift/network_attachment_definition.rb
  lib/world.rb
Labels: approved, lgtm, size/M

#475 Auto OCP-25706
  features/networking/sdn.feature
Labels: approved, lgtm, size/M

#499 Add owners for devexp
  features/build/OWNERS
  features/images/OWNERS
Labels: approved, lgtm, size/S

#496 fix OCP-19669
  lib/rules/web/admin_console/4.3/status.xyaml
Labels: approved, lgtm, size/XS

#512 Modify steps to click another button
  lib/rules/web/console/3.11/login.xyaml
  lib/rules/web/console/base/login.xyaml
Labels: approved, lgtm, size/XS

#514 Backport relevant commits from master
  Gemfile
  doc/upgrade_testing.adoc
  features/step_definitions/logging_metrics.rb
  features/step_definitions/net.rb
  features/step_definitions/web.rb
  features/support/env.rb
  features/test/upgrade.feature
  lib/bushslicer.rb
  lib/cli_executor.rb
  lib/common.rb
  lib/environment.rb
  lib/http.rb
  lib/login.rb
  lib/openshift/route.rb
  lib/platform/master_service.rb
  lib/polarshift/request.rb
  lib/polarshift/test_case.rb
  lib/polarshift/test_suite.rb
  lib/rest.rb
  lib/webauto/chrome_extension.rb
  lib/webauto/resource/chrome_crx3/README
  lib/webauto/resource/chrome_crx3/crx3.pb.rb
  lib/webauto/resource/chrome_crx3/crx3.proto
  lib/webauto/resource/chrome_proxy/background.js.erb
  lib/webauto/resource/chrome_proxy/manifest.json
  lib/webauto/web4cucumber.rb
  lib/webauto/webconsole_executor.rb
  tools/launch_instance.rb
  tools/shell_proxy.sh
Labels: approved, lgtm, size/XL

#520 Fix for the rule check_key_and_action_link
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
Labels: approved, lgtm, size/XS

#484 fix issue: getting metrics failed
  features/logging/cluster_logging_operator.feature
  features/logging/elasticsearch_operator.feature
  features/step_definitions/logging.rb
Labels: approved, lgtm, size/S

#518 Fix the rhel8 images auto
  features/images/rhel8_images.feature
Labels: approved, lgtm, size/L

#519 auto OCP-25773
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
Labels: approved, lgtm, size/XS

#523 Fix scrips failing
  features/cli/build.feature
  features/cli/oc_import_image.feature
Labels: approved, lgtm, size/M

#532 add cli rules
  lib/rules/cli/4.4.yaml
  lib/rules/cli/kubectl-4.3.yaml
  lib/rules/cli/kubectl-4.4.yaml
Labels: approved, lgtm, size/XS

#468 Add machine-healthcheck scenarios
  features/machine/machine_healthcheck.feature
  features/step_definitions/machine_healthcheck.rb
  lib/openshift/machine_set.rb
  lib/openshift/machinehealthcheck.rb
Labels: approved, lgtm, size/M

#490 fix failure of scaling up es pods when running CI testing
  features/logging/cluster_logging_operator.feature
Labels: approved, lgtm, size/M

#505 auto OCP-24340
  lib/rules/web/admin_console/4.3/operator_hub.xyaml
Labels: approved, lgtm, size/S

#508 Update OCP-15471,Auto OCP-15472
  features/networking/egress-ip.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/M

#530 Fix author format
  features/cli/configmap.feature
  features/logging/cluster_logging_operator.feature
  features/logging/collector.feature
  features/logging/deploy_logging_operators_via_console.feature
  features/logging/elasticsearch.feature
  features/logging/kibana.feature
  features/logging/permission.feature
  features/networking/pod.feature
  features/networking/service.feature
  features/online/images.feature
  features/svc-catalog_asb/apb-update.feature
  features/web/k8s-deployments.feature
Labels: approved, lgtm, size/L

#534 One author per line
  features/cli/limits.feature
  features/cli/secrets.feature
  features/images/jenkins.feature
  features/quickstarts/quickstarts.feature
Labels: approved, lgtm, size/M

#533 new step to get available router ip
  features/routing/route.feature
  features/step_definitions/route.rb
Labels: approved, lgtm, size/S

#541 update all related cases to use the new step [follow up #533]
  features/routing/abrouting.feature
  features/routing/haproxy-router.feature
  features/routing/ingress-route.feature
  features/routing/rate-limit.feature
  features/routing/route.feature
  features/routing/timeout.feature
Labels: approved, lgtm, size/S

#489 automate eventrouter related case
  features/logging/eventrouter.feature
  features/step_definitions/logging.rb
  lib/openshift/daemon_set.rb
Labels: approved, lgtm, size/M

#535 remove unnecessary steps
  features/logging/cluster_logging_operator.feature
  features/logging/collector.feature
  features/logging/elasticsearch.feature
  features/logging/elasticsearch_operator.feature
  features/step_definitions/logging.rb
Labels: approved, lgtm, size/S

#540 Fix OCP-10626
  features/cli/scale.feature
Labels: approved, lgtm, size/XS

#438 More n more multus auto
  features/networking/multus.feature
Labels: approved, lgtm, size/L

#502 update multus failed cases
  features/networking/multus.feature
Labels: approved, lgtm, size/M

#539 Add default sub-team reviewers
  features/admin/OWNERS
  features/cli/OWNERS
  features/cluster_configuration/OWNERS
  features/infrastructure/OWNERS
  features/logging/OWNERS
  features/machine/OWNERS
  features/metrics/OWNERS
  features/networking/OWNERS
  features/online/OWNERS
  features/quickstarts/OWNERS
  features/registry/OWNERS
  features/routing/OWNERS
  features/svc-catalog_asb/OWNERS
  features/upgrade/OWNERS
  features/upgrade/etcd/OWNERS
  features/web/OWNERS
  features/web/service-catalog/OWNERS
Labels: approved, lgtm, size/M

#546 Bump up storage apiVersion from v1beta1 to v1
  features/step_definitions/storage_class.rb
Labels: approved, lgtm, size/XS

#513 auto OCP-24330
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
Labels: approved, lgtm, size/S

#544 Automate OCP-24493
  features/storage/local-storage-operator.feature
  lib/openshift/operator_source.rb
  lib/world.rb
Labels: approved, lgtm, size/S

#547 fix OCP-24316 OCP-21772
  lib/rules/web/admin_console/4.0/projects.xyaml
  lib/rules/web/admin_console/4.1/projects.xyaml
  lib/rules/web/admin_console/4.2/customizations.xyaml
  lib/rules/web/admin_console/4.2/projects.xyaml
  lib/rules/web/admin_console/4.3/customizations.xyaml
  lib/rules/web/admin_console/4.3/projects.xyaml
Labels: approved, lgtm, size/S

#526 Fix OCP-12400
  features/registry/registry.feature
  features/step_definitions/dc.rb
  features/step_definitions/registry.rb
Labels: approved, lgtm, size/M

#506 Automate OCP-25676
  features/networking/multus.feature
Labels: approved, lgtm, size/M

#521 automated OCP-24416
  lib/openshift/console_external_log_link.rb
  lib/rules/web/admin_console/4.2/check_links.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/check_links.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
Labels: approved, lgtm, size/S

#537 OCP-24918
  features/networking/operator.feature
Labels: approved, lgtm, size/M

#517 Some tweaks/addition to support OVN, more to come
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/M

#553 Missing end in networking.rb
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/XS

#542 autocase OCP-24286
  lib/rules/web/admin_console/4.2/check_links.xyaml
  lib/rules/web/admin_console/4.3/check_links.xyaml
Labels: approved, lgtm, size/M

#511 auto OCP-25931
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/operator_hub.xyaml
Labels: approved, lgtm, size/M

#538 Simplify OCP-10467
  features/cli/policy.feature
Labels: approved, lgtm, size/S

#555 Auto OCP-25401
  features/images/jenkins.feature
Labels: approved, lgtm, size/S

#554 Auto OCP-22958
  features/images/rhel8_images.feature
Labels: approved, lgtm, size/M

#549 add rules for OCP-21958
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.1/quota.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.2/quota.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/quota.xyaml
Labels: approved, lgtm, size/L

#559 rules added for OCP-21256
  lib/rules/web/admin_console/4.1/overview.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.2/overview.xyaml
  lib/rules/web/admin_console/4.3/overview.xyaml
Labels: approved, lgtm, size/M

#522 add rules for OCP-24232
  lib/rules/web/admin_console/4.2/actions.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/actions.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
Labels: approved, lgtm, size/M

#562 fix namespaced scope for packagemanifests
  lib/openshift/package_manifest.rb
Labels: approved, lgtm, size/XS

#528 Add rules for popover case OCP-25792
  lib/rules/web/admin_console/4.3/overview.xyaml
Labels: approved, lgtm, size/M

#548 Add rules for OCP-25868
  lib/openshift/console_external_log_links_console_openshift_io.rb
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/logs.xyaml
Labels: approved, lgtm, size/S

#560 rules added for OCP-26170
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/route.xyaml
Labels: approved, lgtm, size/M

#525 rules for OCP-25817
  lib/openshift/console_yaml_samples_console_openshift_io.rb
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
Labels: approved, lgtm, size/S

#575 remove duplicated rule goto_one_pod_log_page
  lib/rules/web/admin_console/4.3/goto.xyaml
Labels: approved, lgtm, size/XS
