Repository openshift/verification-tests, pull requests merged in 2019-06, with the labels that each got.

#219 Fixing yaml (from integer to string)
  features/storage/nfs.feature
Labels: approved, lgtm, size/S

#229 Fix OCP-12151
  features/cli/deploy.feature
Labels: approved, lgtm, size/XS

#231 allow report generation for scheduled reports
  features/step_definitions/metering.rb
  features/test/metering.feature
  lib/openshift/report.rb
Labels: CoreAutomation, Metering, approved, size/M

#228 Update OCP-14382 for 4.x
  features/storage/quota.feature
Labels: approved, lgtm, size/M

#232 Use attribute storageClassName to replace annotations
  features/step_definitions/pv.rb
  features/step_definitions/secrets.rb
  features/storage/aws.feature
  features/storage/cloud_provider.feature
  features/storage/csi.feature
  features/storage/dynamic_provisioning.feature
  features/storage/glusterfs.feature
  features/storage/quota.feature
  features/storage/rbd.feature
  features/storage/storage_class.feature
  features/storage/vsphere.feature
  features/test/pvc.feature
Labels: approved, lgtm, size/L

#236 Move annotation is-default-class from beta to stable
  features/step_definitions/storage_class.rb
  features/storage/storage_class.feature
  features/test/storage_class.feature
Labels: approved, lgtm, size/M

#237 Fix typo of author
  features/networking/operator.feature
  features/networking/pod.feature
Labels: approved, lgtm, size/XS

#238 added a couple of new openshift resource objects.
  lib/openshift/a_p_i_service.rb
  lib/openshift/namespace.rb
  lib/openshift/storage_class.rb
Labels: CoreAutomation, approved, lgtm, size/S

#234 updated it to use 4.1 branch until 4.2 is officially released...the a…
  features/step_definitions/metering.rb
Labels: CoreAutomation, Metering, approved, size/XS

#241 Add packet support
  lib/bushslicer.rb
  lib/launchers/cloud_helper.rb
  lib/launchers/packet.rb
Labels: approved, lgtm, size/S

#239 add case OCP-21690 for tsb
  features/service_catalog_tsb/tsb.feature
  lib/openshift/cluster_service_class.rb
  lib/openshift/cluster_service_plan.rb
Labels: approved, lgtm, size/M

#213 added new openshift objects to help another PR
  lib/openshift/deployment.rb
  lib/openshift/ingress_controller.rb
  lib/openshift/service_monitor.rb
Labels: CoreAutomation, approved, size/M

#235 update login flow, add IDP option
  features/step_definitions/admin_console.rb
  lib/environment.rb
  lib/rules/web/console/base/login.xyaml
Labels: approved, lgtm, size/S

#244 add tsb case OCP-14477
  features/service_catalog_tsb/tsb.feature
Labels: approved, lgtm, size/M

#243 Fix typo of OCP-9638
  features/storage/iscsi.feature
Labels: approved, size/XS

#242 4.1 rules for web
  lib/rules/web/admin_console/4.1/actions.xyaml
  lib/rules/web/admin_console/4.1/check_links.xyaml
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/deployment.xyaml
  lib/rules/web/admin_console/4.1/environments.xyaml
  lib/rules/web/admin_console/4.1/filters.xyaml
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.1/projects.xyaml
  lib/rules/web/admin_console/4.1/secrets.xyaml
  lib/rules/web/admin_console/4.1/status.xyaml
  lib/rules/web/admin_console/4.1/storage.xyaml
Labels: approved, lgtm, size/XL

#245 add OCP-14477 for tsb v4.x
  features/service_catalog_tsb/tsb.feature
Labels: approved, lgtm, size/M

#247 rules for OCP-20954
  lib/rules/web/admin_console/4.1/deployment.xyaml
  lib/rules/web/admin_console/4.1/environments.xyaml
  lib/rules/web/admin_console/4.1/goto.xyaml
Labels: approved, lgtm, size/S

#246 Fix PV gid type (from int to string)
  features/storage/nfs.feature
Labels: approved, lgtm, size/XS

#249 RHEL8 jenkins slave agent
  tools/common.sh
  tools/install_os_deps.sh
  tools/jenkins/slaves/Dockerfile.rhel8
  tools/jenkins/slaves/Dockerfile.rhel8_base
  tools/os_deps/deps.yum.RHEL8
Labels: approved, lgtm, size/L

#248 RHEL8 jenkins slave agent
  tools/common.sh
  tools/install_os_deps.sh
  tools/jenkins/slaves/Dockerfile.rhel8
  tools/jenkins/slaves/Dockerfile.rhel8_base
  tools/os_deps/deps.yum.RHEL8
Labels: approved, lgtm, size/L

#250 fix OLM cluster logging installation
  features/step_definitions/logging.rb
Labels: CoreAutomation, approved, cluster-logging, lgtm

#251 Revert "RHEL8 jenkins slave agent"
  tools/common.sh
  tools/install_os_deps.sh
  tools/jenkins/slaves/Dockerfile.rhel8
  tools/jenkins/slaves/Dockerfile.rhel8_base
  tools/os_deps/deps.yum.RHEL8
Labels: approved, lgtm, size/L

#252 Support 4.2
  lib/rules/cli/4.2.yaml
  lib/rules/cli/kubectl-4.2.yaml
Labels: approved, lgtm, size/XS

#253 add one f5 router case
  features/routing/f5-router.feature
  lib/rules/cli/3.3.yaml
Labels: approved, lgtm, size/M

#255 auto OCP-21677
  features/step_definitions/logging.rb
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
Labels: approved, lgtm, size/S

#254 Add rules for case ocp-22330
  lib/rules/web/admin_console/4.1/check_links.xyaml
  lib/rules/web/admin_console/base/logout.xyaml
Labels: approved, lgtm, size/XS
