Repository openshift/verification-tests, pull requests merged in 2019-01, with the labels that each got.

#60 nextgen installer improvements
  tools/launch_instance.rb
Labels: approved, size/XS

#61 fix usage with URL vars file
  tools/launch_instance.rb
Labels: approved, size/XS

#62 ocp4 admin credentials
  config/config.yaml
  lib/admin_credentials.rb
Labels: approved, size/M

#59 some instructions
  tools/jenkins/slaves/README.adoc
  tools/launch_instance.rb
Labels: approved, size/S

#64 update scenario for OCP-11614
  features/online/images.feature
Labels: size/XS

#63 nodes auto-discovery and accessing on private IPs
  lib/environment.rb
  lib/host.rb
  lib/openshift/node.rb
  lib/ssh.rb
Labels: approved, size/L

#70 style updates to dockerfile
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved, size/S

#71 fix bug on missing bastion role
  lib/host.rb
Labels: approved, size/XS

#73 selectable floating IP pools
  lib/launchers/openstack10.rb
Labels: approved, size/M

#74 Fix case_id format
  lib/gherkin_parse.rb
Labels: size/XS

#58 refactor metering steps
  features/step_definitions/admin.rb
  features/step_definitions/metering.rb
  features/test/metering.feature
  lib/openshift/report.rb
  lib/rest_kubernetes.rb
Labels: CoreAutomation, Metering, size/L

#68 adding router related steps for 4.0
  features/step_definitions/route.rb
Labels: size/S

#76 update ocp-9736
  features/routing/abrouting.feature
  features/routing/config-manager.feature
  features/routing/haproxy-router.feature
  features/routing/http2.feature
  features/routing/logging.feature
  features/step_definitions/pod.rb
  features/step_definitions/route.rb
Labels: size/M

#77 Fixes for some outputs compatible issues
  features/cli/policy.feature
  features/cli/projects.feature
  features/cli/serviceaccount.feature
Labels: size/M

#75 delete cache parameter step
  features/networking/build.feature
Labels: size/S
