Repository openshift/verification-tests, pull requests merged in 2019-07, with the labels that each got.

#256 fix rules for secrets
  lib/rules/web/admin_console/4.1/goto.xyaml
Labels: approved, lgtm, size/XS

#230 Adding various scenarios to support SDN 411 - Blocking Machine-config-server port
  features/networking/pod.feature
  features/networking/service.feature
  features/step_definitions/networking.rb
Labels: size/L

#258 fix logging csc name change, and bug in parsing 'keep_installation' t…
  features/step_definitions/logging.rb
  features/test/logging_metrics.feature
Labels: CoreAutomation, approved, cluster-logging, lgtm, size/S

#259 Simplify the logic of default storage class
  features/storage/storage_class.feature
Labels: approved, lgtm, size/XS

#261 Simplify the logic of default storage class
  features/storage/storage_class.feature
Labels: approved, lgtm, size/XS

#263 Remove region/zone from storage class as 4.x does not support that
  features/storage/storage_class.feature
Labels: approved, lgtm, size/M

#260 fix OCP-19532
  lib/openshift/project.rb
  lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/filters.xyaml
Labels: approved, lgtm, size/S

#264 Fix rules for OCP-19577
  features/step_definitions/resources.rb
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/projects.xyaml
Labels: size/S

#265 Fix OCP-10465
  features/cli/policy.feature
Labels: approved, lgtm, size/S

#262 Add rules for case OCP-19653
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/goto.xyaml
Labels: approved, lgtm, size/S

#267 Automate OCP-24259
  features/storage/storage_class.feature
Labels: approved, lgtm, size/S

#266 Fix OCP-10467
  features/cli/policy.feature
Labels: approved, lgtm, size/XS

#268 auto 4.2 caseOCP-23681
  lib/rules/web/admin_console/4.1/browser_opts.yml
  lib/rules/web/admin_console/4.2/actions.xyaml
  lib/rules/web/admin_console/4.2/browser_opts.yml
  lib/rules/web/admin_console/4.2/check_links.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/deployment.xyaml
  lib/rules/web/admin_console/4.2/environments.xyaml
  lib/rules/web/admin_console/4.2/filters.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.2/projects.xyaml
  lib/rules/web/admin_console/4.2/secrets.xyaml
  lib/rules/web/admin_console/4.2/status.xyaml
  lib/rules/web/admin_console/4.2/storage.xyaml
Labels: approved, lgtm, size/XL

#271 Use simpler pvc/pod name to easier debug as they are in unique project
  features/storage/NoDiskConflict.feature
  features/storage/aws.feature
  features/storage/csi.feature
  features/storage/dynamic_provisioning.feature
  features/storage/fsType.feature
  features/storage/glusterfs.feature
  features/storage/nfs.feature
  features/storage/persistent_volume.feature
  features/storage/pre-bind.feature
  features/storage/quota.feature
  features/storage/rbd.feature
  features/storage/reclaim_policy.feature
  features/storage/security.feature
  features/storage/storage_class.feature
  features/storage/vsphere.feature
Labels: approved, lgtm, size/L

#272 Fix openstack auth-url
  lib/iaas/iaas.rb
Labels: approved, lgtm, size/XS

#273 Fix openstack auth-url
  lib/iaas/iaas.rb
Labels: approved, lgtm, size/XS

#269 Restore "RHEL8 jenkins slave agent"
  tools/install_os_deps.sh
  tools/jenkins/slaves/Dockerfile.rhel8
  tools/os_deps/deps.yum.RHEL7
Labels: approved, lgtm, size/XS

#270 ansible in RHEL8 image
  tools/jenkins/slaves/Dockerfile.rhel8
Labels: approved, lgtm, size/XS

#276 iSCSI initiator should only setup on nodes
  features/step_definitions/helper_services.rb
Labels: approved, lgtm, size/XS

#275 update click_button_on_page to click_buttonin 4.1
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
Labels: approved, lgtm, size/XS

#277 Cherry-pick packet support to v3
  lib/bushslicer.rb
  lib/launchers/cloud_helper.rb
  lib/launchers/packet.rb
Labels: approved, lgtm, size/S

#274 support to allocate floating ip from known network name
  lib/launchers/openstack10.rb
Labels: approved, lgtm, size/M

#280 Add steps for 4.x registry
  features/step_definitions/registry.rb
  lib/rules/cli/3.0.yaml
  lib/rules/cli/3.3.yaml
  lib/rules/cli/4.0.yaml
Labels: size/S

#281 Add oauth backup and restore step
  features/step_definitions/oauth.rb
Labels: approved, lgtm, size/S

#282 fix indentation and took out debug statement
  features/step_definitions/oauth.rb
Labels: CoreAutomation, approved, lgtm

#279 Split 13914 mapping the e2e test scripts
  features/build/buildlogic.feature
Labels: size/L

#284 Merge scenarios into scenario outlines
  features/storage/cloud_provider.feature
Labels: approved, lgtm, size/M

#285 support a_dns installation task
  tools/launch_instance.rb
Labels: approved, lgtm, size/M

#287 Merge scenarios into scenario outlines
  features/storage/cloud_provider.feature
Labels: approved, lgtm, size/M

#283 ocp 23543 - iptables binary and rules on sdn containers should be the same as host
  features/networking/sdn.feature
Labels: approved, do-not-merge/hold, lgtm, size/S

#286 Update some cases
  features/online/rolebindingrestriction.feature
  features/online/route.feature
Labels: approved, lgtm, size/S

#288 Remove alpha annotation storage-class (obsoleted since 3.4)
  features/cli/secrets.feature
  features/images/jenkins.feature
  features/quickstarts/quickstarts.feature
  features/storage/quota.feature
Labels: approved, lgtm, size/M

#289 add rules for ocp-21034
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
Labels: approved, lgtm, size/M

#290 Fix the version
  config/config.yaml
Labels: approved, lgtm, size/XS

#293 Update cases to fit 4.x
  features/build/buildconfig.feature
  features/build/dockerbuild.feature
  features/cli/oc_set_probe.feature
  features/cli/secrets.feature
Labels: approved, lgtm, size/M

#294 Pass idp type when jenkins enables openshift oauth
  features/step_definitions/images/jenkins.rb
  lib/rules/web/images/jenkins_2/jenkins_2.xyaml
Labels: approved, lgtm, size/XS

#291 update OCP-17285
  features/online/imagestreams.feature
Labels: approved, lgtm, size/L

#300 Add openshiftapiserver to the crd backup and restore
  features/step_definitions/crd.rb
  lib/openshift/open_shift_a_p_i_server.rb
  lib/world.rb
Labels: approved, lgtm, size/S

#298 Remove eol imagestreamtags
  features/build/buildlogic.feature
  features/cli/build.feature
  features/cli/create.feature
Labels: approved, lgtm, size/M

#295 auto OCP-9767
  features/routing/ipfailover.feature
  lib/rules/cli/3.3.yaml
Labels: approved, lgtm, size/M

#296 Add more time for oauth restore step
  features/step_definitions/oauth.rb
Labels: approved, lgtm, size/XS

#301 Merge azure scenario into scenario outlines
  features/storage/dynamic_provisioning.feature
Labels: approved, lgtm, size/M

#302 Merge azure scenario into scenario outlines
  features/storage/dynamic_provisioning.feature
Labels: approved, lgtm, size/M

#299 some fixes
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/environments.xyaml
  lib/rules/web/admin_console/4.2/filters.xyaml
  lib/rules/web/admin_console/4.2/secrets.xyaml
Labels: approved, lgtm, size/S

#305 fix metering to be able to run both Metering and MeteringConfig
  features/step_definitions/logging_metrics.rb
  features/step_definitions/metering.rb
  features/test/metering.feature
  lib/openshift/metering_config.rb
  lib/openshift/operator_group.rb
  lib/openshift/report_query.rb
Labels: approved, lgtm, size/L

#303 auto OCP-24423
  lib/rules/web/admin_console/4.2/deployment.xyaml
Labels: approved, lgtm, size/XS
