Repository openshift/verification-tests, pull requests merged in 2019-09, with the labels that each got.

#341 auto OCP-24342
  lib/rules/web/admin_console/4.2/configmap.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
Labels: approved, lgtm, size/XS

#342 add set_floating_ip function for IPI on OSP routes record
  lib/launchers/openstack10.rb
Labels: size/M

#335 some fixes
  lib/rules/web/admin_console/4.1/status.xyaml
  lib/rules/web/admin_console/4.2/status.xyaml
Labels: approved, lgtm, size/XS

#336 Add rules for OCP-21007
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/route.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/route.xyaml
  lib/rules/web/admin_console/base/logout.xyaml
Labels: approved, lgtm, size/L

#349 auto OCP-20932
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/overview.xyaml
  lib/rules/web/admin_console/4.2/actions.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/overview.xyaml
Labels: approved, lgtm, size/L

#350 some fixes
  lib/rules/web/admin_console/3.11/environments.xyaml
  lib/rules/web/admin_console/4.1/environments.xyaml
  lib/rules/web/admin_console/4.1/status.xyaml
  lib/rules/web/admin_console/4.2/environments.xyaml
  lib/rules/web/admin_console/4.2/status.xyaml
Labels: approved, lgtm, size/S

#345 Add merge type for patch command
  features/step_definitions/_constants.rb
  features/step_definitions/cli.rb
Labels: approved, lgtm, size/XS

#348 Fix some cases
  features/build/env.feature
  features/cli/build.feature
  features/cli/secrets.feature
Labels: approved, lgtm, size/M

#352 Add rules for ocp-24263
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.2/imagestream.xyaml
Labels: approved, lgtm, size/S

#353 auto OCP-21085
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/deployment.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
Labels: approved, lgtm, size/S

#355 Create imageregistry operator cluster resource
  lib/openshift/config_imageregistry_operator_openshift_io.rb
Labels: approved, lgtm, size/XS

#356 rules for OCP-25203
  lib/rules/web/admin_console/4.1/deployment.xyaml
  lib/rules/web/admin_console/4.1/goto.xyaml
Labels: approved, lgtm, size/S

#354 Add 4.2 rules for OCP-20849
  lib/rules/web/admin_console/4.2/deployment.xyaml
Labels: approved, lgtm, size/S

#357 add rules for auto ocp-21000
  lib/rules/web/admin_console/4.2/overview.xyaml
Labels: approved, lgtm, size/M

#347 helper for https://github.com/openshift/cucushift/pull/7083
  features/test/new_api.feature
  lib/openshift/flakes/route_spec.rb
  lib/openshift/route.rb
Labels: CoreAutomation, approved, lgtm, size/M

#359 fix for oc version output change
  lib/cli_executor.rb
Labels: approved, lgtm, size/XS

#362 fix typo in route_spec.rb
  lib/cli_executor.rb
  lib/openshift/flakes/route_spec.rb
Labels: size/XS

#363 minor update
  lib/cli_executor.rb
Labels: approved, lgtm, size/XS

#364 Add 4.1 rules for deployment image
  lib/rules/web/admin_console/4.1/deployment.xyaml
Labels: approved, lgtm, size/S

#360 Update ocp-13509, 15017, 13507, 15465
  features/networking/egress-ingress.feature
  features/networking/egress-ip.feature
Labels: approved, lgtm, size/M

#340 modify steps to deploy logging operators
  features/step_definitions/logging.rb
  features/step_definitions/logging_metrics.rb
  features/support/clusterlogging_env.rb
  features/test/logging_metrics.feature
  lib/openshift/cluster_logging.rb
  lib/openshift/elasticsearch.rb
Labels: approved, lgtm, size/L

#366 touch a little message bus tools
  tools/polarshift.rb
  tools/stompbus/stompbus.rb
Labels: approved, lgtm, size/S

#365 touch a little message bus tools
  tools/polarshift.rb
  tools/stompbus/stompbus.rb
Labels: approved, lgtm, size/S

#358 Add rule for ocp-23610
  lib/rules/web/admin_console/4.2/catalog.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
Labels: approved, lgtm, size/S

#367 fix rule
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
Labels: approved, lgtm, size/XS
