Repository openshift/verification-tests, pull requests merged in 2019-04, with the labels that each got.

#132 Skip node InitatorName config for iscsi as no need in 4.0
  features/step_definitions/helper_services.rb
Labels: approved, lgtm, size/XS

#134 Change jenkins agent images to slave images
  features/step_definitions/images/jenkins.rb
Labels: approved, lgtm, size/S

#140 remove case OCP-15395 in tier1
  features/svc-catalog_asb/asb.feature
Labels: lgtm, size/M

#139 remove OCP-15395 in tier1
  features/svc-catalog_asb/asb.feature
Labels: approved, lgtm, size/M

#143 update asb namespace in v4.0
  features/step_definitions/cluster_service_broker.rb
  features/svc-catalog_asb/asb.feature
Labels: approved, lgtm, size/XS

#138 HostPath for 4.x
  features/storage/hostpath.feature
Labels: approved, lgtm, size/M

#137 modify the rules for web login
  lib/rules/web/console/base/login.xyaml
Labels: size/S

#146 Add instructions for downloading and installing Web Driver
  README.adoc
  doc/configuration.adoc
Labels: approved, lgtm, size/S

#144 Add instructions for downloading and installing Web Driver
  README.adoc
  doc/configuration.adoc
Labels: approved, lgtm, size/S

#147 add oc 4.1
  lib/rules/cli/4.1.yaml
Labels: lgtm, size/XS

#142 Update clone sc step to fix pvc bound issue
  features/step_definitions/storage_class.rb
Labels: approved, lgtm, size/XS

#149 change installation method to default to OLM
  features/step_definitions/metering.rb
Labels: CoreAutomation, Metering, approved, lgtm

#148 [networking] initiate the multus related testing automation
  features/networking/multus.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/M

#150 [networking] automated more macvlan cases
  features/networking/multus.feature
Labels: approved, lgtm, size/L

#145 Added support for cluster upgrade and check status
  features/step_definitions/installer.rb
  features/test/new_api.feature
  lib/openshift/cluster_version.rb
  lib/rules/cli/4.0.yaml
Labels: CoreAutomation, approved, size/M

#154 add kubectl for oc 4.1
  lib/rules/cli/kubectl-4.1.yaml
Labels: approved, lgtm, size/XS

#153 added methods to get clusterSerivceBrokerName
  lib/openshift/cluster_service_class.rb
  lib/openshift/cluster_service_plan.rb
Labels: CoreAutomation, approved, lgtm

#155 change condition check to default to cached: false
  lib/openshift/resource.rb
Labels: CoreAutomation, approved, size/XS

#152 [networking] automate the host-device cni plugin case for multus
  features/networking/multus.feature
Labels: approved, lgtm, size/M

#159 Update OCP-18796 for 4.x
  features/storage/storage_object_in_use_protection.feature
  lib/rules/cli/4.0.yaml
Labels: approved, lgtm, size/S

#158 Fix OCP-10873
  features/cli/oc_expose.feature
Labels: size/XS

#160 Update OCP-17254 for 4.x
  features/storage/storage_object_in_use_protection.feature
Labels: approved, lgtm, size/S

#164 Fix OCP-11933 pvc not bound status
  features/storage/persistent_volume.feature
Labels: approved, lgtm, size/XS

#162 Update OCP-17253 for 4.x
  features/storage/storage_object_in_use_protection.feature
Labels: approved, lgtm, size/XS

#156 Added Scenario for OCP-22706
  features/networking/operator.feature
Labels: size/M

#151 add case OCP-21690 for tsb
  features/service_catalog_tsb/tsb.feature
Labels: size/M

#166 Update OCP-9638 for 4.x
  features/storage/iscsi.feature
Labels: approved, lgtm, size/M

#165 [networking] Automate network-operator cases
  features/networking/operator.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/L

#167 Fix OCP-19631
  features/cli/build.feature
  features/registry/is.feature
  features/registry/registry.feature
  features/registry/remote.feature
Labels: size/M

#173 clustersourceconfig name changed for metering
  features/step_definitions/metering.rb
Labels: Metering, approved, lgtm, size/XS

#171 work with elastic IPs
  config/config.yaml
  lib/launchers/amz.rb
Labels: approved, lgtm, size/M

#177 'Failing' type to 'Degraded' change in nw operator use cases
  features/networking/operator.feature
  features/step_definitions/networking.rb
Labels: size/M

#161 [networking] automated multus cases for multiple cni plugins
  features/networking/multus.feature
  features/step_definitions/networking.rb
Labels: size/L

#170 work with elastic IPs
  config/config.yaml
  lib/launchers/amz.rb
Labels: approved, lgtm, size/M

#172 workaround bug 1610661
  features/step_definitions/pv.rb
  lib/openshift/cluster_resource.rb
  lib/openshift/project_resource.rb
  lib/openshift/resource.rb
Labels: approved, lgtm, size/S

#178 allow allocating elastic IPs on cretion of VMs
  config/config.yaml
  lib/launchers/amz.rb
Labels: approved, lgtm, size/XS

#179 allow allocating elastic IPs on cretion of VMs
  config/config.yaml
  lib/launchers/amz.rb
Labels: approved, lgtm, size/XS

#180 update default router pod label
  features/step_definitions/route.rb
Labels: approved, lgtm, size/XS

#181 Fix OCP-10904
  features/cli/build.feature
  features/registry/remote.feature
Labels: approved, lgtm, size/M
