Repository openshift/verification-tests, pull requests merged in 2019-02, with the labels that each got.

#78 added support to install metering using OLM
  features/step_definitions/metering.rb
  lib/openshift/catalog_source_config.rb
  lib/openshift/report_data_source.rb
  lib/rules/cli/3.3.yaml
Labels: CoreAutomation, Metering, size/M

#81 selectable floating IP pools
  tools/launch_instance.rb
Labels: size/M

#79 fix get bearer token issue for splitted oauth server endpoint
  lib/login.rb
Labels: approved, lgtm, size/S

#83 support admin kubeconfig from URL
  config/config.yaml
  lib/admin_credentials.rb
  lib/environment.rb
Labels: approved, size/M

#82 Auto case for OCP-22283
  features/cli/pod.feature
Labels: approved, size/S

#86 generating host list with flags and small fixes
  lib/admin_credentials.rb
  lib/launchers/openstack10.rb
  tools/launch_instance.rb
Labels: approved, size/XS

#87 fix issue with rest request step because User needs to be APIAccessor…
  features/step_definitions/common.rb
  features/test/rest.feature
Labels: CoreAutomation, approved, lgtm, size/XS

#89 fix for oc version
  lib/cli_executor.rb
Labels: lgtm, size/XS

#93 Add authentication endpoint for 4.x
  lib/environment.rb
Labels: approved, lgtm, size/S

#88 get rest api to work with 4.0 api structure, also took out oapi refer…
  lib/rest.rb
  lib/rest_kubernetes.rb
  lib/rest_openshift.rb
Labels: CoreAutomation, approved, lgtm, size/M
