Repository openshift/verification-tests, pull requests merged in 2019-08, with the labels that each got.

#309 backport fix from 658452bb
  lib/rules/web/images/jenkins_2/jenkins_2.xyaml
  tools/openshift-ci/verification_tests_ci_entrypoint.sh
Labels: approved, lgtm, size/M

#307 Use topology aware dynamic provisioning in the clouds
  features/step_definitions/storage_class.rb
Labels: approved, lgtm, size/XS

#304 Remove eol istags
  features/build/buildlogic.feature
  features/cli/build.feature
  features/cli/scale.feature
Labels: approved, lgtm, size/M

#310 Update github raw file URL
  features/step_definitions/helper_services.rb
Labels: approved, lgtm, size/XS

#313 Remove SystemGroup and SystemUser definition
  features/step_definitions/policy.rb
  lib/openshift/cluster_role_binding.rb
  lib/openshift/role_binding.rb
  lib/openshift/system_group.rb
  lib/openshift/system_user.rb
Labels: approved, lgtm, size/M

#317 Update OCP-9781
  features/online/build.feature
Labels: approved, lgtm, size/XS

#319 auto OCP-21772 check user starter guide on projects
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.1/status.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.2/status.xyaml
Labels: approved, lgtm, size/M

#324 Fix parameters for OCP-10108/10112
  features/storage/pre-bind.feature
Labels: approved, lgtm, size/XS

#318 Add step to update operator operand managementstate
  features/step_definitions/operator.rb
Labels: approved, lgtm, size/S

#325 Fix scenario dynamic provisioning
  features/storage/dynamic_provisioning.feature
Labels: approved, lgtm, size/S

#311 Add step to patch 4.x default storage class to non-default
  features/step_definitions/storage_class.rb
  features/test/storage_class.feature
Labels: approved, lgtm, size/M

#328 Cache resource storage class
  features/step_definitions/storage_class.rb
Labels: approved, lgtm, size/XS

#316 duplicate of https://github.com/openshift/verification-tests/pull/315/files
  lib/openshift/deployment.rb
Labels: CoreAutomation, approved, lgtm, size/XS

#315 added method to get metadata.generation
  lib/openshift/deployment.rb
Labels: CoreAutomation, approved, lgtm, size/XS

#327 Default storage class can not be deleted in 4.x
  features/step_definitions/cluster_configuration/csi.rb
  features/storage/persistent_volume.feature
  features/storage/storage_class.feature
  features/web/pvc.feature
Labels: approved, lgtm, size/XS

#297 Fix cases in 4.x
  features/build/env.feature
  features/cli/build.feature
Labels: approved, lgtm, size/S

#320 WIP admin console must read browser_opts.yml
  features/step_definitions/admin_console.rb
Labels: approved, do-not-merge/work-in-progress, size/XS

#323 Fix rules for OCP-19669: landing page and empty resources detail page
  lib/rules/web/admin_console/3.11/status.xyaml
  lib/rules/web/admin_console/4.1/status.xyaml
  lib/rules/web/admin_console/4.2/status.xyaml
Labels: approved, lgtm, size/S

#321 fix metering creation logic to skip if it's already installed.
  features/step_definitions/metering.rb
Labels: CoreAutomation, Metering, approved, size/S

#306 Fix OCP-19577
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.1/projects.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.2/projects.xyaml
Labels: size/S

#322 Add rules for ocp-21004
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.1/route.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.2/route.xyaml
Labels: approved, lgtm, size/M

#329 support resources with dots in their Kind field
  lib/admin_credentials.rb
  lib/openshift/cluster_role.rb
  lib/openshift/config_samples_operator_openshift_io.rb
  lib/openshift/resource.rb
  lib/openshift/security_context_constraints.rb
  lib/world.rb
Labels: approved, lgtm, size/M

#326 added support for machineautoscaler
  features/cluster_configuration/autoscaling.feature
  features/step_definitions/cluster_configuration/cluster_config.rb
  features/step_definitions/machine_set.rb
  features/step_definitions/node.rb
  features/test/node.feature
  lib/openshift/machine_set.rb
  lib/openshift/node.rb
Labels: CoreAutomation, approved, size/M

#332 [hotfix] rename #type to #kind and fix logic
  lib/openshift/resource.rb
Labels: approved, lgtm, size/S

#330 add step to support extracting IDP creds
  features/step_definitions/oauth.rb
  features/test/oauth.feature
  lib/openshift/o_auth.rb
Labels: CoreAutomation, approved, size/M

#333 v3 fixes CI fixes
  tools/common.sh
  tools/launch_instance.rb
  tools/openshift-ci/verification_tests_ci_entrypoint.sh
Labels: approved, lgtm, size/M

#334 verification_tests_ci_entrypoint.sh should call all ruby commands with SCL
  tools/openshift-ci/verification_tests_ci_entrypoint.sh
Labels: approved, lgtm, size/XS

#337 fix array filtering in which elements are present
  lib/openshift/o_auth.rb
Labels: CoreAutomation, approved, lgtm, size/XS

#338 update manage cmd for 4.x
  lib/rules/cli/4.0.yaml
Labels: approved, lgtm, size/XS

#343 Add elasticsearch operator ready to steps
  features/step_definitions/logging.rb
Labels: approved, lgtm, size/XS
