Repository openshift/verification-tests, pull requests merged in 2019-03, with the labels that each got.

#97 Fix check_doc_get_started_with_cli and check_dim_resource_list
  lib/rules/web/admin_console/4.0/check_links.xyaml
  lib/rules/web/admin_console/4.0/status.xyaml
Labels: size/XS

#96 update the project delete step
  lib/openshift/project.rb
Labels: size/XS

#95 Auto case OCP-22515
  features/cli/create.feature
Labels: size/M

#56 Make csi driver deployment as a case so that can be run as CVP
  features/step_definitions/cluster_configuration/csi.rb
  features/storage/csi.feature
Labels: size/M

#100 proxy command should not ask
  lib/host.rb
Labels: approved, size/XS

#101 proxy command should not ask
  lib/host.rb
Labels: size/XS

#99 Add post_role_api step for OCP-22565
  lib/rest_openshift.rb
Labels: approved, lgtm, size/S

#103 iSCSI initiator should only setup on nodes
  features/step_definitions/helper_services.rb
Labels: approved, lgtm, size/XS

#94 added support when user specify a local kubeconfig location
  lib/admin_credentials.rb
Labels: CoreAutomation, approved, size/S

#104 4.0 oc rules in new file
  lib/rules/cli/4.0.yaml
Labels: approved, lgtm, size/XXL

#102 Delete 'grep' in sh and update it to scan
  features/networking/pod.feature
Labels: approved, lgtm, size/XS

#105 fix issue when YAML uses anchoring
  lib/collections.rb
  lib/configuration.rb
Labels: approved, lgtm, size/S

#106 fix issue when YAML uses anchoring
  lib/collections.rb
  lib/configuration.rb
Labels: approved, size/S

#107 updated owners file to remove cjryan
  OWNERS
Labels: size/XS

#109 update for case 10717
  features/cli/deploy.feature
Labels: approved, lgtm, size/XS

#111 make jira create issue work and allow running on command line
  lib/jira_rht.rb
Labels: approved, lgtm, size/S

#112 make jira create issue work and allow running on command line
  lib/jira_rht.rb
Labels: approved, size/S

#108 Adding scenario OCP-19810 for v3
  features/networking/pod.feature
Labels: size/M

#110 Fix web rules
  lib/rules/web/admin_console/4.0/common_ui_elements.xyaml
Labels: approved, lgtm, size/S

#113 add ocp4 registry
  features/step_definitions/registry.rb
Labels: approved, lgtm, size/XS

#115 Update repository url
  config/config.yaml
  doc/webauto.adoc
Labels: size/XS

#114 Update repository url
  config/config.yaml
  doc/webauto.adoc
Labels: approved, size/XS

#116 a couple of improvements
  lib/jira_rht.rb
  lib/launchers/amz.rb
  tools/tcms_query.rb
Labels: approved, lgtm, size/M

#117 modernize jira code
  lib/jira_rht.rb
  tools/tcms_query.rb
Labels: approved, lgtm, size/S

#121 revert changes to populate method, perhaps we need nother version of …
  lib/rest_kubernetes.rb
Labels: CoreAutomation, approved, lgtm, size/XS

#119 support for test case queries
  lib/http.rb
  lib/polarshift/request.rb
  tools/polarshift.rb
Labels: approved, lgtm, size/M

#120 support for test case queries
  lib/http.rb
  lib/polarshift/request.rb
  tools/polarshift.rb
Labels: approved, lgtm, size/M

#123 handle differnt api url depending on the type of operation
  lib/rest_kubernetes.rb
Labels: CoreAutomation, approved, lgtm, size/XS

#128 fix OCP-13839 case ID
  features/routing/route.feature
Labels: approved, lgtm, size/XS

#127 added api support for clusteroperator and clusterversion for 4.x
  lib/openshift/cluster_operator.rb
  lib/openshift/cluster_version.rb
Labels: CoreAutomation, approved, lgtm

#130 fix the name of node service for 4.x
  features/networking/sdn.feature
  features/step_definitions/networking.rb
  features/step_definitions/node.rb
  lib/platform/node_service.rb
Labels: approved, lgtm, size/S

#129 update router pod label
  features/step_definitions/route.rb
Labels: size/XS

#124 Step for cluster crd backup restore
  features/step_definitions/crd.rb
  lib/openshift/kube_a_p_i_server.rb
  lib/world.rb
Labels: size/S

#131 moved methods to lib/resource and added a version check
  lib/openshift/cluster_operator.rb
  lib/openshift/resource.rb
Labels: CoreAutomation, approved, lgtm, size/S

#98 Modify jenkins steps to adjust 4.0 change
  features/step_definitions/images/jenkins.rb
  lib/environment.rb
  lib/rules/web/images/jenkins_2/jenkins_2.xyaml
Labels: approved, lgtm, size/L

#126 Ocp 22704
  features/networking/operator.feature
Labels: approved, lgtm, size/S

#136 AWS improvements
  lib/launchers/amz.rb
  tools/aws.rb
  tools/launch_instance.rb
Labels: approved, lgtm, size/L

#135 AWS improvements
  lib/launchers/amz.rb
  tools/aws.rb
  tools/launch_instance.rb
Labels: approved, lgtm, size/L
