Repository openshift/verification-tests, pull requests merged in 2019-11, with the labels that each got.

#431 Fix checkpoint of using default storage class
  features/storage/storage_class.feature
Labels: approved, lgtm, size/S

#430 added #ready? method for resouce 'machine'
  lib/openshift/machine.rb
Labels: CoreAutomation, approved, lgtm, size/XS

#428 Add rules for ocp-20964
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/storage.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/storage.xyaml
  lib/rules/web/console/base/login.xyaml
Labels: approved, lgtm, size/M

#433 Automate OCP-25789
  features/storage/storage_class.feature
Labels: approved, lgtm, size/S

#424 enhancements for logging 4.1
  features/logging/collector.feature
  lib/openshift/cluster_logging.rb
Labels: approved, lgtm, size/M

#434 added allow_explicit_upgrade option to oc upgrade
  features/test/new_api.feature
  lib/rules/cli/4.0.yaml
Labels: CoreAutomation, approved, lgtm, size/XS

#437 describe pod if status not reached
  features/step_definitions/pod.rb
Labels: approved, lgtm, size/XS

#439 Replace obsoleted cmd "oc volume" with "oc set volume"
  features/cli/oc_volume.feature
  features/step_definitions/helper_services.rb
  features/step_definitions/registry.rb
  features/storage/add_update_delete_volume.feature
  lib/rules/cli/4.0.yaml
Labels: approved, lgtm, size/M

#436 fix issue: undefined method `map' for nil:NilClass (NoMethodError)
  features/logging/collector.feature
Labels: approved, lgtm, size/XS

#440 Ensure secret prometheus-k8s-token-xxx is returned
  features/machine/machine.feature
Labels: approved, lgtm, size/XS

#442 add rule files for 4.3
  lib/rules/web/admin_console/4.3/actions.xyaml
  lib/rules/web/admin_console/4.3/browser_opts.yml
  lib/rules/web/admin_console/4.3/catalog.xyaml
  lib/rules/web/admin_console/4.3/check_links.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/configmap.xyaml
  lib/rules/web/admin_console/4.3/customizations.xyaml
  lib/rules/web/admin_console/4.3/deployment.xyaml
  lib/rules/web/admin_console/4.3/environments.xyaml
  lib/rules/web/admin_console/4.3/filters.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/imagestream.xyaml
  lib/rules/web/admin_console/4.3/node.xyaml
  lib/rules/web/admin_console/4.3/overview.xyaml
  lib/rules/web/admin_console/4.3/projects.xyaml
  lib/rules/web/admin_console/4.3/route.xyaml
  lib/rules/web/admin_console/4.3/secrets.xyaml
  lib/rules/web/admin_console/4.3/status.xyaml
  lib/rules/web/admin_console/4.3/storage.xyaml
Labels: approved, lgtm, size/XXL

#444 update image tag
  features/build/dockerbuild.feature
Labels: approved, lgtm, size/XS

#389 auto case OCP-22558 OCP-24292
  features/logging/deploy_logging_operators_via_console.feature
  features/step_definitions/logging.rb
  lib/openshift/subscription.rb
  lib/rules/web/admin_console/4.2/goto.xyaml
Labels: approved, lgtm, size/M

#445 update image tag
  features/build/env.feature
  features/cli/build.feature
  features/cli/create.feature
Labels: approved, lgtm, size/S

#443 Make sure storageClassName is a string
  features/storage/pre-bind.feature
Labels: approved, lgtm, size/S

#449 4.3 fixes
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/status.xyaml
Labels: approved, lgtm, size/S

#451 fix web rules
  lib/rules/web/admin_console/4.3/catalog.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/deployment.xyaml
Labels: approved, lgtm, size/S

#453 Fix OCP-11613
  features/storage/cloud_provider.feature
Labels: approved, lgtm, size/M

#457 Testing metrics is exposed on https
  features/machine/machine.feature
Labels: approved, lgtm, size/S

#447 Bug fix for OCP-21814
  features/networking/service.feature
Labels: approved, lgtm, size/XS

#448 Ocp 22606
  features/test/upgrade.feature
Labels: approved, lgtm, size/M

#458 Fix 4.x oauth team test cases steps
  features/cli/pod.feature
  features/cli/policy.feature
  features/cli/projects.feature
  features/cli/serviceaccount.feature
  lib/environment.rb
Labels: approved, lgtm, size/S

#450 4.3 rules fixes
  lib/rules/web/admin_console/4.3/actions.xyaml
  lib/rules/web/admin_console/4.3/catalog.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/environments.xyaml
Labels: approved, lgtm, size/S

#452 Auto OCP-25707
  features/networking/sdn.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/S

#456 Uncordon node so pods are schedulable
  features/storage/node_operations.feature
Labels: approved, lgtm, size/XS

#463 rules added for OCP-25816
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/monitoring.xyaml
Labels: approved, lgtm, size/S

#454 fix web cases
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/catalog.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/actions.xyaml
  lib/rules/web/admin_console/4.3/catalog.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/environments.xyaml
  lib/rules/web/admin_console/4.3/overview.xyaml
Labels: approved, lgtm, size/L

#441 private cluster proxy support
  features/step_definitions/logging_metrics.rb
  features/step_definitions/metering.rb
  features/step_definitions/net.rb
  features/step_definitions/web.rb
  features/support/env.rb
  lib/bushslicer.rb
  lib/cli_executor.rb
  lib/common.rb
  lib/environment.rb
  lib/http.rb
  lib/login.rb
  lib/openshift/route.rb
  lib/platform/master_service.rb
  lib/rest.rb
  lib/rules/cli/4.0.yaml
  lib/webauto/chrome_extension.rb
  lib/webauto/resource/chrome_crx3/README
  lib/webauto/resource/chrome_crx3/crx3.pb.rb
  lib/webauto/resource/chrome_crx3/crx3.proto
  lib/webauto/resource/chrome_proxy/background.js.erb
  lib/webauto/resource/chrome_proxy/manifest.json
  lib/webauto/web4cucumber.rb
  lib/webauto/webconsole_executor.rb
  tools/shell_proxy.sh
Labels: approved, lgtm, size/L

#461 Update to use ruby-25-* images to do docker build
  features/build/buildconfig.feature
  features/build/buildlogic.feature
  features/build/stibuild.feature
  features/cli/oc_import_image.feature
  features/cli/secrets.feature
  features/registry/remote.feature
Labels: approved, lgtm, size/M

#446 some fixes for CI testing
  features/step_definitions/logging.rb
  lib/rules/web/images/logging/login.xyaml
Labels: approved, lgtm, size/M

#460 add rule files for OCP-25791,OCP-25840
  lib/openshift/console_links_console_openshift_io.rb
  lib/rules/web/admin_console/4.3/check_links.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
Labels: approved, lgtm, size/S

#464 Revert "private cluster proxy support"
  features/step_definitions/logging_metrics.rb
  features/step_definitions/metering.rb
  features/step_definitions/net.rb
  features/step_definitions/web.rb
  features/support/env.rb
  lib/bushslicer.rb
  lib/cli_executor.rb
  lib/common.rb
  lib/environment.rb
  lib/http.rb
  lib/login.rb
  lib/openshift/route.rb
  lib/platform/master_service.rb
  lib/rest.rb
  lib/rules/cli/4.0.yaml
  lib/webauto/chrome_extension.rb
  lib/webauto/resource/chrome_crx3/README
  lib/webauto/resource/chrome_crx3/crx3.pb.rb
  lib/webauto/resource/chrome_crx3/crx3.proto
  lib/webauto/resource/chrome_proxy/background.js.erb
  lib/webauto/resource/chrome_proxy/manifest.json
  lib/webauto/web4cucumber.rb
  lib/webauto/webconsole_executor.rb
  tools/shell_proxy.sh
Labels: approved, size/L

#404 Add rules for OCP-24287 about masthead, add consoleclidownload resource
  lib/openshift/console_cli_download_console_openshift_io.rb
  lib/rules/web/admin_console/4.2/check_links.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
Labels: approved, lgtm, size/M

#462 Fix OCP-9639
  features/storage/hostpath.feature
Labels: approved, lgtm, size/S

#466 Revert "Revert "private cluster proxy support""
  Gemfile
  features/step_definitions/logging_metrics.rb
  features/step_definitions/metering.rb
  features/step_definitions/net.rb
  features/step_definitions/web.rb
  features/support/env.rb
  lib/bushslicer.rb
  lib/cli_executor.rb
  lib/common.rb
  lib/environment.rb
  lib/http.rb
  lib/login.rb
  lib/openshift/route.rb
  lib/platform/master_service.rb
  lib/rest.rb
  lib/rules/cli/4.0.yaml
  lib/webauto/chrome_extension.rb
  lib/webauto/resource/chrome_crx3/README
  lib/webauto/resource/chrome_crx3/crx3.pb.rb
  lib/webauto/resource/chrome_crx3/crx3.proto
  lib/webauto/resource/chrome_proxy/background.js.erb
  lib/webauto/resource/chrome_proxy/manifest.json
  lib/webauto/web4cucumber.rb
  lib/webauto/webconsole_executor.rb
  tools/shell_proxy.sh
Labels: approved, do-not-merge/hold, size/L

#435 Simplify machine steps
  features/machine/machine.feature
  features/step_definitions/machine.rb
  features/step_definitions/machine_set.rb
  lib/openshift/machine.rb
  lib/openshift/machine_set.rb
Labels: size/L

#467 Update proxy server label
  features/step_definitions/helper_services.rb
Labels: approved, lgtm, size/XS

#459 rules update for OCP-20932 OCP-24423
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/overview.xyaml
Labels: approved, lgtm, size/S

#465 auto OCP-25764,OCP-25795
  features/step_definitions/machine.rb
  lib/rules/web/admin_console/4.3/builds.xyaml
  lib/rules/web/admin_console/4.3/filters.xyaml
  lib/rules/web/admin_console/4.3/node.xyaml
Labels: approved, lgtm, size/S

#416 Auto console notification case OCP-24316
  lib/openshift/console_notifications_console_openshift_io.rb
  lib/rules/web/admin_console/4.2/customizations.xyaml
  lib/world.rb
Labels: approved, lgtm, size/S

#471 proper file location when loading ruby files
  tools/launch_instance.rb
Labels: approved, size/XS

#470 fix OCP-23044
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
Labels: approved, lgtm, size/XS

#472 Add reviewers to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#476 Update the wait time
  features/svc-catalog_asb/svc-catalog.feature
Labels: approved, lgtm, size/XS

#474 Fix checkpoint of using default storage class
  features/storage/storage_class.feature
Labels: approved, lgtm, size/S

#480 update ruby-22 failed
  features/cli/deploy.feature
Labels: approved, lgtm, size/XS
