Repository openshift/verification-tests, pull requests merged in 2019-05, with the labels that each got.

#182 Update metering.rb
  features/step_definitions/metering.rb
Labels: CoreAutomation, Metering, approved, size/S

#184 [Hotfix] no rules found for option: wait
  lib/rules/cli/3.3.yaml
Labels: approved, lgtm, size/XS

#188 add support for test run type on creation
  lib/polarshift/request.rb
Labels: approved, size/XS

#189 add support for test run type on creation
  lib/polarshift/request.rb
Labels: approved, size/XS

#37 Added bash script to run as part of aos-azure ci-operator.
  tools/openshift-ci/verification_tests_ci_entrypoint.sh
Labels: size/S

#190 Added bash script to run as part of aos-azure ci-operator. (#37)
  tools/openshift-ci/verification_tests_ci_entrypoint.sh
Labels: approved, size/S

#183 update OCP-10228
  features/storage/storage_class.feature
Labels: size/S

#185 added a query tool to look for payload that has a particualr fix base…
  tools/find_image.rb
Labels: CoreAutomation, approved, lgtm, size/M

#186 up the wait timeout to 120
  features/step_definitions/metering.rb
Labels: CoreAutomation, Metering, approved, lgtm

#187 fix OCP-13641
  features/web/overview.feature
  lib/rules/web/console/3.10/overview.xyaml
  lib/rules/web/console/3.11/overview.xyaml
  lib/rules/web/console/3.6/overview.xyaml
  lib/rules/web/console/3.7/overview.xyaml
  lib/rules/web/console/3.9/overview.xyaml
Labels: approved, lgtm, size/S

#191 report object changed from spec.generationQuery to just spec.query
  lib/openshift/report.rb
Labels: CoreAutomation, Metering, approved, lgtm, size/XS

#163 clusterlogging installation via OLM
  features/cluster_configuration/cluster_logging_operator.feature
  features/step_definitions/logging.rb
  features/step_definitions/logging_metrics.rb
  features/test/logging_metrics.feature
  features/test/new_api.feature
  lib/openshift/cluster_logging.rb
  lib/openshift/install_plan.rb
  lib/openshift/package_manifest.rb
  lib/openshift/project.rb
  lib/openshift/subscription.rb
Labels: CoreAutomation, approved, cluster-logging, size/L

#192 update logging CRD to the correct URL
  features/step_definitions/logging.rb
Labels: CoreAutomation, Metering

#193 Remove parameter zone in 4.x
  features/storage/storage_class.feature
Labels: approved, lgtm, size/XS

#197 project name change back to openshift-
  features/step_definitions/cluster_service_broker.rb
  features/svc-catalog_asb/asb.feature
Labels: approved, lgtm, size/XS

#195 Update step about have volume and save volume id in the clipboard
  features/step_definitions/pv.rb
Labels: approved, lgtm, size/XS

#198 allow ruby expressions in template
  tools/launch_instance.rb
Labels: approved, size/XS

#176 Updated scripts for 4.x
  features/build/buildlogic.feature
  features/cli/oc_set_build_hook.feature
  features/cli/resources.feature
Labels: approved, lgtm, size/S

#157 update no project return step for 4.x
  features/step_definitions/resources.rb
Labels: approved, lgtm, size/XS

#199 No need to create storage class for OCP-10447
  features/cli/policy.feature
  lib/rules/cli/4.0.yaml
Labels: approved, lgtm, size/M

#196 update to the default interface of node for multus
  features/networking/multus.feature
  features/step_definitions/networking.rb
Labels: size/M

#204 No need to create storage class for OCP-10447
  features/cli/policy.feature
  lib/rules/cli/3.3.yaml
Labels: approved, lgtm, size/M

#202 deprecated the 'new-app' command for OCP-15600
  features/svc-catalog_asb/svc-catalog.feature
Labels: approved, lgtm, size/S

#205 Update OCP-16485
  features/storage/regression.feature
Labels: approved, lgtm, size/XS

#200 added check for clusteroperators after upgrade to make sure no DEGRAD…
  features/step_definitions/installer.rb
  features/step_definitions/operators.rb
  features/test/new_api.feature
  features/test/operators.feature
  lib/openshift/cluster_operator.rb
Labels: CoreAutomation, Metering, approved, size/M

#206 Improvements
  config/config.yaml
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/S

#207 deprecated the 'new-app' command for asb/tsb test scenarios
  features/svc-catalog_asb/apb-update.feature
  features/svc-catalog_asb/asb.feature
  features/svc-catalog_asb/svc-catalog.feature
Labels: approved, lgtm, size/L

#209 predictable workdir under Jenkins
  lib/host.rb
Labels: approved, lgtm, size/S

#208 predictable workdir under Jenkins
  lib/host.rb
Labels: approved, lgtm, size/S

#210 enable svcat in 4.1
  lib/rules/cli/svcat-4.1.yaml
Labels: approved, lgtm, size/XS

#211 fix various bugs with metering automation
  features/step_definitions/metering.rb
  lib/openshift/report_data_source.rb
Labels: CoreAutomation, Metering, approved, lgtm, size/S

#212 change methods for cached: true, and calling it with false
  features/step_definitions/metering.rb
  lib/openshift/report_data_source.rb
Labels: CoreAutomation, Metering, approved, lgtm, size/S

#203 OCP_16217 fixes to be merged in v3 branch
  features/networking/sdn.feature
  features/step_definitions/networking.rb
Labels: size/M

#194 Fix scenarios
  features/networking/operator.feature
  features/networking/sdn.feature
  features/step_definitions/networking.rb
Labels: size/M

#215 fix parameters in case for oc process
  features/svc-catalog_asb/asb.feature
Labels: approved, lgtm, size/XS

#214 added get run information based on run id
  tools/polarshift.rb
Labels: CoreAutomation, approved, lgtm, size/S

#216 Update OCP-9940 for 4.x to not interfere with each other
  features/storage/pre-bind.feature
Labels: approved, lgtm, size/S

#221 Fix OCP-11943
  features/cli/build.feature
Labels: approved, lgtm, size/XS

#218 a smarter (and correct) way to determine if a reportdatasource should…
  features/step_definitions/metering.rb
  lib/openshift/report_data_source.rb
Labels: CoreAutomation, Metering, approved, lgtm, size/XS

#223 fix running a command without arguments during install
  lib/local_process.rb
  tools/launch_instance.rb
Labels: approved, lgtm, size/S

#222 fix running a command without arguments during install
  lib/local_process.rb
  tools/launch_instance.rb
Labels: approved, lgtm, size/S

#217 Update OCP-14173
  features/storage/quota.feature
Labels: approved, lgtm, size/S

#224 command might be array of two element array so handle it
  lib/local_process.rb
Labels: approved, size/XS

#226 more robust CI script
  config/cucumber.yml
  tools/common.sh
  tools/openshift-ci/verification_tests_ci_entrypoint.sh
Labels: approved, size/M
