Repository openshift/verification-tests, pull requests merged in 2019-10, with the labels that each got.

#380 Centos 8 image release recently broke the Dockerfile, need to use cen…
  tools/openshift-ci/Dockerfile.centos
Labels: approved, size/XS

#373 Fix OCP-14382
  features/storage/quota.feature
Labels: approved, lgtm, size/XS

#375 [Time debt (1)] Fix some unmaintained scheduler cases now that transf…
  features/step_definitions/node.rb
Labels: approved, lgtm, size/XS

#374 Fix OCP-16485
  features/storage/regression.feature
Labels: approved, lgtm, size/XS

#368 Update case OCP-13847 OCP-18535 OCP-14986 OCP-10817
  features/networking/pod.feature
  features/networking/sdn.feature
Labels: approved, lgtm, size/M

#381 fix for OCP-20932
  lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
Labels: approved, lgtm, size/L

#379 add new functions for logging
  features/step_definitions/logging.rb
  lib/openshift/cluster_logging.rb
  lib/openshift/elasticsearch.rb
Labels: approved, lgtm, size/M

#382 Auto OCP-21814
  features/networking/service.feature
Labels: approved, lgtm, size/S

#394 cli rules for oc 4.3
  lib/rules/cli/4.3.yaml
Labels: size/XS

#378 Add rules for OCP-24415
  lib/rules/web/admin_console/4.2/storage.xyaml
Labels: approved, lgtm, size/M

#386 auto case OCP-25364
  features/logging/4.x/permission.feature
Labels: approved, lgtm, size/M

#397 limit jira api version
  Gemfile
Labels: approved, lgtm, size/XS

#398 revert change that does not fix problem
  Gemfile
Labels: approved, lgtm, size/XS

#399 update to ruby26 for gem compatibility reasons
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: size/S

#401 update ruby and git in jenkins images
  tools/jenkins/slaves/Dockerfile.centos
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved, cherry-pick-approved, lgtm, size/S

#400 update centos image to use new ruby and git
  tools/jenkins/slaves/Dockerfile.centos
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#388 add step for delete the specifid ovs pod
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/S

#391 Fix OCP-11539
  features/cli/job.feature
Labels: approved, lgtm, size/S

#384 add rule for OCP-21250
  lib/rules/web/admin_console/4.1/catalog.xyaml
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.2/catalog.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
Labels: approved, lgtm, size/M

#390 Add rules for ocp-23880
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/imagestream.xyaml
Labels: approved, lgtm, size/M

#369 Add rule for OCP-21461
  lib/rules/web/admin_console/4.1/check_links.xyaml
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/check_links.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
Labels: approved, lgtm, size/M

#371 Automated tests for machine-api
  features/machine/machine.feature
  features/step_definitions/machine.rb
  features/step_definitions/machine_set.rb
  lib/openshift/machine.rb
  lib/openshift/machine_set.rb
  lib/openshift/node.rb
Labels: approved, lgtm, size/L

#406 Use sample test case ID to not interfere with other tools
  tools/case_id_splitter.rb
Labels: approved, lgtm, size/XS

#405 Update OCP-10466 so it cross platforms
  features/cli/policy.feature
Labels: approved, lgtm, size/S

#395 add new steps to get `opsrc` name
  features/step_definitions/logging.rb
Labels: size/M

#402 auto ocp21333
  features/logging/4.x/cluster_logging_operator.feature
Labels: approved, size/M

#385 auto case OCP-25599
  features/logging/4.x/kibana.feature
  features/step_definitions/logging_metrics.rb
  lib/rules/web/images/logging/logging.xyaml
Labels: approved, size/L

#407 [Blocker] Replace obsoleted oadm_manage_node with oadm_cordon/uncordon_node
  features/admin/pod.feature
  features/step_definitions/node.rb
  lib/rules/cli/4.0.yaml
Labels: approved, lgtm, size/M

#409 remove outdated scenarios
  features/logging/elasticsearch.feature
  features/logging/fluentd.feature
  features/logging/install_uninstall.feature
  features/logging/permission.feature
Labels: approved, lgtm, size/L

#410 Added cluster 'proxy' functions
  lib/openshift/proxy_config_openshift_io.rb
Labels: approved, lgtm, size/S

#392 rules for OCP-23044
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.1/node.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.2/node.xyaml
Labels: size/L

#403 add rules for ocp-23580
  lib/rules/web/admin_console/4.2/route.xyaml
Labels: approved, lgtm, size/S

#415 change default IDP to the last one
  lib/rules/web/console/base/login.xyaml
Labels: approved, lgtm, size/XS

#372 auto logging cases
  features/logging/4.x/cluster_logging_operator.feature
  features/logging/cluster_logging_operator.feature
  features/logging/collector.feature
  features/logging/elasticsearch.feature
  features/logging/elasticsearch_operator.feature
  features/logging/kibana.feature
  features/step_definitions/storage_class.rb
  features/support/clusterlogging_env.rb
  lib/openshift/cluster_logging.rb
  lib/openshift/elasticsearch.rb
  lib/openshift/service_monitor.rb
Labels: approved, lgtm, size/L

#413 Replace manually registered clean-up with unified clean-up
  features/admin/pod.feature
Labels: approved, lgtm, size/S

#414 deploy EO firstly due to bz1752073
  features/step_definitions/logging.rb
Labels: approved, lgtm, size/M

#412 use OCDebugAccessibleHost in OCP v4.x
  config/config.yaml
  lib/environment.rb
  lib/host.rb
  lib/openshift/node.rb
  lib/openshift/project.rb
Labels: approved, lgtm, size/L

#408 python-dnf doesn't exist in Fedora 30
  tools/os_deps/deps.dnf.fedora
Labels: approved, lgtm, size/XS

#393 auto case OCP-25365 OCP-18147
  features/logging/collector.feature
  features/step_definitions/logging_metrics.rb
Labels: size/M

#417 Fix script to more strong
  features/build/dockerbuild.feature
  features/build/stibuild.feature
Labels: size/M

#421 Update fsType scenarios
  features/storage/fsType.feature
Labels: approved, lgtm, size/M

#411 update rule for OCP-24016
  lib/rules/web/admin_console/4.1/check_links.xyaml
  lib/rules/web/admin_console/4.2/check_links.xyaml
Labels: approved, lgtm, size/XS

#423 Automated and OCP-25652
  features/machine/machine.feature
Labels: approved, lgtm, size/S

#426 add rules for operator subscription
  features/test/webconsole.feature
  lib/rules/web/admin_console/4.2/catalog.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
Labels: approved, lgtm, size/M

#429 use chroot by default + some fixes
  lib/environment.rb
  lib/host.rb
Labels: approved, lgtm, size/S

#419 Add parameter for new-app cmd
  features/step_definitions/registry.rb
  lib/rules/cli/4.0.yaml
Labels: size/XS
