Repository openshift/verification-tests, pull requests merged in 2020-08, with the labels that each got.

#1409 Fix gecokdriver download url
  tools/openshift-ci/Dockerfile.centos
Labels: approved, lgtm

#1267 auto some ptp cases
  features/networking/ptp_operator.feature
  features/step_definitions/networking.rb
  testdata/networking/ptp/namespace/43/ns43.yaml
  testdata/networking/ptp/namespace/45/ns45.yaml
  testdata/networking/ptp/og/og.yaml
  testdata/networking/ptp/ptp_master.yaml
  testdata/networking/ptp/ptp_slave.yaml
  testdata/networking/ptp/subscription/sub.yaml
Labels: approved, lgtm

#1410 Fix geckodriver download url for cucushift-public
  tools/jenkins/slaves/Dockerfile.centos
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved, lgtm

#1414 Add step to test persistent
  features/storage/dynamic_provisioning.feature
Labels: approved, lgtm

#1415 Delete CSC creation on OCP 4.5+
  features/step_definitions/operators.rb
  features/upgrade/marketplace/upgrade.feature
Labels: lgtm

#1413 fix web cases
  lib/rules/web/admin_console/4.6/check_links.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/node.xyaml
  lib/rules/web/admin_console/4.6/pods.xyaml
  lib/rules/web/admin_console/4.6/secrets.xyaml
Labels: approved, lgtm

#1422 xt_u32 test coverage for SDN
  features/networking/pod.feature
  testdata/networking/centos_latest_admin.yaml
Labels: approved, lgtm

#1416 Bug fix for the new changes in the latest oc version
  features/cli/oc_volume.feature
  features/step_definitions/pv.rb
  features/step_definitions/storage_class.rb
Labels: approved, lgtm

#1420 Bug fix for azure connection and get disk by name
  lib/iaas/iaas.rb
  lib/launchers/azure.rb
Labels: approved, lgtm

#1424 Add tear down
  features/upgrade/machines/machines.feature
Labels: approved, lgtm

#1423 Upgrade the apiVersion of PodSecurityPolicySelfSubjectReview
  testdata/authorization/scc/tc538262/PodSecurityPolicySubjectReview_privileged_false.json
  testdata/authorization/scc/tc538262/PodSecurityPolicySubjectReview_privileged_true.json
Labels: approved, lgtm

#1417 mhc validation before sending data to server to create mhc resource
  features/machine/machine_healthcheck.feature
Labels: approved, lgtm

#1421 fix for web cases
  features/upgrade/web/console-upgrade.feature
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
Labels: approved, lgtm

#1418 Update ruby to 2.5 when using ruby-ex repo to build
  features/cli/oc_import_image.feature
  features/registry/is.feature
  features/registry/remote.feature
Labels: approved, lgtm

#1399 auto for OCP-33209
  features/upgrade/workloads/oc-upgrade.feature
Labels: approved, lgtm

#1426 Fix rules due to OCM UI upgrading and finish some rules of OCM for new cases
  lib/rules/web/ocm_console/archived_cluster_detail.xyaml
  lib/rules/web/ocm_console/archived_clusters.xyaml
  lib/rules/web/ocm_console/browser_opts.yml
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_detail_access_control_tab.xyaml
  lib/rules/web/ocm_console/cluster_detail_addons_tab.xyaml
  lib/rules/web/ocm_console/cluster_detail_logs_tab.xyaml
  lib/rules/web/ocm_console/cluster_detail_monitoring_tab.xyaml
  lib/rules/web/ocm_console/cluster_detail_networking_tab.xyaml
  lib/rules/web/ocm_console/cluster_detail_overview_tab.xyaml
  lib/rules/web/ocm_console/cluster_idp.xyaml
  lib/rules/web/ocm_console/cluster_list_page.xyaml
  lib/rules/web/ocm_console/creation_cards_page.xyaml
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
  lib/rules/web/ocm_console/dropdown_items.xyaml
  lib/rules/web/ocm_console/install_page.xyaml
  lib/rules/web/ocm_console/login.xyaml
  lib/rules/web/ocm_console/ocm_workflow.xyaml
  lib/rules/web/ocm_console/osd_creation_page.xyaml
  lib/rules/web/ocm_console/subscription_page.xyaml
Labels: approved, lgtm

#1412 update 3 test cases according new features and fix all UI test failures
  lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.2/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.3/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.5/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.6/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.6/monitoring_metrics.xyaml
Labels: approved, lgtm

#1425 fix for 4.6 web cases
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/node.xyaml
  lib/rules/web/admin_console/4.6/pods.xyaml
Labels: approved, lgtm

#1419 [OCPQE-1641] Placeholder directory for essential Dockerfiles
  testdata/routing/images/caddy-docker/Caddyfile
  testdata/routing/images/caddy-docker/Dockerfile
  testdata/routing/images/caddy-docker/certs/example_wildcard.key
  testdata/routing/images/caddy-docker/certs/example_wildcard_chain.pem
  testdata/routing/images/caddy-docker/public/index.html
  testdata/routing/images/caddy-docker/public/path/index.html
  testdata/routing/images/caddy-docker/public/path/second/index.html
  testdata/routing/images/caddy-docker/public/test/index.html
  testdata/routing/images/caddy-docker/publics/index.html
  testdata/routing/images/caddy-docker/publics/path/index.html
  testdata/routing/images/caddy-docker/publics/path/second/index.html
  testdata/routing/images/caddy-docker/publics/test/index.html
  testdata/routing/images/rsyslogd-docker/Dockerfile
  testdata/routing/images/rsyslogd-docker/rsyslog.conf
Labels: approved, lgtm

#1427 Fix ip route show default parsing
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1388 Default values for Different IaaS - aws/azure/gcp/
  features/machine/machine.feature
  lib/openshift/infrastructure.rb
  lib/openshift/machine.rb
  testdata/cloud/ms-aws/ms_default_values.yaml
  testdata/cloud/ms-azure/ms_default_values.yaml
  testdata/cloud/ms-gcp/ms_default_values.yaml
Labels: approved, lgtm

#1428 automated 2 new test cases
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1432 Fix OCP-11882
  features/cli/resources.feature
Labels: approved, lgtm

#1429 some fixes
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/base/login.xyaml
Labels: approved, lgtm

#1435 Allow operations without teardown to support upgrade
  features/step_definitions/scc.rb
Labels: approved, lgtm

#1360 Auotmate OCP-28757
  features/networking/sctp.feature
  features/step_definitions/networking.rb
  testdata/networking/sctp/load-sctp-module.yaml
  testdata/networking/sctp/sctpclient.yaml
  testdata/networking/sctp/sctpserver.yaml
  testdata/networking/sctp/sctpservice.yaml
Labels: approved, lgtm

#1434 Fix OCP-23501
  features/upgrade/storage/upgrade.feature
Labels: approved, lgtm

#1438 fix upgrade failure for metric name change
  features/upgrade/monitoring/monitoring-upgrade.feature
Labels: approved, lgtm

#1431 update ocp-28630
  features/upgrade/storage/upgrade.feature
Labels: approved, lgtm

#1439 Hongyli fix upgrade failure
  features/upgrade/monitoring/monitoring-upgrade.feature
Labels: approved, lgtm

#1436 add pod method "reviseVersion"
  lib/openshift/pod.rb
Labels: approved, lgtm

#1442 fix OCP-11580 test failure
  features/cli/build.feature
Labels: approved, lgtm

#1440 fix rules
  lib/rules/web/admin_console/4.6/style.xyaml
Labels: approved, lgtm

#1441 fix OCP-11887
  features/cli/projects.feature
Labels: approved, lgtm

#1444 No teardown should apply to upgrade-prepare only
  features/step_definitions/scc.rb
  lib/world.rb
Labels: approved, lgtm

#1433 add rules for new checkpoint in OCP-27495
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
Labels: approved, lgtm

#1443 fix web case
  lib/rules/web/admin_console/4.3/external_page.xyaml
  lib/rules/web/admin_console/4.3/projects.xyaml
Labels: approved, lgtm

#1445 Add 4.6 checkpoint rules for OCP-25762
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
Labels: approved, lgtm

#1446 pod label changed to 'deployment' from 'deploymentconfig'
  features/cli/pod.feature
Labels: approved, lgtm

#1454 Fix upgrade-prepare without teardown
  features/step_definitions/scc.rb
  features/test/scc.feature
Labels: approved, lgtm

#1430 Automate OCP-33579
  features/networking/multus.feature
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/whereabouts-overlapping.yaml
Labels: approved, lgtm

#1450 some fix and new rules
  lib/rules/web/admin_console/4.3/customizations.xyaml
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.6/dashboards.xyaml
  lib/rules/web/admin_console/4.6/node.xyaml
  lib/rules/web/admin_console/base/login.xyaml
Labels: approved, lgtm

#592 OCP-11286 iptables rules test updated for 4.x
  features/networking/sdn.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/L

#1246 resource existance output has changed for 4.5
  lib/openshift/resource.rb
Labels: CoreAutomation, approved, lgtm, tide/merge-method-squash

#1459 OCP-33040
  features/machine/machine.feature
  features/step_definitions/machine_set.rb
Labels: approved, lgtm

#1458 fix test failures for product change
  lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.6/monitoring_alerts.xyaml
Labels: approved, lgtm

#1460 Properly wait for mcp to roll out
  features/node/seccomp.feature
Labels: approved, lgtm

#1457 some rule fixes
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
Labels: approved, lgtm

#1453 add rule for OCP-33125
  lib/rules/web/admin_console/4.6/clustersettings.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
Labels: lgtm

#1455 Improved cases 33714, added 34095 to have timeout validations
  features/machine/machine_healthcheck.feature
  testdata/cloud/mhc/mhc_validations.yaml
Labels: approved, lgtm

#1464 some fix and new rules
  lib/rules/web/admin_console/4.3/customizations.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.6/dashboards.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
Labels: approved, lgtm

#1466 update for OCP-11769
  features/cli/deploy.feature
Labels: approved, lgtm

#1471 Add automation for OCP-33722 OCP-33220
  features/build/metrics.feature
Labels: approved, lgtm

#1472 add oc adm must-gather -- /usr/bin/gather_network_ovn_trace support
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1470 Fix error when creating STDIN: namespaces aos-qe-ci not found.
  features/admin/scc.feature
Labels: approved, lgtm

#1474 Increase wait time
  features/node/seccomp.feature
Labels: approved, lgtm

#1469 fix issue: fluentd is not ready
  features/logging/elasticsearch.feature
  features/step_definitions/logging.rb
  lib/openshift/cluster_logging.rb
Labels: approved, lgtm

#1473 Quick fix for conntrack usecase
  features/networking/pod.feature
Labels: approved, lgtm

#1448 Add tag check for upgrade-prepare/check
  lib/world.rb
Labels: approved, lgtm

#1461 Prometheus automation for SDN
  features/networking/metrics.feature
Labels: approved, lgtm

#1475 Fix undefined step in OCP-11877
  features/cli/deploy.feature
Labels: approved, lgtm

#1462 Auto-SCTP
  features/networking/sctp.feature
  testdata/networking/sctp/allow_sctpclient.yaml
  testdata/networking/sctp/default-deny.yaml
Labels: approved, lgtm

#1447 reviewers guide
  doc/reviewer_guide.adoc
  lib/openshift/prometheus.rb
  lib/openshift/resource.rb
Labels: approved

#1452 change resource check to rb file method
  lib/openshift/prometheus.rb
  lib/openshift/thanos_ruler.rb
  lib/openshift/validating_webhook_configuration.rb
Labels: approved, lgtm
