Repository openshift/verification-tests, pull requests merged in 2020-02, with the labels that each got.

#664 Cloud cop 2
  tools/cloud_cop.rb
  tools/instance_summary.rb
  tools/jenkins.rb
Labels: approved, size/S, tools

#669 make sure vendor gem dir not committed
  .gitignore
Labels: approved, size/XS

#663 Fix OCP-21489
  features/networking/multus.feature
Labels: approved, lgtm, size/S

#668 fix failing
  features/registry/is.feature
Labels: approved, lgtm, size/M

#672 remove redundant machines steps
  features/step_definitions/cluster_configuration/cluster_config.rb
  features/step_definitions/machine.rb
  features/step_definitions/machine_set.rb
Labels: approved, lgtm, size/S

#665 Update log in rules
  lib/rules/web/console/base/login.xyaml
Labels: approved, lgtm, size/XS

#671 Add options for 'oc adm node-logs' command
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/XS

#637 add volumes to PodReplicator
  lib/openshift/flakes/pod_volume_spec.rb
  lib/openshift/pod_replicator.rb
Labels: approved, size/S

#675 OLM upgrade tests
  features/step_definitions/local_storage.rb
  features/step_definitions/operator.rb
  features/step_definitions/operators.rb
  features/step_definitions/upgrade/etcd.rb
  features/upgrade/olm/upgrade.feature
  lib/openshift/etcd_cluster.rb
Labels: size/L

#673 Split minor version from "-"
  lib/cli_executor.rb
Labels: approved, lgtm, size/XS

#674 autoscaling step is broken due to PR#672
  features/cluster_configuration/autoscaling.feature
  features/step_definitions/cluster_configuration/cluster_config.rb
Labels: CoreAutomation, approved, lgtm, size/XS

#627 Add the OCP-15603 ocp-15605
  features/svc-catalog_asb/svc-catalog.feature
Labels: approved, lgtm, size/L

#676 Remove oc version check for 3.y
  lib/cli_executor.rb
Labels: approved, lgtm, size/S

#682 Using curl instead of ping
  features/networking/egress-ingress.feature
Labels: approved, lgtm, size/M

#683 fix client proxy setting
  lib/environment.rb
Labels: approved, lgtm, size/XS

#679 update project Details tab page url for 4.4
  lib/rules/web/admin_console/4.4/goto.xyaml
Labels: approved, lgtm, size/XS

#678 add curation_schedule method
  lib/openshift/cluster_logging.rb
  lib/openshift/elasticsearch.rb
Labels: approved, lgtm, size/M

#667 Rewrite OCP-9572 to be non-destructive
  features/storage/nfs.feature
Labels: approved, lgtm, size/S

#670 Simplify steps to query prometheus
  features/machine/alerting.feature
  features/step_definitions/prometheus.rb
Labels: approved, lgtm, size/M

#684 Ensure machines and nodes are restored after scenario
  features/machine/machine.feature
Labels: lgtm, size/XS

#689 fix rules for idp selection
  lib/rules/web/console/base/login.xyaml
Labels: approved, lgtm, size/XS

#688 Run OCP-9565 in network-policy by default
  features/networking/isolation.feature
Labels: approved, lgtm, size/XS

#693 Fix OCP-21461/OCP-21034
  lib/rules/web/admin_console/4.1/storage.xyaml
  lib/rules/web/admin_console/4.2/storage.xyaml
  lib/rules/web/admin_console/4.3/storage.xyaml
  lib/rules/web/admin_console/4.4/check_links.xyaml
  lib/rules/web/admin_console/4.4/storage.xyaml
Labels: approved, lgtm, size/S

#690 add rules for oc comands
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/XS

#691 4.4 rule fixes
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/deployment.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/deployment.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/deployment.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/deployment.xyaml
  lib/rules/web/admin_console/4.4/overview.xyaml
Labels: approved, lgtm, size/M

#698 Fix case_id
  features/images/jenkins.feature
  features/logging/collector.feature
  features/logging/elasticsearch.feature
  features/test/storage.feature
Labels: approved, lgtm, size/XS

#696 add one step to make sure all nodes are changed to ready
  features/networking/operator.feature
Labels: approved, lgtm, size/XS

#699 modify autocase OCP-10931
  features/cli/hpa.feature
Labels: approved, lgtm, size/XS

#680 Update to run cucushift on oc 4.4 using --kubeconfig instead of --config
  lib/cli_executor.rb
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/XS

#697 fix click_specified_idp
  lib/rules/web/admin_console/base/login.xyaml
Labels: approved, lgtm, size/XS

#704 update 'open ocm portal' step and 'login' rule
  config/config.yaml
  features/step_definitions/ocm/ocm.rb
  lib/rules/web/ocm_console/login.xyaml
Labels: size/S

#703 [Blocker] Switch to --kubeconfig only in 4.4 as some cmd in 4.3 does not support it.
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm, size/XXL

#707 annotations access for image stream tag specification
  lib/openshift/flakes/image_stream_tag_spec.rb
Labels: approved, lgtm, size/XS

#712 update the match strings to avoid case-sensitive
  features/routing/route.feature
Labels: approved, lgtm, size/S

#711 Replace old secret cmds
  features/build/buildconfig.feature
  features/build/buildlogic.feature
  features/cli/secrets.feature
  features/step_definitions/helper_services.rb
Labels: approved, lgtm, size/M

#713 Ensure machine/node consistency after scenario
  features/machine/machine.feature
  features/step_definitions/machine_set.rb
  lib/openshift/machine.rb
Labels: approved, lgtm, size/M

#685 Verify machine-api components are functional after upgrade
  features/upgrade/machines/machines.feature
Labels: approved, lgtm, size/M

#701 Automate OCP-27655
  features/networking/sdn.feature
Labels: approved, lgtm, size/M

#700 add a rule to make sure kebab actions list open before next click
  lib/rules/web/admin_console/4.3/actions.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/actions.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
Labels: approved, lgtm, size/S

#692 logging alert rules testing
  features/logging/cluster_logging_operator.feature
  features/logging/elasticsearch_operator.feature
  features/step_definitions/logging.rb
  features/step_definitions/logging_metrics.rb
  lib/openshift/flakes/prometheus_rule_group_rule_spec.rb
  lib/openshift/flakes/prometheus_rule_group_spec.rb
  lib/openshift/flakes/service_monitor_endpoint_spec.rb
  lib/openshift/prometheus_rule.rb
  lib/openshift/service_monitor.rb
Labels: approved, lgtm, size/L

#721 allow running flexy installer in a container easier
  tools/openshift-ci/Dockerfile.installer-example
  tools/openshift-ci/verification_tests_install_entrypoint.sh
Labels: approved, lgtm, size/M

#706 annotations access for image stream tag specification
  lib/openshift/flakes/image_stream_tag_spec.rb
Labels: approved, lgtm, size/XS

#722 allow terminating clusters and fix file owner
  tools/jenkins/slaves/Dockerfile.centos
  tools/jenkins/slaves/Dockerfile.rhel7
  tools/jenkins/slaves/Dockerfile.rhel8
  tools/openshift-ci/verification_tests_install_entrypoint.sh
Labels: size/S

#720 update OCP-18482 and OCP-9650
  features/routing/rate-limit.feature
  features/routing/route.feature
Labels: approved, lgtm, size/M

#729 container installer improvements
  tools/launch_instance.rb
  tools/openshift-ci/Dockerfile.installer-example
  tools/openshift-ci/verification_tests_install_entrypoint.sh
Labels: approved, lgtm, size/L, tide/merge-method-merge

#717 Auto OCP-25608
  features/machine/machine.feature
  lib/openshift/machine.rb
Labels: approved, lgtm, size/M

#633 Fix OCP-10745
  features/build/buildlogic.feature
Labels: approved, lgtm, size/XS

#725 helper method to get loadBalancer ingress
  lib/openshift/service.rb
Labels: CoreAutomation, approved, lgtm, size/XS

#732 fix kebab list item issue
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/actions.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/user_management.xyaml
  lib/rules/web/admin_console/4.3/users.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/user_management.xyaml
  lib/rules/web/admin_console/4.4/users.xyaml
Labels: approved, lgtm, size/M

#736 rules added for OCP-26984
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/monitoring.xyaml
  lib/rules/web/admin_console/4.4/projects.xyaml
Labels: approved, lgtm, size/M

#737 Fix OCP-9638
  features/storage/iscsi.feature
Labels: approved, lgtm, size/S

#724 add the check of clusterservicebroker before the testcases
  features/svc-catalog_asb/svc-catalog.feature
Labels: approved, lgtm, size/S

#735 update AB routing cases
  features/routing/abrouting.feature
Labels: approved, lgtm, size/L

#710 fix OCP-19532
  lib/rules/web/admin_console/4.3/filters.xyaml
  lib/rules/web/admin_console/4.4/filters.xyaml
Labels: approved, lgtm, size/M

#733 add tolerations method
  lib/openshift/cron_job.rb
  lib/openshift/pod_replicator.rb
Labels: approved, lgtm, size/S

#744 Fix chrome login issue
  lib/webauto/web4cucumber.rb
Labels: approved, lgtm, size/XS

#716 Fix OCP-10944
  features/cli/build.feature
Labels: approved, lgtm, size/S

#738 Since "oc secret new" is deprecated,we have to change it to "oc create secret".
  features/cli/oc_secrets.feature
Labels: approved, lgtm, size/S
