Repository openshift/verification-tests, pull requests merged in 2020-09, with the labels that each got.

#1480 fix image issue - OCP-14799
  testdata/infrastructure/cluster-capacity/cluster-capacity-pod.yaml
Labels: approved, lgtm

#1485 fix deduplication of more than 256 messages where UTF is used
  lib/log.rb
Labels: approved, lgtm

#1489 remove checking status in clusterlogging
  features/step_definitions/logging.rb
Labels: approved, lgtm

#1486 fix deduplication of more than 256 messages where UTF is used
  lib/log.rb
Labels: approved, lgtm

#1490 add rules for OCP-32151
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
Labels: approved, lgtm

#1487 more debug info on taint restore error
  features/step_definitions/node.rb
Labels: approved, lgtm

#1238 NB DB scenarios
  features/networking/ovn.feature
  features/step_definitions/pod.rb
Labels: approved, lgtm

#1476 rules fixed for OCP-27586
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.6/dashboards.xyaml
Labels: approved, lgtm

#1365 Some manual cases automation
  features/networking/multus.feature
  features/networking/operator.feature
  features/networking/service.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1482 Auto ocp-33770 ocp-25598
  features/build/metrics.feature
Labels: approved, lgtm

#1467 Updated OCP-24070
  lib/rules/web/ocm_console/install_page.xyaml
Labels: approved, lgtm

#1484 fix web rules
  lib/rules/web/admin_console/4.3/customizations.xyaml
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/4.6/dashboards.xyaml
Labels: approved, lgtm

#1307 IPAM thrash test for SDN-892 and a test file
  features/networking/ovn.feature
  testdata/networking/generic_test_pod_with_replica.yaml
Labels: approved, lgtm

#1483 Hongyli new case aug17 veri
  lib/openshift/flakes/container_spec.rb
  lib/openshift/prometheus.rb
  lib/openshift/thanos_ruler.rb
Labels: approved, lgtm

#1498 Delete new format oauth token
  lib/api_accessor.rb
Labels: approved, lgtm

#1493 Bugfix for making nfs pv is valid for ipv4 and ipv6
  features/storage/nfs.feature
  lib/openshift/service.rb
Labels: approved, lgtm

#1495 rules updated
  lib/rules/web/admin_console/4.4/check_links.xyaml
  lib/rules/web/admin_console/4.5/check_links.xyaml
  lib/rules/web/admin_console/4.6/check_links.xyaml
Labels: approved, lgtm

#1491 more debug info on taint restore error (#1487)
  features/step_definitions/node.rb
Labels: approved, lgtm

#1252 SDN-655 SystemOVS: update tests to use system OVS
  features/networking/sdn.feature
  features/step_definitions/networking.rb
  lib/openshift/network_operator.rb
  lib/platform/systemd_service.rb
Labels: approved, lgtm

#1497 add rules for OCP-33543
  lib/rules/web/admin_console/base/login.xyaml
Labels: approved, lgtm

#1496 Add config file for cco feature
  testdata/cloud-credential/cr-namespace-no-exist.yaml
  testdata/cloud-credential/cr.yaml
Labels: approved, lgtm

#1385 Fix case OCP-16443
  features/cli/deploy.feature
Labels: approved, lgtm

#1502 fix close tour on dev console
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
Labels: approved, lgtm

#1494 fix skip tour issue
  lib/rules/web/admin_console/4.6/check_links.xyaml
Labels: approved, lgtm

#1504 Fix install page case
  lib/rules/web/ocm_console/install_page.xyaml
Labels: approved, lgtm

#1500 add step to get all reports
  features/step_definitions/metering.rb
  lib/openshift/report.rb
Labels: approved, lgtm

#1506 Fix indention
  features/step_definitions/rc.rb
Labels: approved, lgtm

#1507 Prometheus cases needs to point to sdn ep name across all releases now
  features/networking/metrics.feature
Labels: approved, lgtm

#1510 No operatorsource from 4.6
  features/step_definitions/operators.rb
  features/upgrade/marketplace/upgrade.feature
Labels: lgtm

#1343 auto case OCP-32197
  features/logging/collector.feature
Labels: approved, lgtm

#1508 fix OCP-27646 for operators
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
Labels: approved, lgtm

#1509 fix OCP-10941
  features/cli/oc_idle.feature
  testdata/rc/idling-echo-server.yaml
Labels: approved, lgtm

#1516 use only character oriented methods with StringScanner
  lib/log.rb
Labels: approved, lgtm

#1515 complete fix for log deduplication
  lib/log.rb
Labels: approved, lgtm

#1517 Fix namespaces aos-qe-ci not found
  features/networking/sctp.feature
Labels: approved, lgtm

#1518 Update OCP-25917
  features/networking/multus.feature
Labels: approved, lgtm

#1513 Update oc downloads and license link OCP-25802
  lib/rules/web/admin_console/4.3/check_links.xyaml
  lib/rules/web/admin_console/4.4/check_links.xyaml
  lib/rules/web/admin_console/4.5/check_links.xyaml
  lib/rules/web/admin_console/4.6/check_links.xyaml
Labels: approved, lgtm

#1524 fix oc logs for SDN, add --all-containers and --prefix options
  features/step_definitions/networking.rb
  lib/rules/cli/4.4.yaml
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1520 fix OCP-23044
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/node.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  testdata/olm/catalogsource-template.yaml
Labels: approved, lgtm

#1503 Add lib to restore descheduler CR
  features/step_definitions/descheduler.rb
Labels: approved, lgtm

#1526 allow metering to be installed into other namespace other than the de…
  features/step_definitions/metering.rb
  testdata/metering/configs/metering_operatorgroup.yaml
  testdata/metering/configs/metering_subscription.yaml
  testdata/metering/configs/meteringconfig_hdfs.yaml
  testdata/metering/configs/meteringconfig_sharedPVC.yaml
  testdata/metering/configs/pv_metering.yaml
Labels: approved, lgtm

#1512 add resource define
  lib/openshift/etcd_cluster.rb
  lib/openshift/kiali.rb
  lib/openshift/pgcluster.rb
Labels: approved, lgtm

#1525 OCP-11286: change iptables flush to be more atomic
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1519 auto OCP-33743
  features/step_definitions/catalog_source.rb
  lib/openshift/catalog_source.rb
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
Labels: approved, lgtm

#767 New OVN tests
  features/networking/ovn.feature
  features/step_definitions/networking.rb
  features/step_definitions/node.rb
  testdata/networking/egress-ingress/qos/iperf-rc.json
  testdata/networking/egress-ingress/qos/iperf-server.json
  testdata/networking/iperf_nodeport_service.json
Labels: approved, lgtm, size/L

#1529 new ui test cases
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/monitoring_metrics.xyaml
Labels: approved, lgtm

#1505 add type for credentialsrequest
  lib/openshift/credential_request.rb
Labels: approved, lgtm

#1449 Update some egressnetworkpolicy case to be compatiable with OVN
  features/networking/egress-ingress.feature
  features/step_definitions/networking.rb
  testdata/networking/ovn-egressfirewall/limit_policy.json
Labels: approved, lgtm

#1527 leader election log message validation
  features/machine/machine.feature
Labels: approved, lgtm

#1501 auto cases OCP-33850 OCP-33848
  features/networking/pod.feature
  features/networking/service.feature
Labels: approved, lgtm

#1532 Use proper pod/pods
  features/build/metrics.feature
  features/build/stibuild.feature
  features/cli/build.feature
  features/cli/create.feature
  features/machine/autoscaler.feature
  features/machine/machine.feature
  features/networking/egress-ingress.feature
  features/networking/service.feature
  features/step_definitions/pod.rb
  features/step_definitions/registry.rb
  features/upgrade/machines/machines.feature
  features/upgrade/node/hpa/upgrade.feature
Labels: approved, lgtm

#1528 Auto case OCP-22665
  features/upgrade/etcd/upgrade.feature
Labels: approved, lgtm

#1534 change image to sha256 format for disconnected cluster testing
  testdata/cloud/autoscaler-auto-tmpl.yml
  testdata/cloud/mhc/kubelet-killer-pod-43.yml
  testdata/cloud/mhc/kubelet-killer-pod.yml
Labels: approved, lgtm

#1451 Auto scheduler upgrade case
  features/upgrade/workloads/scheduler-upgrade.feature
  testdata/scheduler/policy_upgrade.json
Labels: approved, lgtm

#1521 Add WA for OCP-28630
  features/upgrade/storage/upgrade.feature
Labels: approved, lgtm

#1514 auto OCP-34718
  features/machine/machine.feature
  lib/openshift/node.rb
  testdata/cloud/pod-34718.yml
  testdata/cloud/pvc-34718.yml
Labels: approved, lgtm

#1535 fix web cases
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.6/dashboards.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/overview.xyaml
  lib/rules/web/admin_console/4.6/status.xyaml
Labels: approved, lgtm

#1522 OCP-25832 - [web console] Check upgrade channels automate the test case.
  lib/rules/web/admin_console/4.4/clustersettings.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.5/clustersettings.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.6/clustersettings.xyaml
Labels: approved, lgtm

#1499 auto some egressfirewall cases
  features/networking/egress-ingress.feature
  testdata/networking/ovn-egressfirewall/egressfirewall-policy1.yaml
  testdata/networking/ovn-egressfirewall/egressfirewall-policy2.yaml
  testdata/networking/ovn-egressfirewall/egressfirewall-policy3.yaml
Labels: approved, lgtm

#1538 Use proper step
  features/networking/egress-ingress.feature
Labels: approved, lgtm

#1540 Xt_u32 case changes
  features/networking/pod.feature
Labels: approved, lgtm

#1539 rules added for OCP-33568
  lib/rules/web/admin_console/4.6/tables.xyaml
Labels: approved, lgtm

#1408 Auto OCP-18316 OCP-18315 OCP-19785
  features/networking/egress-ip.feature
Labels: approved, lgtm

#1542 Fix exec on sdn pods
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1536 auto OCP-33744
  lib/rules/web/admin_console/4.6/check_links.xyaml
Labels: approved, lgtm

#1545 Fix OCP-11602 in v3.11
  features/cli/oc_set_build_hook.feature
Labels: approved, lgtm

#1541 Hongyli new ui sep13 veri
  lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.6/monitoring_alerts.xyaml
Labels: approved, lgtm

#1548 Fix scripts for v3
  features/cli/build.feature
  features/cli/create.feature
  features/registry/remote.feature
Labels: approved, lgtm

#1549 some rule fixes
  lib/rules/web/admin_console/4.3/check_links.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/customizations.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/overview.xyaml
  lib/rules/web/admin_console/4.3/storage.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/overview.xyaml
  lib/rules/web/admin_console/4.4/storage.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/overview.xyaml
  lib/rules/web/admin_console/4.5/storage.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/overview.xyaml
  lib/rules/web/admin_console/4.6/storage.xyaml
Labels: approved, lgtm

#1551 Fix failed tests for v3.11
  features/build/custombuild.feature
  features/build/dockerbuild.feature
Labels: approved, lgtm

#1547 Bugfix for PV is deleted before PVC
  features/storage/nfs.feature
  features/storage/persistent_volume.feature
Labels: approved, lgtm

#1552 we need to set `-i` when stdin is provided
  lib/openshift/pod.rb
Labels: approved, lgtm

#1553 we need to set `-i` when stdin is provided
  lib/openshift/pod.rb
Labels: approved, lgtm

#1511 Finish some rules for url redirection cases of OCM
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/creation_cards_page.xyaml
  lib/rules/web/ocm_console/osd_creation_page.xyaml
Labels: approved, lgtm

#1555 Fix OCP-11298
  features/cli/oc_set_deployment_hook.feature
Labels: approved, lgtm

#1543 update OCP-27901 and add checkpoints
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/dashboards.xyaml
Labels: approved, lgtm

#1533 host-ovs: add missing network_type and fix pgrep
  features/networking/sdn.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1557 update rules
  features/step_definitions/catalog_source.rb
Labels: approved, lgtm

#1353 Ldap step defination changes
  features/step_definitions/helper_services.rb
  testdata/authorization/init.ldif
Labels: approved, lgtm

#1559 Fix OCP-15461 in v3
  features/build/dockerbuild.feature
Labels: approved, lgtm

#1558 Fix for OCP-20932
  lib/rules/web/admin_console/4.6/overview.xyaml
Labels: approved, lgtm

#1554 fix OCP-10941
  features/cli/oc_idle.feature
Labels: approved, lgtm

#1562 Ensure pvc clean-up, regardless of test step failures
  features/storage/nfs.feature
  features/storage/persistent_volume.feature
Labels: approved, lgtm

#1561 update for OCP-27646
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
Labels: approved, lgtm

#1563 Add image hostpathplugin info
  testdata/storage/csi/csi-hostpath-plugin.yaml
Labels: approved, lgtm

#1560 added gem for jenkins access
  tools/Gemfile
Labels: approved, lgtm

#1565 Update SCTP cases
  features/networking/sctp.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1566 Fix resource type of NetworkAttachmentDefinition
  lib/openshift/network_attachment_definition.rb
Labels: approved, lgtm

#1550 Add rules for 3.11 for OCP-19667 and OCP-19558
  lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
  lib/rules/web/admin_console/3.11/goto.xyaml
Labels: approved, lgtm

#1570 update OCP-12625
  features/web/check_page.feature
Labels: approved, lgtm

#1573 add specify for container
  features/upgrade/workloads/scheduler-upgrade.feature
Labels: approved, lgtm

#1523 OCP-23609 - [web console] User could use keyboard shortcut on project resources page
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/overview.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/overview.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/overview.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/overview.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/overview.xyaml
Labels: approved, lgtm

#1544 Auto OCP-35068
  features/images/jenkins.feature
  lib/rules/web/images/jenkins_2/jenkins_2.xyaml
Labels: approved, lgtm

#1556 add rules for OCP-33748
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
Labels: approved, lgtm

#1568 update syslogserver configurations
  testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_configmap.yaml
Labels: approved, lgtm

#1572 fix web cases
  lib/rules/web/admin_console/4.6/dashboards.xyaml
  lib/rules/web/admin_console/4.6/overview.xyaml
Labels: approved, lgtm

#1564 add rules for OCP-29690
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
Labels: approved, lgtm

#1569 Fix test failure of case OCP-27841 and automate new case OCP-21874
  lib/rules/web/admin_console/4.2/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.3/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.5/monitoring_metrics.xyaml
Labels: approved, lgtm

#1575 Fix the manifest issue
  testdata/storage/secret/secret.yaml
Labels: approved, lgtm

#1574 add automation scenarios to test forward logs with tags
  features/logging/cluster_log_forwarder.feature
  features/step_definitions/logging.rb
  features/step_definitions/logging_metrics.rb
  lib/openshift/cluster_log_forwarder.rb
  testdata/logging/clusterlogforwarder/clf-forward-with-different-tags.yaml
  testdata/logging/clusterlogforwarder/clf-forward-with-same-tag.yaml
Labels: approved, lgtm

#1571 Fix ui automation cases
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/install_page.xyaml
Labels: approved, lgtm

#1577 fix web cases
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.6/dashboards.xyaml
  lib/rules/web/admin_console/base/login.xyaml
Labels: approved, do-not-merge/hold, lgtm

#1576 add lib support for argocds
  lib/openshift/argo_c_d.rb
Labels: approved, lgtm

#1537 Fix failing
  features/build/metrics.feature
  features/registry/registry.feature
  testdata/image/gitserver/gitserver-persistent.yaml
Labels: approved, lgtm

#1477 update for OCP-11326
  testdata/deployment/extensions/deployment.yaml
Labels: approved, lgtm
