Repository openshift/verification-tests, pull requests merged in 2020-07, with the labels that each got.

#1284 add methods for logging resources
  features/step_definitions/logging.rb
  lib/openshift/cluster_logging.rb
  lib/openshift/elasticsearch.rb
Labels: approved, lgtm

#1289 test loop step
  features/test/meta.feature
  features/test/project.feature
Labels: approved, lgtm

#1304 Change the title of the prepare test case
  features/upgrade/api_auth/upgrade.feature
Labels: approved, lgtm

#1260 add rules for kibana
  lib/rules/web/admin_console/4.2/logging_kibana.xyaml
  lib/rules/web/admin_console/4.3/logging_kibana.xyaml
  lib/rules/web/admin_console/4.4/logging_kibana.xyaml
  lib/rules/web/admin_console/4.5/logging_kibana.xyaml
Labels: approved, lgtm

#1299 Auto OCP-29299
  features/networking/sdn.feature
Labels: approved, lgtm

#1298 fix for web cases
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.5/logs.xyaml
  testdata/deployment/dc-with-two-containers.yaml
Labels: approved, lgtm

#1305 fix jira OCPQE-984
  features/step_definitions/metering.rb
Labels: approved, lgtm

#1257 Same case to test both sdn and ovn cluster
  features/networking/multicast.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1288 Automate OCP-31999
  features/networking/multus.feature
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/whereabouts-excludeIP.yaml
Labels: approved, lgtm

#1268 automate case OCP-32002
  features/logging/kibana.feature
  lib/rules/web/admin_console/4.1/logging_kibana.xyaml
  lib/rules/web/admin_console/4.2/logging_kibana.xyaml
  lib/rules/web/admin_console/4.3/logging_kibana.xyaml
  lib/rules/web/admin_console/4.4/logging_kibana.xyaml
  lib/rules/web/admin_console/4.5/logging_kibana.xyaml
Labels: approved, lgtm

#1295 add rule for OCP-26557
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
Labels: approved, lgtm

#1310 Some small fix to adapt the script to the new version
  features/cli/policy.feature
  features/cli/serviceaccount.feature
Labels: approved, lgtm

#1313 OCP-26014 Pod readiness check for OVN, fix case id
  features/networking/pod.feature
Labels: approved, lgtm

#1308 finally fix OCPQE-240 getting GCP credentials
  lib/iaas/iaas.rb
  lib/launchers/gce.rb
Labels: approved, lgtm

#1314 update-OCP-28633
  features/networking/multus.feature
Labels: approved, lgtm

#1315 corner cases fix for metering steps
  features/step_definitions/metering.rb
Labels: CoreAutomation, approved, lgtm

#1321 add oc create deploymentconfig with short -o
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1300 add OCP-19722 rules for 4.5
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/node.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/node.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/node.xyaml
Labels: approved, lgtm

#1316 check ES status first
  features/logging/kibana.feature
  features/step_definitions/logging.rb
  features/step_definitions/logging_metrics.rb
  lib/rules/web/admin_console/4.1/logging_kibana.xyaml
  lib/rules/web/admin_console/4.2/logging_kibana.xyaml
  lib/rules/web/admin_console/4.3/logging_kibana.xyaml
  lib/rules/web/admin_console/4.4/logging_kibana.xyaml
Labels: approved, lgtm

#1317 update external ES
  testdata/logging/logforwarding/elasticsearch/secure/configmap.yaml
  testdata/logging/logforwarding/elasticsearch/secure/deployment.yaml
Labels: approved, lgtm

#1324 use 'open_uri_redirections' gem instead to handle redirect
  tools/Gemfile
  tools/find_image.rb
Labels: approved, lgtm, tools

#1294 Automated 4 UI test cases and fix 1 test failure
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.2/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.3/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.5/monitoring_metrics.xyaml
Labels: approved, lgtm

#1320 rules updated
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
Labels: approved, lgtm

#1326 Update typo
  features/build/buildlogic.feature
  features/upgrade/samples_operator/upgrade.feature
Labels: approved, lgtm

#1322 Automate OCP-32065
  features/node/seccomp.feature
  testdata/node/machineconfig_nostat.yaml
  testdata/node/pod_nostat.json
Labels: approved, lgtm

#1332 Fix typo
  features/networking/egress-ingress.feature
Labels: approved

#1325 fix uninstall via Operatorhub error due to missing rule for 4.3, also…
  features/step_definitions/metering.rb
  lib/rules/web/admin_console/4.3/actions.xyaml
  lib/rules/web/admin_console/4.3/operator_hub.xyaml
Labels: approved, lgtm

#1334 Fix OCP-11695
  features/cli/deploy.feature
Labels: approved, lgtm

#1327 Fix OCP-11474
  features/build/buildconfig.feature
Labels: approved, lgtm

#1336 fix issue: get empty genUUID
  features/logging/cluster_logging_operator.feature
  features/logging/elasticsearch.feature
Labels: approved, lgtm

#1342 Fix OCP-22958
  features/images/rhel8_images.feature
Labels: approved, lgtm

#1341 fix OCP-28859
  features/machine/machine_healthcheck.feature
Labels: approved, lgtm

#1345 add 4.6 rules
  lib/rules/web/admin_console/4.6/actions.xyaml
  lib/rules/web/admin_console/4.6/browser_opts.yml
  lib/rules/web/admin_console/4.6/builds.xyaml
  lib/rules/web/admin_console/4.6/catalog.xyaml
  lib/rules/web/admin_console/4.6/check_links.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/configmap.xyaml
  lib/rules/web/admin_console/4.6/customizations.xyaml
  lib/rules/web/admin_console/4.6/dashboards.xyaml
  lib/rules/web/admin_console/4.6/deployment.xyaml
  lib/rules/web/admin_console/4.6/environments.xyaml
  lib/rules/web/admin_console/4.6/explore.xyaml
  lib/rules/web/admin_console/4.6/filters.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/idp.xyaml
  lib/rules/web/admin_console/4.6/imagestream.xyaml
  lib/rules/web/admin_console/4.6/logging_kibana.xyaml
  lib/rules/web/admin_console/4.6/logs.xyaml
  lib/rules/web/admin_console/4.6/machine.xyaml
  lib/rules/web/admin_console/4.6/masthead.xyaml
  lib/rules/web/admin_console/4.6/monitoring.xyaml
  lib/rules/web/admin_console/4.6/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.6/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.6/node.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
  lib/rules/web/admin_console/4.6/overview.xyaml
  lib/rules/web/admin_console/4.6/projects.xyaml
  lib/rules/web/admin_console/4.6/quota.xyaml
  lib/rules/web/admin_console/4.6/route.xyaml
  lib/rules/web/admin_console/4.6/search.xyaml
  lib/rules/web/admin_console/4.6/secrets.xyaml
  lib/rules/web/admin_console/4.6/status.xyaml
  lib/rules/web/admin_console/4.6/storage.xyaml
  lib/rules/web/admin_console/4.6/style.xyaml
  lib/rules/web/admin_console/4.6/user_management.xyaml
  lib/rules/web/admin_console/4.6/yaml.xyaml
Labels: approved, lgtm

#1318 add rules for OCP-26868
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/pods.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/pods.xyaml
  testdata/deployment/hello-deployment-1.yaml
Labels: approved, lgtm

#1329 Make OCP-12144 test more robust
  features/cli/oc_delete.feature
Labels: approved, lgtm

#1338 Update metering.rb
  features/step_definitions/metering.rb
Labels: approved, lgtm

#1348 fix web case for 4.6
  lib/rules/web/admin_console/4.6/check_links.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/dashboards.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/style.xyaml
Labels: approved, lgtm

#1347 Add 4.7 CLI support
  lib/rules/cli/4.7.yaml
  lib/rules/cli/kubectl-4.7.yaml
Labels: approved, lgtm

#1337 oc new-app generate deployment(>4.4) and deploymentConfig,this is for Compatible with different version OC
  features/cli/serviceaccount.feature
Labels: approved, lgtm

#1352 Add nodocs to yum install
  tools/install_os_deps.sh
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved, lgtm

#1346 auto OCP-32620
  features/machine/machine.feature
Labels: approved, lgtm

#1207 Fix OCP-31241
  features/cli/oc_set_probe.feature
Labels: approved, lgtm

#1356 update a doc link for 4.4
  lib/rules/web/admin_console/4.4/builds.xyaml
Labels: approved, lgtm

#1306 Update the step to avoid choosing a master node
  features/step_definitions/project.rb
Labels: approved, lgtm

#1350 show systemctl status after restart
  lib/platform/systemd_service.rb
Labels: approved, lgtm

#1351 fix web cases for 4.6
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/overview.xyaml
  lib/rules/web/admin_console/4.6/search.xyaml
Labels: approved, lgtm

#1339 fixes to test result reporting and logging
  features/support/cucu_formatter.rb
  features/support/env.rb
  lib/polarshift/scenario_wrapper.rb
  lib/polarshift/test_case.rb
  lib/polarshift/test_record.rb
  lib/ssh.rb
  lib/test_case_manager.rb
  lib/world.rb
Labels: approved, lgtm, tide/merge-method-merge

#1357 add missing rule for 4.4
  lib/rules/web/admin_console/4.4/goto.xyaml
Labels: approved, lgtm

#1340 (v3) fixes to test result reporting and logging
  features/support/cucu_formatter.rb
  features/support/env.rb
  lib/polarshift/scenario_wrapper.rb
  lib/polarshift/test_case.rb
  lib/polarshift/test_record.rb
  lib/ssh.rb
  lib/test_case_manager.rb
  lib/world.rb
Labels: approved, lgtm, tide/merge-method-merge

#1358 Fix undefined steps which is caused by typo
  features/networking/pod.feature
Labels: approved, lgtm

#1361 fixing server account issue
  testdata/infrastructure/cluster-capacity/cluster-capacity-pod.yaml
Labels: approved, lgtm

#1262 sriov case auto
  features/networking/sriov.feature
  features/step_definitions/sriov.rb
  lib/openshift/sriov_network.rb
  lib/openshift/sriov_network_node_policy.rb
  testdata/networking/sriov/namespace/43/ns.yaml
  testdata/networking/sriov/namespace/45/ns45.yaml
  testdata/networking/sriov/og/og.yaml
  testdata/networking/sriov/pod/sriov-without-resource-static.yaml
  testdata/networking/sriov/pod/sriov-without-resource-static.yaml-deployment
  testdata/networking/sriov/sriovnetwork/static-sriovnetwork.yaml
  testdata/networking/sriov/sriovnetworkpolicy/intel-netdevice.yaml
  testdata/networking/sriov/subscription/sub.yaml
Labels: approved, lgtm

#1366 fix_etcd_cluster_rb
  lib/openshift/etcd_cluster.rb
Labels: approved, lgtm

#1359 fix web case for 4.6
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.6/check_links.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/node.xyaml
  lib/rules/web/admin_console/4.6/pods.xyaml
  lib/rules/web/admin_console/4.6/user_management.xyaml
Labels: approved, lgtm

#1369 Bug fix for oc_new_app_as_dc and OCP-15268
  features/storage/node_operations.feature
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1363 fix ocp-13022
  features/upgrade/node/node-upgrade.feature
Labels: approved, lgtm

#1371 Enable test for disconnected
  features/node/seccomp.feature
  testdata/node/pod_nostat.json
Labels: approved, lgtm

#1311 Auto upgrade tc OCP-28630
  features/upgrade/storage/upgrade.feature
  testdata/storage/csi/csi-hostpath-attacher.yaml
  testdata/storage/csi/csi-hostpath-driverinfo.yaml
  testdata/storage/csi/csi-hostpath-plugin.yaml
  testdata/storage/csi/csi-hostpath-provisioner.yaml
  testdata/storage/csi/csi-hostpath-snapshotter.yaml
  testdata/storage/csi/csi-rbac.yaml
  testdata/storage/csi/csi-storageclass.yaml
  testdata/storage/csi/restorepvc.yaml
  testdata/storage/csi/snapshotclass.yaml
  testdata/storage/csi/volumesnapshot.yaml
Labels: approved, lgtm

#1276 Fix restore steps for scheduler
  features/step_definitions/scheduler.rb
Labels: approved, lgtm

#1375 add quotation marks
  features/step_definitions/sriov.rb
Labels: approved, lgtm

#1372 fix for web case
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.5/node.xyaml
  lib/rules/web/admin_console/4.6/dashboards.xyaml
  lib/rules/web/admin_console/4.6/node.xyaml
Labels: approved, lgtm

#1370 fix failures and new case for 4.6
  lib/rules/web/admin_console/4.6/monitoring_alerts.xyaml
Labels: approved, lgtm

#1367 properly fix fully qualified resource names cache
  lib/iaas/iaas.rb
  lib/world.rb
Labels: approved, lgtm

#1368 properly fix fully qualified resource names cache
  lib/world.rb
Labels: approved, lgtm

#1309 auto some egressIP cases
  features/networking/egress-ip.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1376 Change to use ephemeral template to reduce failure when pvc can't be …
  features/registry/registry.feature
Labels: approved, lgtm

#1378 Add destructive tag
  features/upgrade/samples_operator/upgrade.feature
Labels: approved, lgtm

#1381 avoid race condition while checking delete deps
  lib/openshift/resource.rb
Labels: approved, lgtm

#1382 avoid race condition while checking delete deps
  lib/openshift/resource.rb
Labels: approved, lgtm

#1383 OCP-12194 fix dc creating issue
  features/cli/oc_volume.feature
Labels: approved, lgtm

#1374 Bug fix for OCP-9685
  lib/iaas/iaas.rb
Labels: approved, lgtm

#1386 auto OCP-32126
  features/machine/machine.feature
  features/step_definitions/machine_set.rb
Labels: approved, lgtm

#1384 warn on missing artifacts
  lib/test_case_manager.rb
Labels: approved, lgtm, tide/merge-method-merge

#1373 Add rules for OCP-32152
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/projects.xyaml
Labels: approved, lgtm

#1387 Update csidriver version
  testdata/storage/csi/csi-hostpath-driverinfo.yaml
Labels: approved, lgtm

#1395 debug tempfile disappearance
  lib/launchers/gce.rb
Labels: approved, lgtm

#1389 Bug fix for connection with openstack
  lib/iaas/iaas.rb
  lib/launchers/openstack.rb
Labels: approved, lgtm

#1391 need to delete existing meteringconfig if the types are different
  features/step_definitions/cluster_configuration/cluster_config.rb
  features/step_definitions/metering.rb
Labels: CoreAutomation, Metering, approved, lgtm

#1397 fix test failure 4.4 for case OCP-24601
  lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
Labels: approved, lgtm

#1393 fix rules
  lib/rules/web/admin_console/4.6/builds.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
Labels: approved, lgtm

#1400 Hongyli fix testfailure OCPQE-1583
  lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
Labels: approved, lgtm

#1405 networkplugin: workaround api timeout
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1406 update for yaml format
  testdata/deployment/deployment-perme-failed-2.yaml
Labels: approved, lgtm

#1407 Fix OCPQE-1448
  lib/cli_executor.rb
Labels: approved, lgtm

#1401 fix 4.3 and 4.4 to support flexible scroll
  lib/rules/web/admin_console/4.3/browser_opts.yml
  lib/rules/web/admin_console/4.3/builds.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/browser_opts.yml
Labels: approved, lgtm

#1404 Forcing OCP-26822 to single node
  features/networking/pod.feature
Labels: approved, lgtm
