Repository openshift/verification-tests, pull requests merged in 2020-06, with the labels that each got.

#1184 fix_OCP-12194 project issues
  features/upgrade/node/hpa/upgrade.feature
Labels: approved, lgtm

#1177 Fix proxy step for OCP-14476
  features/step_definitions/helper_services.rb
Labels: approved, lgtm

#1059 add and update logging crd lib files
  lib/openshift/cluster_logging.rb
  lib/openshift/collector.rb
  lib/openshift/elasticsearch.rb
  lib/openshift/kibana.rb
Labels: approved, lgtm

#1158 add permission cases for ES6
  features/logging/permission.feature
  features/step_definitions/logging_metrics.rb
Labels: approved, lgtm

#1183 rules for OCP-27646
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
Labels: approved, lgtm

#1179 Fix OCP-13025
  features/upgrade/build/build-upgrade.feature
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1173 Fix cronjob lib for 4.5
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1192 Automate OCP-31331
  features/upgrade/storage/upgrade.feature
Labels: approved, lgtm

#1180 fix_OCP-12194 outdated commands
  features/cli/oc_volume.feature
Labels: approved, lgtm

#1129 Fix OCP-23030
  features/registry/registry.feature
Labels: approved, lgtm

#1185 Upgrade: Add autoscaler test
  features/upgrade/machines/machines.feature
Labels: approved, lgtm

#968 Wait default-route appearing for image-registry svc
  features/step_definitions/registry.rb
Labels: approved, lgtm

#1188 backport fix proxy environment injection
  features/step_definitions/dc.rb
  features/step_definitions/deployment.rb
  features/step_definitions/ds.rb
  features/step_definitions/rs.rb
  lib/common.rb
  lib/host.rb
Labels: approved, lgtm, tide/merge-method-merge

#1187 fix proxy environment injection and fix warnings
  features/step_definitions/dc.rb
  features/step_definitions/deployment.rb
  features/step_definitions/ds.rb
  features/step_definitions/rs.rb
  lib/common.rb
  lib/host.rb
Labels: approved, lgtm, tide/merge-method-merge

#1195 Update image url for vsphere
  testdata/storage/vsphere/pod.json
Labels: approved, lgtm

#1052 update with image degist
  features/cli/deploy.feature
  features/cli/oc_patch_apply.feature
  testdata/deployment/dc-with-pre-mid-post.yaml
  testdata/deployment/deployment-perme-failed-1.yaml
  testdata/deployment/deployment-perme-failed-3.yaml
  testdata/deployment/deployment-with-resources.json
  testdata/deployment/deployment1.json
  testdata/deployment/manual.json
  testdata/deployment/tc510612/hook-inheritance-secret-volume.json
  testdata/deployment/test-stop-failed-deployment.json
  testdata/deployment/testhook.json
  testdata/deployment/updatev1.json
  testdata/replicaSet/tc533162/rs_endpoints.yaml
Labels: approved, lgtm

#1199 update image with digest
  testdata/scheduler/multiple-schedulers/pod-no-scheduler.yaml
Labels: approved, lgtm

#1196 Add option --docker-image to new_app_as_dc
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1193 Add rules for auto OCP-29799
  lib/rules/web/admin_console/4.5/style.xyaml
Labels: approved, lgtm

#1176 remove oc debug default image for 4.5
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1200 Add rules for OCP-29210
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
Labels: approved, lgtm

#1211 Fix failing
  features/cli/oc_import_image.feature
  features/registry/is.feature
Labels: approved, lgtm

#1194 Auto OCP-29696
  features/registry/registry.feature
Labels: approved, lgtm

#1154 added support for installation of metering via OperatorHub UI
  features/step_definitions/metering.rb
  lib/openshift/metering_config.rb
  testdata/metering/configs/meteringconfig_hdfs.yaml
Labels: approved, lgtm

#1208 OCP-19470 fix Change clusterrole to build-strategy-custom
  features/upgrade/api_auth/upgrade.feature
Labels: approved, lgtm

#1205 Auto OCP-29693 OCP-29706
  features/registry/registry.feature
  lib/openshift/image_content_source_policy.rb
Labels: approved, lgtm

#1210 service: add IPv6 URL brackets and fix return
  lib/openshift/service.rb
Labels: approved, lgtm

#1209 Auto OCP-19615
  features/networking/egress-ingress.feature
Labels: approved, lgtm

#1202 Adding stage images test cases
  features/storage/csi.feature
Labels: approved, lgtm

#1219 Update the image for disconnection test
  testdata/storage/nfs/auto/rc.yml
Labels: approved, lgtm

#1163 auto kibana cases
  features/logging/kibana.feature
  lib/rules/web/admin_console/4.5/logging_kibana.xyaml
Labels: approved, lgtm

#1198 auto ES6 cases
  features/logging/cluster_logging_operator.feature
  features/logging/elasticsearch.feature
  features/step_definitions/logging.rb
  lib/openshift/cluster_logging.rb
  lib/openshift/elasticsearch.rb
Labels: approved, lgtm

#1216 fix 4.5 encoded url for check_link_and_text
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
Labels: approved, lgtm

#1206 Using taints to prevent pods from scheduling to test nodes
  features/step_definitions/machine_set.rb
  lib/openshift/machine_set.rb
  testdata/cloud/autoscaler-auto-tmpl.yml
  testdata/cloud/mhc/kubelet-killer-pod-43.yml
  testdata/cloud/mhc/kubelet-killer-pod.yml
Labels: approved, lgtm

#1212 Fix pod using congfigmap checking issues
  features/upgrade/node/hpa/upgrade.feature
Labels: approved, lgtm

#1220 Use BushSlicer::HOME
  features/networking/multus-ipv6.feature
  features/step_definitions/clouds/azure.rb
  features/step_definitions/cluster_configuration/cluster_config.rb
  features/step_definitions/cluster_configuration/csi.rb
  features/step_definitions/cluster_configuration/localstorage.rb
  features/step_definitions/cluster_configuration/snapshot.rb
  features/step_definitions/helper_services.rb
  features/step_definitions/logging.rb
  features/step_definitions/machine_healthcheck.rb
  features/step_definitions/metering.rb
  features/step_definitions/networking.rb
  features/step_definitions/pv.rb
  features/step_definitions/route.rb
  features/step_definitions/secrets.rb
  features/step_definitions/upgrade/3rd_operator.rb
  features/step_definitions/upgrade/etcd.rb
  features/svc-catalog_asb/asb.feature
  features/upgrade/sdn/policy-upgrade.feature
Labels: approved, lgtm

#1131 Auto OCP-15473
  features/networking/egress-ip.feature
Labels: approved, lgtm

#1224 Automate OCP-25727
  features/machine/machine_healthcheck.feature
  features/step_definitions/machine_healthcheck.rb
Labels: approved, lgtm

#1190 merger OCP-31315 into OCP-28108
  features/machine/autoscaler.feature
Labels: approved, lgtm

#1232 Update OCP-27655
  features/networking/sdn.feature
Labels: approved, lgtm

#1221 fix OCP-23893
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1182 Hongyli 7 alert ui
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
Labels: lgtm

#1217 Fix for stability
  features/cli/deploy.feature
Labels: approved, lgtm

#1234 Add shell script to format cucshift feature file
  tools/formatter.sh
Labels: approved, lgtm

#1225 change utility name and fix thread error
  tools/cloud_usage.rb
  tools/jenkins.rb
Labels: CoreAutomation, approved, lgtm

#1239 re-push modifications in lieu of PR #1222
  features/routing/route.feature
Labels: approved, lgtm

#1236 Updated OCP-13065 upgrade auto
  features/upgrade/node/scc.feature
Labels: approved, lgtm

#1218 Add labels parameter to new_app_as_dc cmd
  features/cli/oc_volume.feature
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1214 fix web cases
  lib/openshift/subscription.rb
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/overview.xyaml
Labels: approved, lgtm

#1245 pod: allow specifying container in pod to execute on
  features/step_definitions/pod.rb
Labels: approved, lgtm

#1203 auto OCP-26917
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
Labels: approved, lgtm

#1243 OCP-18482: Modify testdata file locations
  features/routing/rate-limit.feature
  testdata/routing/routetimeout/edge-route_edge.json
  testdata/routing/routetimeout/edge-service_unsecure.json
  testdata/routing/routetimeout/reencrypt-route_reencrypt.json
  testdata/routing/routetimeout/reencrypt-service_secure.json
  testdata/routing/routetimeout/unsecure-route_unsecure.json
  testdata/routing/routetimeout/unsecure-service_unsecure.json
Labels: approved, lgtm

#1237 Update OCP-29742
  features/networking/multus.feature
Labels: approved, lgtm

#1251 update steps to make ES cluster unhealthy
  features/logging/elasticsearch_operator.feature
  lib/openshift/elasticsearch.rb
Labels: approved, lgtm

#1191 Finish some rules for the OCM UI automation testing (#37)
  lib/rules/web/ocm_console/archived_cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_idp.xyaml
  lib/rules/web/ocm_console/cluster_list_page.xyaml
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
  lib/rules/web/ocm_console/dropdown_items.xyaml
  lib/rules/web/ocm_console/install_page.xyaml
  lib/rules/web/ocm_console/osd_creation_page.xyaml
Labels: approved, lgtm

#1248 45 rule fixes
  lib/openshift/subscription.rb
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
Labels: approved, lgtm

#1240 ERB trim mode '<' is invalid
  tools/launch_instance.rb
Labels: approved, do-not-merge/hold

#1241 ERB trim mode '<' is invalid
  features/step_definitions/pod.rb
  tools/launch_instance.rb
Labels: approved, do-not-merge/hold

#1128 OCP-29741 upgrade auto
  features/upgrade/api_auth/upgrade.feature
Labels: approved, lgtm

#1255 base RHEL8 images have only dnf
  tools/install_os_deps.sh
Labels: approved

#1256 Remove undefined step from the script
  features/cli/deploy.feature
Labels: approved, lgtm

#1254 base RHEL8 images have only dnf
  tools/install_os_deps.sh
Labels: approved, lgtm

#1253 Fix test for stability
  features/cli/job.feature
Labels: approved, lgtm

#1258 reduce ES request cpu and memory
  features/logging/collector.feature
  testdata/logging/clusterlogging/clusterlogging-storage-template.yaml
  testdata/logging/clusterlogging/example.yaml
  testdata/logging/clusterlogging/example_indexmanagement.yaml
  testdata/logging/clusterlogging/example_unmanaged.yaml
  testdata/logging/clusterlogging/scalebase.yaml
Labels: approved, lgtm

#1259 Upgrade check for OCP-27983
  features/upgrade/samples_operator/upgrade.feature
Labels: approved, lgtm

#1242 Add rules for OCP-29724
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
Labels: approved, lgtm

#1261 Fix issue about could not find files
  features/storage/reclaim_policy.feature
Labels: approved, lgtm

#1263 update OCP-25706
  features/networking/sdn.feature
Labels: approved, lgtm

#1264 Remove case id from upgrade-prepare
  features/upgrade/node/scc.feature
Labels: approved, lgtm

#1265 remove case id from upgrade-prepare
  features/upgrade/api_auth/upgrade.feature
Labels: approved, lgtm

#1266 Fix error about cannot find project
  features/upgrade/samples_operator/upgrade.feature
Labels: approved, lgtm

#1271 Fix ocp-13065 test flake
  features/upgrade/node/scc.feature
Labels: approved, lgtm

#1250 automate 2 tests and fix 1 test failure
  lib/rules/web/admin_console/4.1/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.1/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.2/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.3/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.5/monitoring_metrics.xyaml
Labels: approved, lgtm

#1269 Remove pip and minio
  tools/jenkins/slaves/Dockerfile.centos
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved, lgtm

#1270 some rule fixes
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
Labels: approved, lgtm

#1273 OCP28859 - MHC MaxUnhealthy string value should be checked for '%' sym
  features/machine/machine_healthcheck.feature
Labels: approved, lgtm

#1244 add rules for OCP-27582
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
Labels: approved, lgtm

#1178 auto case OCP-24478
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
Labels: approved, lgtm

#1275 Disable unexpected repos
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved

#1278 OCPQE-933: Fix bad regexp replacement
  features/step_definitions/pod.rb
Labels: approved, lgtm

#1277 OCPQE-933: Fix bad regexp replacement
  features/step_definitions/pod.rb
Labels: approved, lgtm

#1281 Fix OCP-22618: namespaces "aos-qe-ci" not found
  features/upgrade/marketplace/upgrade.feature
Labels: approved, lgtm

#1189 add definion for projectsconfig
  features/step_definitions/crd.rb
  lib/openshift/project_config_openshift_io.rb
Labels: approved, lgtm

#1286 using quay images
  testdata/infrastructure/hpa/hello-pod.yaml
Labels: approved, lgtm

#1283 update time wait to polciy take effect
  features/upgrade/sdn/policy-upgrade.feature
Labels: approved, lgtm

#1282 Fix file url
  features/storage/negative.feature
Labels: approved, lgtm

#1249 Add obtain test dir
  features/build/stibuild.feature
  features/step_definitions/file.rb
Labels: approved, lgtm

#1233 Auto OCP-29709
  features/upgrade/samples_operator/upgrade.feature
Labels: approved, lgtm

#1290 metering deploy refactor to use sharedPVC as default
  features/step_definitions/metering.rb
  lib/openshift/package_manifest.rb
  lib/openshift/storage_class.rb
  lib/openshift/subscription.rb
  testdata/metering/configs/metering_operatorgroup.yaml
  testdata/metering/configs/metering_subscription.yaml
  testdata/metering/configs/meteringconfig_sharedPVC.yaml
  testdata/metering/configs/pv_metering.yaml
  testdata/metering/deploy/olm/metering.catalogsource.yaml
  testdata/metering/deploy/olm/metering.operatorgroup.yaml
  testdata/metering/deploy/olm/metering.subscription.yaml
Labels: approved, lgtm

#1287 update web case for disconnected env
  features/upgrade/web/console-upgrade.feature
Labels: approved, lgtm

#1285 rules added for OCP-28297
  features/step_definitions/resources.rb
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.4/deployment.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.5/deployment.xyaml
Labels: approved, lgtm

#1272 Update help output - OCP11565
  features/cli/oc_help.feature
Labels: approved, lgtm

#982 debug Pending status with describe pod
  features/step_definitions/helper_services.rb
  features/step_definitions/pod.rb
Labels: approved, lgtm

#1292 Add option no-snippets to formatter.sh
  tools/formatter.sh
Labels: approved, lgtm

#1296 Fix OCP-14799
  features/infrastructure/cluster-capacity.feature
  features/step_definitions/admin.rb
  testdata/infrastructure/cluster-capacity/cluster-capacity-pod.yaml
Labels: approved, lgtm

#1301 Removing test data file as dup
  testdata/scheduler/pod_with_nodename.json
Labels: approved, lgtm

#1303 Update image to support disconnect cluster
  testdata/pods/pod-pull-by-tag.yaml
Labels: approved, lgtm

#1302 Remove file as it is a dup
  testdata/customscheduler/pod-noscheduler.yaml
Labels: approved, lgtm
