Repository openshift/verification-tests, pull requests merged in 2020-05, with the labels that each got.

#1033 Moving Cleanup steps to the appropriate locations
  features/networking/multus.feature
Labels: approved, lgtm

#1018 Hongyli alert browser 4.5
  lib/rules/web/admin_console/4.1/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.2/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.3/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.5/monitoring_metrics.xyaml
Labels: approved, lgtm

#1001 monitoring upgrade
  features/upgrade/monitoring/monitoring-upgrade.feature
  features/upgrade/monitoring/testdata/cm-monitoring-retention.yaml
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#985 fix eventrouter issue: ImagePullBackOff
  features/logging/cluster_logging_operator.feature
  features/logging/elasticsearch_operator.feature
  features/logging/eventrouter.feature
  features/step_definitions/logging.rb
Labels: approved, lgtm

#1013 add rules for OCP-26887
  lib/rules/web/admin_console/4.4/style.xyaml
  lib/rules/web/admin_console/4.5/style.xyaml
Labels: approved, lgtm

#1039 Added oc adm release info
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#923 Get version info from ClusterVersion
  config/config.yaml
  lib/environment.rb
Labels: approved, lgtm

#1037 Automate BZ-1827377
  features/networking/multus.feature
Labels: approved, lgtm

#1040 fix for OCP-24306
  lib/rules/web/admin_console/4.2/filters.xyaml
  lib/rules/web/admin_console/4.3/filters.xyaml
  lib/rules/web/admin_console/4.4/filters.xyaml
  lib/rules/web/admin_console/4.5/filters.xyaml
Labels: approved, lgtm

#1008 update for more stable
  features/cli/job.feature
Labels: approved, lgtm

#1041 Added options for oc adm release info
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#1044 Remove invalid features
  features/images/hot_depoy.feature
Labels: approved, lgtm

#1024 Fix ui cases
  lib/rules/web/admin_console/4.1/actions.xyaml
  lib/rules/web/admin_console/4.2/actions.xyaml
  lib/rules/web/admin_console/4.3/actions.xyaml
  lib/rules/web/admin_console/4.4/actions.xyaml
  lib/rules/web/admin_console/4.5/actions.xyaml
  lib/rules/web/admin_console/4.5/builds.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.5/deployment.xyaml
  lib/rules/web/admin_console/4.5/overview.xyaml
  lib/rules/web/admin_console/4.5/route.xyaml
Labels: approved, lgtm

#1027 Auto OCP-25940
  features/networking/ptp_operator.feature
Labels: approved, lgtm

#1011 Add rules for alert-message and alert-manager OCP-29209
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/environments.xyaml
  lib/rules/web/admin_console/4.5/monitoring.xyaml
  lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
Labels: approved, lgtm

#1047 Hongyali make ui case work 41 42 43
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
Labels: approved, lgtm

#1036 fixed scenarios post few bugs
  features/networking/multus.feature
Labels: approved, lgtm

#1046 image-registry/samples/openshift-controller-manager operator upgrade
  features/upgrade/samples_operator/upgrade.feature
Labels: approved, lgtm

#1051 remove invalid creds
  lib/launchers/alicloud.rb
Labels: approved, lgtm

#1050 minor cosmetic changes
  tools/find_image.rb
Labels: approved, lgtm

#1057 Revert "remove invalid creds"
  lib/launchers/alicloud.rb
Labels: approved, lgtm

#1048 Auto jenkins upgrade case
  features/step_definitions/images/jenkins.rb
  features/upgrade/jenkins/upgrade.feature
  lib/rules/web/images/jenkins_2/jenkins_2.xyaml
Labels: approved, lgtm

#1045 Clean-up scenarios OCP-11xxx (3.x scenarios, not suitable for 4.x)
  features/admin/pod.feature
  features/build/buildconfig.feature
  features/build/buildlogic.feature
  features/build/custombuild.feature
  features/build/dockerbuild.feature
  features/build/stibuild.feature
  features/cli/build.feature
  features/cli/deploy.feature
  features/cli/initcontainers.feature
  features/cli/job.feature
  features/cli/oc_attach.feature
  features/cli/oc_import_image.feature
  features/cli/oc_login.feature
  features/cli/oc_secrets.feature
  features/cli/oc_tag.feature
  features/cli/oc_volume.feature
  features/cli/policy.feature
  features/cli/rolling_deploy.feature
  features/cli/scale.feature
  features/images/jenkins.feature
  features/metrics/system_metric.feature
  features/registry/registry.feature
  features/registry/remote.feature
  features/rest/webhook.feature
  features/routing/haproxy-router.feature
  features/routing/wildcard-route.feature
  features/web/build.feature
  features/web/check_page.feature
  features/web/configmap.feature
  features/web/create.feature
  features/web/deployments.feature
  features/web/filter.feature
  features/web/hooks.feature
  features/web/membership.feature
  features/web/pod.feature
  features/web/rollback.feature
  features/web/routes.feature
  features/web/scale.feature
  features/web/secrets.feature
Labels: approved

#1003 Auto OCP-29477
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
Labels: approved, lgtm

#1042 Update: Modify iscsi/nfs image url for disconnect env
  features/step_definitions/helper_services.rb
  testdata/storage/iscsi/iscsi-target.json
  testdata/storage/nfs/nfs-server.yaml
Labels: approved, lgtm

#1063 add create deploymentconfig lib
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#1060 Fix failure test OCP-28106 in polar run_20200508-0647
  lib/rules/web/admin_console/4.1/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.2/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.3/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.5/monitoring_metrics.xyaml
Labels: approved, lgtm

#1055 fix web cases
  lib/rules/web/admin_console/4.3/operator_hub.xyaml
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/check_links.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/user_management.xyaml
Labels: approved, lgtm

#1049 fix for web cases
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/base/logout.xyaml
Labels: approved, lgtm

#1062 Fix get_version from cluster version
  lib/environment.rb
Labels: approved, lgtm

#1064 Clean-up scenarios OCP-12xxx (3.x scenarios, not suitable for 4.x)
  features/admin/pod.feature
  features/admin/quota.feature
  features/build/dockerbuild.feature
  features/cli/initcontainers.feature
  features/cli/oc_import_image.feature
  features/cli/oc_secrets.feature
  features/cli/oc_tag.feature
  features/cli/secrets.feature
  features/images/jenkins.feature
  features/metrics/install_uninstall.feature
  features/quickstarts/quickstarts.feature
  features/routing/haproxy-router.feature
  features/routing/route.feature
  features/storage/reclaim_policy.feature
  features/storage/storage_class.feature
  features/web/build.feature
  features/web/check_page.feature
  features/web/configmap.feature
  features/web/create.feature
  features/web/deployments.feature
  features/web/k8s-deployments.feature
  features/web/login.feature
  features/web/project.feature
  features/web/routes.feature
  features/web/settings.feature
Labels: approved, lgtm

#1067 Update image
  testdata/pods/graceful-delete/10.json
Labels: approved, lgtm

#988 auto OCP-29199
  features/machine/machine.feature
  features/step_definitions/machine_set.rb
Labels: approved, lgtm

#1061 replace -v with --suggest for oc status
  lib/openshift/project.rb
Labels: approved, lgtm

#1038 fixes for logging 4.5
  features/logging/cluster_logging_operator.feature
  features/logging/collector.feature
  features/logging/elasticsearch.feature
  features/logging/elasticsearch_operator.feature
  features/logging/eventrouter.feature
  features/step_definitions/logging.rb
  features/step_definitions/logging_metrics.rb
  lib/openshift/service.rb
Labels: approved, lgtm

#1071 Add oc_createcronjob&createjob functionality
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#1074 fix wrong arguement
  features/step_definitions/machine_set.rb
Labels: approved, lgtm

#1056 Auto ocp-22734
  features/upgrade/api_auth/upgrade.feature
Labels: approved, lgtm

#1053 OCP-22673 upgrade auto
  features/upgrade/api_auth/upgrade.feature
Labels: approved, lgtm

#1073 Fix BushSlicer::HOME
  features/step_definitions/helper_services.rb
Labels: approved, lgtm

#1068 Fix auto case OCP_10696
  features/cli/oc_patch_apply.feature
Labels: approved, lgtm

#1080 OCPQE-82 too many legitimate error messages when rebooting nodes
  lib/host.rb
Labels: approved, lgtm

#1075 Fix format for api auth upgrade
  features/upgrade/api_auth/upgrade.feature
Labels: approved

#1085 Fix metering
  features/step_definitions/metering.rb
Labels: CoreAutomation, Metering, approved, lgtm

#1081 fix_err_OCP-22606
  features/upgrade/etcd/upgrade.feature
Labels: approved, lgtm

#1076 fix case
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
Labels: approved, lgtm

#1088 update for ocp-9563
  features/cli/deploy.feature
Labels: approved, lgtm

#1070 fix OCP-19608
  lib/rules/web/admin_console/4.1/route.xyaml
  lib/rules/web/admin_console/4.2/route.xyaml
  lib/rules/web/admin_console/4.3/route.xyaml
  lib/rules/web/admin_console/4.4/route.xyaml
  lib/rules/web/admin_console/4.5/filters.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/route.xyaml
Labels: approved, lgtm

#1086 auto OCP-30501
  features/step_definitions/node.rb
  features/upgrade/routing/upgrade.feature
Labels: approved, lgtm

#1058 remove outdated steps, files and scenarios
  features/cluster_configuration/logging_metrics_metering.feature
  features/metrics/OWNERS
  features/metrics/install_uninstall.feature
  features/metrics/system_metric.feature
  features/step_definitions/logging_metrics.rb
  features/test/logging_metrics.feature
  testdata/logging_metrics/OCP-10214/inventory
  testdata/logging_metrics/OCP-11821/deployer_ocp11821.yaml
  testdata/logging_metrics/OCP-11821/inventory
  testdata/logging_metrics/OCP-12186/inventory
  testdata/logging_metrics/OCP-12234/inventory
  testdata/logging_metrics/OCP-12276/inventory
  testdata/logging_metrics/OCP-12305/inventory
  testdata/logging_metrics/OCP-12377/inventory
  testdata/logging_metrics/OCP-15529/inventory
  testdata/logging_metrics/OCP-16138/inventory
  testdata/logging_metrics/OCP-17163/inventory
  testdata/logging_metrics/base_ansible_ose.yaml
  testdata/logging_metrics/default_base_inventory
  testdata/logging_metrics/default_deployer.yaml
  testdata/logging_metrics/default_install_logging_params
  testdata/logging_metrics/default_install_metering_params
  testdata/logging_metrics/default_install_metrics_params
  testdata/logging_metrics/default_install_prometheus_params
  testdata/logging_metrics/default_inventory_prometheus
  testdata/logging_metrics/default_inventory_uninstall_prometheus
  testdata/logging_metrics/default_uninstall_logging_params
  testdata/logging_metrics/default_uninstall_metering_params
  testdata/logging_metrics/default_uninstall_metrics_params
  testdata/logging_metrics/default_uninstall_prometheus_params
  testdata/logging_metrics/generic_uninstall_inventory
  testdata/logging_metrics/logging_deployer_configmap.yaml
  testdata/logging_metrics/prom2json_pod.yaml
  testdata/logging_metrics/test_data.json
  testdata/logging_metrics/test_data_bulk.json
Labels: approved, lgtm

#978 Auto test OCP-12930
  features/networking/multicast.feature
Labels: approved, lgtm

#1072 Remove unnecessary version check
  features/test/version_compare.feature
  lib/environment.rb
Labels: approved, lgtm

#1069 Replace --image option
  features/cli/build.feature
Labels: approved, lgtm

#1087 Add image pruners
  lib/openshift/imagepruners_imageregistry_operator_openshift_io.rb
Labels: approved, lgtm

#1031 auto sriov stage case
  features/networking/sriov.feature
Labels: approved, lgtm

#1065 update rules for kibana
  features/step_definitions/admin_console.rb
  features/step_definitions/logging_metrics.rb
  lib/rules/web/admin_console/4.1/logging_kibana.xyaml
  lib/rules/web/admin_console/4.2/logging_kibana.xyaml
  lib/rules/web/admin_console/4.3/logging_kibana.xyaml
  lib/rules/web/admin_console/4.4/logging_kibana.xyaml
  lib/rules/web/images/logging/login.xyaml
  lib/rules/web/images/logging/logout.xyaml
Labels: approved, lgtm

#714 add networkpolicy upgrade case
  features/upgrade/sdn/policy-upgrade.feature
Labels: approved, lgtm, size/M

#1082 Fix OCP-13025
  features/upgrade/build/build-upgrade.feature
Labels: approved, lgtm

#1054 Auto OCP-19470
  features/upgrade/api_auth/upgrade.feature
Labels: approved, lgtm

#1099 Using ruby:2.5 instead of latest tag
  features/upgrade/build/build-upgrade.feature
Labels: approved, lgtm

#897 OCP-26373 and OVN funtionality check def
  features/networking/pod.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1092 add step to check logs
  features/logging/collector.feature
  features/step_definitions/logging.rb
Labels: approved, lgtm

#1102 Add the test of clusterservicebroker
  features/svc-catalog_asb/svc-catalog.feature
Labels: approved, lgtm

#1103 fix issue when curl with token
  features/step_definitions/logging_metrics.rb
Labels: approved, lgtm

#1097 Add generation function for statefulset
  lib/openshift/stateful_set.rb
Labels: approved, lgtm

#1083 Improve cloud tests
  features/machine/autoscaler.feature
  features/machine/machine.feature
  features/machine/machine_healthcheck.feature
  features/step_definitions/machine.rb
  features/step_definitions/machine_healthcheck.rb
  features/step_definitions/machine_set.rb
  features/upgrade/machines/machines.feature
  lib/openshift/machine.rb
Labels: approved, lgtm

#1093 automated 3 UI tests and fix upgrade typo
  features/upgrade/monitoring/monitoring-upgrade.feature
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
Labels: approved, lgtm

#1109 Clean-up scenarios OCP-13xxx (3.x scenarios, not suitable for 4.x)
  features/admin/master_config.feature
  features/admin/pod.feature
  features/cli/taint-toleration.feature
  features/quickstarts/quickstarts.feature
  features/storage/storage_class.feature
  features/web/overview.feature
  features/web/service-catalog/create.feature
  features/web/service-catalog/project.feature
Labels: approved, lgtm

#1111 Fix upgrade prepare for OCP-27664/22712
  features/upgrade/machines/machines.feature
Labels: approved, lgtm

#1113 Use quay.io
  features/node/node.feature
Labels: approved, lgtm

#1089 Wait some time to make steps pass through.
  features/cli/policy.feature
Labels: approved, lgtm

#1115 A small fix about the download step change
  features/cli/policy.feature
Labels: approved, lgtm

#1119 fix monitoring upgrade issue OCPQE-476
  features/upgrade/monitoring/monitoring-upgrade.feature
Labels: approved, lgtm

#1108 Add rules for OCP-24281
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/projects.xyaml
  lib/rules/web/admin_console/4.2/user_management.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/projects.xyaml
  lib/rules/web/admin_console/4.3/user_management.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/user_management.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/user_management.xyaml
Labels: approved, lgtm

#1126 GCE IaaS connector support
  lib/environment.rb
  lib/environment_manager.rb
  lib/iaas/iaas.rb
  lib/openshift/infrastructure.rb
Labels: approved, lgtm, tide/merge-method-merge

#1123 Clean-up scenarios OCP-1xxxx (3.x scenarios, not suitable for 4.x)
  features/build/dockerbuild.feature
  features/build/genericbuild.feature
  features/build/stibuild.feature
  features/images/jenkins.feature
  features/networking/egress-router.feature
  features/networking/pod.feature
  features/networking/sdn.feature
  features/node/node.feature
  features/routing/config-manager.feature
  features/routing/haproxy-router.feature
  features/routing/http2.feature
  features/routing/logging.feature
  features/storage/aws.feature
  features/svc-catalog_asb/apb-update.feature
  features/svc-catalog_asb/asb.feature
  features/svc-catalog_asb/svc-catalog.feature
  features/web/create.feature
  features/web/environments.feature
  features/web/notification_drawer.feature
  features/web/secrets.feature
  features/web/settings.feature
Labels: approved, lgtm

#1098 fix OCP-26029
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
Labels: approved, lgtm

#1120 Add oc/kubectl for 4.6
  lib/rules/cli/4.6.yaml
  lib/rules/cli/kubectl-4.6.yaml
Labels: approved, lgtm

#1121 fix autofailures in run 20200518-1111
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
Labels: approved, lgtm

#1116 check inf first and then perform operation
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1100 add upgrade case OCP-13022
  features/upgrade/node/node-upgrade.feature
  testdata/customresource/custom_kubelet.yaml
Labels: approved, lgtm

#1104 Automate OCP-13016 (node hpa upgrade test)
  features/upgrade/node/hpa/upgrade.feature
Labels: approved, lgtm

#1124 45 rules fixes
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.2/overview.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/overview.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/overview.xyaml
  lib/rules/web/admin_console/4.5/catalog.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/overview.xyaml
  lib/rules/web/admin_console/4.5/projects.xyaml
  lib/rules/web/admin_console/4.5/status.xyaml
Labels: approved, lgtm

#1122 OCP-28718 - Configurable timeout for mhc
  features/machine/machine_healthcheck.feature
  testdata/cloud/mhc/mhc_configurabletimeout.yaml
Labels: approved, lgtm

#1118 merger OCP-29389 into OCP-29199
  features/machine/machine.feature
  features/step_definitions/machine_set.rb
Labels: approved, lgtm

#1130 fix issue running exec command with oc 4.5
  features/step_definitions/logging_metrics.rb
Labels: approved, lgtm

#1107 add rules for OCP-24223
  lib/rules/web/admin_console/4.2/style.xyaml
  lib/rules/web/admin_console/4.3/style.xyaml
  lib/rules/web/admin_console/4.4/style.xyaml
  lib/rules/web/admin_console/4.5/style.xyaml
Labels: approved, lgtm

#1132 Clean-up scenarios OCP-2xxxx (3.x scenarios, not suitable for 4.x)
  features/storage/csi.feature
  features/test/upgrade.feature
Labels: approved, lgtm

#1101 add noproxy
  features/upgrade/workloads/oc-upgrade.feature
Labels: approved, lgtm

#1140 Clean-up scenarios OCP-9xxx (3.x scenarios, not suitable for 4.x)
  features/containers/containers.feature
  features/networking/pod.feature
  features/networking/service.feature
  features/routing/haproxy-router.feature
  features/storage/NoDiskConflict.feature
  features/storage/glusterfs.feature
  features/storage/persistent_volume.feature
  features/storage/pre-bind.feature
  features/web/check_link.feature
Labels: approved, lgtm

#1143 change the review Owner
  features/networking/OWNERS
Labels: approved, lgtm

#1146 fix upgrade issue to check common api to many versions
  features/upgrade/monitoring/monitoring-upgrade.feature
Labels: approved, lgtm

#1135 [IPI on OSP] add funtions to operate network, subnet and router
  lib/launchers/openstack.rb
Labels: approved, lgtm

#1141 rules added for OCP-27586
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
Labels: approved, lgtm

#1144 Clean-up OWNERS from empty folders
  features/web/OWNERS
  features/web/service-catalog/OWNERS
Labels: approved, lgtm

#1147 auto OCP-27594
  features/routing/operator.feature
  testdata/routing/operator/ingressctl-nsowner.yaml
Labels: approved, lgtm

#1149 replease new-app with create dc
  features/cli/deploy.feature
Labels: approved, lgtm

#1139 Bug fix for iscsi test on disconnected cluster
  testdata/storage/iscsi/iscsi-target.json
Labels: approved, lgtm

#1114 Add create deployment for kubectl
  lib/rules/cli/kubectl-4.1.yaml
Labels: approved, lgtm

#1134 Fixcaseid
  features/build/dockerbuild.feature
  features/build/stibuild.feature
Labels: approved, lgtm

#1125 more robust hooks and fix for 4.5 console
  features/step_definitions/web.rb
  lib/rules/web/admin_console/4.1/browser_opts.yml
  lib/rules/web/admin_console/4.2/browser_opts.yml
  lib/rules/web/admin_console/4.3/browser_opts.yml
  lib/rules/web/admin_console/4.4/browser_opts.yml
  lib/rules/web/admin_console/4.5/browser_opts.yml
  lib/rules/web/images/jenkins_2/browser_opts.yml
  lib/rules/web/ocm_console/browser_opts.yml
  lib/webauto/web4cucumber.rb
Labels: approved, lgtm, tide/merge-method-merge

#1133 Add rule for checking documentation link OCP-29210
  lib/rules/web/admin_console/4.4/check_links.xyaml
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.5/check_links.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
Labels: approved, lgtm

#1142 Auto OCP-29200
  lib/rules/web/admin_console/4.1/check_links.xyaml
  lib/rules/web/admin_console/4.2/check_links.xyaml
  lib/rules/web/admin_console/4.3/check_links.xyaml
  lib/rules/web/admin_console/4.4/check_links.xyaml
  lib/rules/web/admin_console/4.5/check_links.xyaml
Labels: approved, lgtm

#1152 Fix testdata path for monitoring
  features/upgrade/monitoring/monitoring-upgrade.feature
  testdata/monitoring/upgrade/cm-monitoring-retention.yaml
Labels: approved, lgtm

#1156 update image to pull from quay.io
  testdata/configmap/pod-configmap-command.yaml
  testdata/configmap/pod-configmap-env.yaml
  testdata/configmap/pod-configmap-volume1.yaml
  testdata/configmap/pod-configmap-volume2.yaml
  testdata/hpa/rc-hello-openshift.yaml
  testdata/job/job-secret-env.yaml
  testdata/pods/graceful-delete/0.json
  testdata/pods/graceful-delete/default.json
  testdata/pods/pod-with-nodeselector.yaml
  testdata/pods/selector-east.json
  testdata/pods/tc533910/readiness-probe-exec.yaml
  testdata/quota/pod-notbesteffort.yaml
  testdata/rc/idle-rc-1.yaml
  testdata/rc/idle-rc-2.yaml
  testdata/secrets/secret-env-pod.yaml
Labels: approved, lgtm

#1151 ignore STDERR when running node commands
  lib/iaas/iaas.rb
Labels: approved, lgtm, tide/merge-method-merge

#1148 fix web cases
  lib/rules/web/admin_console/4.3/environments.xyaml
  lib/rules/web/admin_console/4.3/route.xyaml
  lib/rules/web/admin_console/4.4/environments.xyaml
  lib/rules/web/admin_console/4.4/route.xyaml
Labels: approved, lgtm

#1066 rules for OCP-27631
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
Labels: approved, lgtm

#1159 Fix jenkins login issue
  features/images/jenkins.feature
  lib/rules/web/images/jenkins_2/jenkins_2.xyaml
Labels: approved, lgtm

#1136 Updated test case - OCP27609
  features/machine/machine.feature
Labels: approved, lgtm

#1157 update for new-app
  features/cli/deploy.feature
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#1145 Forcing scenario to execute on specific node only
  features/networking/multus.feature
Labels: approved, lgtm

#1162 run cmd deprecated deploymentconfig, change to use dc template.
  features/step_definitions/helper_services.rb
  testdata/templates/ssh-git/ssh-git-dc.yaml
Labels: approved, lgtm

#1095 update cronjob lib and ocp-17515
  features/cli/job.feature
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#1161 fix oc new-app issue for console cases
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1167 fix OCP-27609
  features/machine/machine.feature
Labels: approved, lgtm

#1165 fix for web cases
  lib/rules/web/admin_console/4.4/catalog.xyaml
  lib/rules/web/admin_console/4.5/catalog.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  testdata/olm/catalogsource-template.yaml
Labels: approved, lgtm

#1169 Replace to use quay images
  testdata/secrets/tc483168/first-secret-pod.yaml
  testdata/secrets/tc483168/second-secret-pod.yaml
Labels: approved, lgtm

#1155 add rules for OCP-25803
  lib/openshift/cluster_service_version.rb
  lib/openshift/custom_resource_definition.rb
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/builds.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.5/builds.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
Labels: approved, lgtm

#983 always use multus image as oc debug image
  lib/host.rb
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#1164 update for proxy config
  features/step_definitions/helper_services.rb
Labels: approved, lgtm

#1150 automate case OCP-24222
  lib/rules/web/admin_console/4.1/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.2/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.3/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.5/monitoring_metrics.xyaml
Labels: approved, lgtm

#1174 fix oc run --generator rule
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1153 add debug step to isolate the auth issue
  lib/login.rb
Labels: approved, lgtm

#1170 update OCP-13022
  features/upgrade/node/node-upgrade.feature
Labels: approved, lgtm

#1172 some rule fixes
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.2/quota.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.5/quota.xyaml
Labels: approved, lgtm
