Repository openshift/verification-tests, pull requests merged in 2020-04, with the labels that each got.

#898 Fix occacional failure of ci job
  tools/openshift-ci/Dockerfile.centos
Labels: approved, lgtm

#895 rules added for OCP-19608
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.1/route.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.2/route.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/route.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/route.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/route.xyaml
Labels: approved, lgtm

#902 automate OCP-22596
  features/build/stibuild.feature
Labels: approved, lgtm

#903 fix OCP-26910
  lib/rules/web/admin_console/4.3/projects.xyaml
  lib/rules/web/admin_console/4.4/projects.xyaml
  lib/rules/web/admin_console/4.5/projects.xyaml
Labels: approved, lgtm

#877 Making test more stable
  features/machine/machine_healthcheck.feature
  features/step_definitions/machine.rb
  features/step_definitions/machine_set.rb
  testdata/cloud/autoscaler-auto-tmpl.yml
Labels: approved, lgtm

#904 ignore one more possible error when rebooting nodes
  lib/host.rb
Labels: approved

#909 Fix OCP-23030
  features/registry/registry.feature
Labels: approved, lgtm

#911 Fix step "CA trust is added to the pod-for-ping"
  features/step_definitions/helper_services.rb
Labels: approved, lgtm

#912 Fix ocp 12400
  features/registry/registry.feature
Labels: approved, lgtm

#726 Ensure goto action complete loading current page
  lib/rules/web/admin_console/4.4/goto.xyaml
Labels: approved, lgtm, size/M

#915 allow user defined token to be specified and change uri parameter to …
  features/step_definitions/prometheus.rb
Labels: approved, lgtm

#914 remove cases that are only applicable to the 3.x branch
  features/web/login.feature
Labels: approved, lgtm

#916 Node proxy config verification
  features/node/proxy.feature
Labels: approved, lgtm

#917 Fix OCP-12430
  features/cli/policy.feature
Labels: approved, lgtm

#862 Add files required for custom scheduler
  testdata/customscheduler/my-scheduler.yaml
  testdata/customscheduler/pod-customscheduler.yaml
  testdata/customscheduler/pod-defaultscheduler.yaml
  testdata/customscheduler/pod-noscheduler.yaml
Labels: approved, lgtm

#919 SSH session closed while IO thread listening
  lib/ssh.rb
  lib/test_case_manager.rb
Labels: approved, lgtm

#798 Finish some page rules for OCM UI automation
  features/step_definitions/ocm.rb
  lib/environment.rb
  lib/rules/web/ocm_console/archived_cluster_detail.xyaml
  lib/rules/web/ocm_console/archived_clusters.xyaml
  lib/rules/web/ocm_console/browser_opts.yml
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_detail_access_control_tab.xyaml
  lib/rules/web/ocm_console/cluster_detail_logs_tab.xyaml
  lib/rules/web/ocm_console/cluster_detail_monitoring_tab.xyaml
  lib/rules/web/ocm_console/cluster_detail_overview_tab.xyaml
  lib/rules/web/ocm_console/cluster_list_page.xyaml
  lib/rules/web/ocm_console/creation_cards_page.xyaml
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
  lib/rules/web/ocm_console/dropdown_items.xyaml
  lib/rules/web/ocm_console/install_page.xyaml
  lib/rules/web/ocm_console/login.xyaml
  lib/rules/web/ocm_console/ocm_workflow.xyaml
  lib/rules/web/ocm_console/osd_creation_page.xyaml
  lib/rules/web/ocm_console/register_disconnected_cluster_page.xyaml
  lib/rules/web/ocm_console/subscription_page.xyaml
Labels: lgtm, size/XXL

#921 fix rule for a Chinese colon character
  lib/rules/web/admin_console/4.3/projects.xyaml
Labels: approved, lgtm

#926 update the image digest
  testdata/networking/multus-cni/Pods/1interface-host-device.yaml
Labels: approved, lgtm

#922 Clean-up OCP-9570 (3.x scenarios, not suitable for 4.x)
  features/quickstarts/quickstarts.feature
Labels: approved, lgtm

#891 Test s2i build in disconnect cluster
  features/build/stibuild.feature
  testdata/build/httpd-ex.git/HEAD
  testdata/build/httpd-ex.git/objects/09/2fbaa682c00d2e2ebec17a1eb2c3eb215a50fe
  testdata/build/httpd-ex.git/objects/1e/a686113129a4f236d5bebc6e0c2eb75aba0fa9
  testdata/build/httpd-ex.git/objects/27/9f76ae27c2bf7a815ab857c804cb6d7f4f1a1e
  testdata/build/httpd-ex.git/objects/3d/70a8d46c2cbc7963c08e80028d7650f8f839d8
  testdata/build/httpd-ex.git/objects/8a/91064ca6613a12721efae8d98274083dd35110
  testdata/build/httpd-ex.git/objects/c9/e534fe1cc3efa5dfaf1b4c98e07091d39ef8f1
  testdata/build/httpd-ex.git/objects/cc/2be2ce48bf4c67f70b3958d4f3688c8ef0fcec
  testdata/build/httpd-ex.git/packed-refs
  testdata/image/gitserver/gitserver-ephemeral.yaml
Labels: approved, lgtm

#925 fix OCP-24106 OCP-25761
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/check_links.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
Labels: approved, lgtm

#867 modifed OCP-25787 to support 4.3 and 4.4 releases
  features/networking/sdn.feature
Labels: approved, lgtm

#931 add another possible reboot error message
  lib/host.rb
Labels: approved, lgtm

#918 Automated OCP-27666
  lib/rules/web/admin_console/4.4/catalog.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.5/catalog.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
Labels: approved, lgtm

#924 update inspect rules
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#935 update cronjob method
  lib/openshift/cron_job.rb
Labels: approved, lgtm

#938 add must-gather command
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#933 Fix case ID
  features/networking/egress-ip.feature
Labels: approved, lgtm

#939 fix machine annotations don't match the output
  features/machine/autoscaler.feature
Labels: approved, lgtm

#940 Fix new-build with binary option
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#942 Update damonset version to v1
  testdata/storage/misc/damonset.json
Labels: approved, lgtm

#920 added skeleton for 'proxy' class
  lib/openshift/proxy.rb
Labels: CoreAutomation, approved, lgtm

#899 Add workaround to https://bugzilla.redhat.com/show_bug.cgi?id=1776594
  features/logging/collector.feature
Labels: approved, lgtm

#937 Automated OCP-25777
  lib/rules/web/admin_console/4.1/route.xyaml
  lib/rules/web/admin_console/4.2/deployment.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.2/route.xyaml
  lib/rules/web/admin_console/4.3/deployment.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/route.xyaml
  lib/rules/web/admin_console/4.4/deployment.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/route.xyaml
  lib/rules/web/admin_console/4.5/deployment.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/route.xyaml
Labels: approved, lgtm

#944 use admin for checking OpenShiftSDN pods
  features/step_definitions/networking.rb
Labels: approved, lgtm

#945 OCP-26035: increase unidle check timeout to 30 seconds.
  features/networking/service.feature
Labels: approved, lgtm

#946 fix relative path for OCP-11970 etc
  features/routing/abrouting.feature
  features/routing/haproxy-router.feature
Labels: approved, lgtm

#910 Auto case OCP-28633
  features/networking/multus.feature
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/whereabouts-macvlan.yaml
Labels: approved, lgtm

#905 Automate OCP-28968
  features/networking/multus-ipv6.feature
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/IPv6/macvlan-bridge-v6.yaml
  testdata/networking/multus-cni/Pods/IPv6/1interface-macvlan-bridge-v6.yaml
Labels: approved, lgtm

#950 fix testcase failure
  features/storage/add_update_delete_volume.feature
Labels: approved, lgtm

#952 follow up 946: remove extra double quotes
  features/routing/abrouting.feature
  features/routing/haproxy-router.feature
Labels: approved, lgtm

#956 more update for ocp 10284
  features/storage/add_update_delete_volume.feature
Labels: approved, lgtm

#948 Add a rule to check sidebar loaded for OCP-25817
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
Labels: approved, lgtm

#961 Use the new test image to enable case can be run in disconnected cluster
  testdata/storage/nfs/security/pod-supplementalgroup.json
Labels: approved, lgtm

#959 Clean-up OCP-9640/11726 (3.x scenarios, not suitable for 4.x)
  features/storage/hostpath.feature
Labels: approved, lgtm

#962 machines method for MachineSet
  lib/openshift/machine_set.rb
Labels: approved, lgtm, tide/merge-method-merge

#960 Use a cloned machineset to test
  features/upgrade/machines/machines.feature
Labels: approved, lgtm

#890 Fix automation scripts to run cases in disconnected env
  features/cli/oc_volume.feature
  testdata/storage/misc/pod.yaml
Labels: approved, lgtm

#947 fix script for OCP-22308
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
Labels: approved, lgtm

#963 Fix an upgrade scenario
  features/upgrade/etcd/upgrade.feature
Labels: approved, lgtm

#969 Make test stable on osp
  features/step_definitions/machine_set.rb
Labels: approved, lgtm

#955 Fix web cases
  lib/rules/web/admin_console/4.1/filters.xyaml
  lib/rules/web/admin_console/4.2/filters.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/filters.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/filters.xyaml
  lib/rules/web/admin_console/4.5/filters.xyaml
Labels: approved, lgtm

#971 special step to obtain test data files
  features/admin/quota.feature
  features/build/genericbuild.feature
  features/cli/build.feature
  features/cli/deployment.feature
  features/cli/job.feature
  features/cli/policy.feature
  features/cli/secrets.feature
  features/images/jenkins.feature
  features/networking/egress-ingress.feature
  features/online/route.feature
  features/routing/http2.feature
  features/routing/idle.feature
  features/step_definitions/cluster_configuration/csi.rb
  features/step_definitions/cluster_configuration/localstorage.rb
  features/step_definitions/file.rb
  features/step_definitions/helper_services.rb
  features/test/scc.feature
  features/web/create.feature
  features/web/hooks.feature
Labels: approved

#951 Auto work for OCP-28518
  features/networking/multus.feature
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/route-override.yaml
Labels: approved, lgtm

#967 added method to get the containers spec
  lib/openshift/deployment.rb
Labels: approved, lgtm

#958 Add rules for OCP-27590
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
Labels: approved, lgtm

#973 Fix OCP-21772 for unstable issues
  lib/rules/web/admin_console/4.4/projects.xyaml
Labels: approved, lgtm

#943 Add step for OCP-29435
  features/step_definitions/deployment.rb
Labels: approved, lgtm

#972 rules update for OCP-19727
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
Labels: approved, lgtm

#976 Update: Fix OCP-13386/13387/13388
  testdata/storage/vsphere/storageclass.yml
Labels: approved, lgtm

#957 Align to standard aws credential file format
  lib/launchers/amz.rb
Labels: approved, lgtm

#953 add rules for OCP-27835
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
Labels: approved, lgtm

#936 Bug fix for OCP-16485
  features/storage/regression.feature
  testdata/storage/misc/damonset.json
Labels: approved, lgtm

#979 Clean-up several obsoleted scenarios (3.x scenarios, not suitable for 4.x)
  features/build/dockerbuild.feature
  features/metrics/install_uninstall.feature
  features/storage/glusterfs.feature
  features/storage/negative.feature
  features/storage/rbd.feature
  features/storage/reclaim_policy.feature
  features/test/admin.feature
  features/web/overview.feature
  features/web/project.feature
  features/web/pvc.feature
  features/web/registry.feature
Labels: approved, lgtm

#941 moving asb stage cases from cucushift to verification-test
  features/svc-catalog_asb/asb.feature
Labels: approved, lgtm

#858 OCP-24363 - Reconciling machine taints with nodes
  features/machine/machine.feature
Labels: approved, lgtm

#977 rules added for OCP-29198
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
Labels: approved, lgtm

#989 Clean-up obsoleted scenarios 103xx (3.x scenarios, not suitable for 4.x)
  features/storage/dynamic_provisioning.feature
  features/storage/glusterfs.feature
  features/web/service.feature
  features/web/settings.feature
Labels: approved, lgtm

#990 Update: Change test file path for OCP-9638
  features/storage/iscsi.feature
  testdata/storage/iscsi/pod-security.json
  testdata/storage/iscsi/pv-rwo.json
Labels: approved, lgtm

#987 Add pip and minio to interact with S3 bucket
  tools/jenkins/slaves/Dockerfile.centos
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved, lgtm

#981 auto OCP-29747 and 29747
  features/upgrade/routing/upgrade.feature
Labels: approved, lgtm

#984 Update to handle instanceState node changed to vmState in Azure clusters
  lib/openshift/machine.rb
Labels: approved, lgtm

#986 Add web rules for OCP-24307
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/style.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/style.xyaml
Labels: approved, lgtm

#994 Clean-up obsoleted scenarios 10xxx (3.x scenarios, not suitable for 4.x)
  features/admin/master_config.feature
  features/build/genericbuild.feature
  features/cli/build.feature
  features/cli/initcontainers.feature
  features/cli/pod.feature
  features/cli/secrets.feature
  features/images/jenkins.feature
  features/metrics/system_metric.feature
  features/online/logging.feature
  features/registry/remote.feature
  features/storage/cloud_provider.feature
  features/storage/dynamic_provisioning.feature
  features/storage/glusterfs.feature
  features/storage/rbd.feature
  features/storage/reclaim_policy.feature
  features/web/catalog.feature
  features/web/check_page.feature
  features/web/create.feature
  features/web/deployments.feature
  features/web/imagestreams.feature
  features/web/limits.feature
  features/web/pvc.feature
  features/web/service.feature
Labels: approved, lgtm

#991 Update: Fix OCP-14173
  features/storage/quota.feature
Labels: approved, lgtm

#998 fix OCP-24415
  lib/rules/web/admin_console/4.4/storage.xyaml
  lib/rules/web/admin_console/4.5/storage.xyaml
Labels: approved, lgtm

#999 fix OCP-27609
  features/machine/machine.feature
Labels: approved, lgtm

#980 rules for OCP-28954
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
Labels: approved, lgtm

#1005 add rules for OCP-21245
  lib/rules/web/admin_console/4.2/environments.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/environments.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/environments.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.5/environments.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
Labels: approved, lgtm

#1015 update ingress source OCP-18789
  features/routing/ingress-route.feature
  testdata/routing/ingress/test-ingress.json
Labels: approved, lgtm

#1016 Modifying interface names on OVN
  features/networking/sdn.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1019 use images from quay.io
  testdata/logging/logforwarding/elasticsearch/insecure/deployment.yaml
  testdata/logging/logforwarding/elasticsearch/secure/deployment.yaml
  testdata/logging/logforwarding/fluentd/insecure/fluentdserver_deployment.yaml
  testdata/logging/logforwarding/fluentd/secure/fluentdserver_deployment.yaml
  testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_deployment.yaml
  testdata/logging/loggen/container_json_log_template.json
  testdata/logging/loggen/container_json_unicode_log_template.json
Labels: approved, lgtm

#1014 Update image to pull from quay.io/openshifttest
  testdata/deployment/skopeo-deployment.json
  testdata/image/gitserver/gitserver-ephemeral.yaml
  testdata/templates/tc539699/build.yaml
Labels: approved, lgtm

#1010 Making more readable clone machineset step
  features/machine/autoscaler.feature
  features/machine/machine.feature
  features/machine/machine_healthcheck.feature
  features/step_definitions/machine_set.rb
  features/upgrade/machines/machines.feature
Labels: approved, lgtm

#1021 add test files for OCP-29198
  testdata/olm/catalogsource-template.yaml
Labels: approved, lgtm

#1023 update routing images to use quay
  testdata/routing/abrouting/caddy-docker-2.json
  testdata/routing/abrouting/caddy-docker.json
  testdata/routing/caddy-docker-2.json
  testdata/routing/caddy-docker.json
  testdata/routing/header-test/dc.json
  testdata/routing/list_for_caddy.json
  testdata/routing/routetimeout/httpbin-pod-2.json
  testdata/routing/routetimeout/httpbin-pod.json
  testdata/routing/websocket/pod.json
  testdata/routing/wildcard_route/caddy-docker.json
Labels: approved, lgtm

#1007 update for proxy failure
  features/cli/oc_portforward.feature
Labels: approved, lgtm

#1022 Update image registry to quay.io for sdn
  testdata/networking/aosqe-pod-for-ping.json
  testdata/networking/hostnetwork-pod.json
  testdata/networking/list_for_pods.json
  testdata/networking/multus-cni/Pods/1interface-host-device.yaml
  testdata/networking/multus-cni/Pods/1interface-macvlan-bridge.yaml
  testdata/networking/multus-cni/Pods/1interface-macvlan-private.yaml
  testdata/networking/multus-cni/Pods/1interface-macvlan-vepa.yaml
  testdata/networking/multus-cni/Pods/2interface-hostdevice-hostdevice.yaml
  testdata/networking/multus-cni/Pods/2interface-macvlan-hostdevice.yaml
  testdata/networking/multus-cni/Pods/2interface-macvlan-macvlan.yaml
  testdata/networking/multus-cni/Pods/IPv6/1interface-macvlan-bridge-v6.yaml
  testdata/networking/multus-cni/Pods/generic_multus_pod.yaml
  testdata/networking/multus-cni/Pods/multus-default-route-pod.yaml
  testdata/networking/multus-cni/Pods/runtimeconfig-pod-ip.yaml
  testdata/networking/multus-cni/Pods/runtimeconfig-pod-ipandmac.yaml
  testdata/networking/multus-cni/Pods/runtimeconfig-pod-mac.yaml
  testdata/networking/net_admin_cap_pod.yaml
  testdata/networking/nodeport_pod.json
  testdata/networking/pod-for-ping.json
  testdata/networking/pod_with_udp_port_4789.json
  testdata/networking/pod_with_udp_port_4789_nodename.json
Labels: approved, lgtm

#995 Fix OCP-25915 OCP-24489 OCP-28518
  features/networking/multus.feature
Labels: approved, lgtm

#996 Auto OCP-24305
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/style.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/style.xyaml
Labels: approved, lgtm

#1020 Add: automate upgrade case OCP-23501
  features/upgrade/storage/upgrade.feature
  testdata/storage/misc/deployment.yaml
Labels: approved, lgtm

#908 Automated OCP-21926
  features/cli/oc_registry.feature
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#1025 Print out all of the actual tried paths
  features/step_definitions/file.rb
Labels: CoreAutomation, approved, lgtm

#1017 step to fetch ERB from URL is invalid due to change of location of th…
  features/step_definitions/cli.rb
  features/step_definitions/helper_services.rb
  features/step_definitions/logging_metrics.rb
Labels: approved, lgtm

#1012 update steps to match logging 4.5
  features/logging/cluster_logging_operator.feature
  features/logging/collector.feature
  features/logging/elasticsearch.feature
  features/logging/elasticsearch_operator.feature
  features/step_definitions/logging.rb
  features/support/clusterlogging_env.rb
  features/test/logging_metrics.feature
  lib/openshift/cluster_logging.rb
  testdata/logging/clusterlogging/example_indexmanagement.yaml
Labels: approved, lgtm

#1026 matches not 'matchs'
  features/step_definitions/operators.rb
  features/upgrade/marketplace/upgrade.feature
  features/upgrade/olm/upgrade.feature
  features/upgrade/storage/upgrade.feature
  features/upgrade/svcat/upgrade.feature
Labels: approved, lgtm

#913 add lib for oc extension plugin
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#1009 fix OCP-27654
  lib/rules/web/admin_console/4.5/masthead.xyaml
Labels: approved, lgtm

#1006 Auto upgrade OCP-22707
  features/upgrade/sdn/policy-upgrade.feature
Labels: approved, lgtm

#1028 add image option for debug command
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#1029 add permanent image as default value
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#1032 fix issue for logging 4.1
  features/logging/collector.feature
Labels: approved, lgtm

#1034 oc policy can-i is deprecated
  lib/openshift/project.rb
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#1030 Now the test images are synced to quay.io, so updated the images
  features/cli/oc_volume.feature
  features/storage/security.feature
  lib/rules/cli/4.1.yaml
  testdata/storage/cinder/cinder-pod.yaml
  testdata/storage/gce/pod.json
  testdata/storage/hostpath/pod.yaml
  testdata/storage/iscsi/pod-security.json
  testdata/storage/misc/pod.yaml
  testdata/storage/nfs/security/pod-supplementalgroup.json
  testdata/storage/secret/secret-pod-test.json
Labels: approved, lgtm

#997 fix IPI abort test
  features/step_definitions/machine.rb
  features/step_definitions/machine_set.rb
Labels: lgtm
