Repository openshift/verification-tests, pull requests merged in 2020-10, with the labels that each got.

#1581 Add rules for oc diff
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1583 OCP-23609-fix - e2e ci failure fix.
  lib/rules/web/admin_console/4.2/overview.xyaml
  lib/rules/web/admin_console/4.3/overview.xyaml
  lib/rules/web/admin_console/4.4/overview.xyaml
  lib/rules/web/admin_console/4.5/overview.xyaml
  lib/rules/web/admin_console/4.6/overview.xyaml
Labels: approved, lgtm

#1580 rules for OCP-33716
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
Labels: approved, lgtm

#1588 rules update
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.6/dashboards.xyaml
  lib/rules/web/admin_console/4.6/logs.xyaml
  lib/rules/web/admin_console/4.6/node.xyaml
  lib/rules/web/admin_console/4.6/user_management.xyaml
Labels: approved, lgtm

#1587 OVN: grep for port in list logical_switch_port
  features/networking/ovn.feature
Labels: approved, lgtm

#1589 update clusterlogforwarder to namespaced resource
  features/logging/cluster_log_forwarder.feature
  lib/openshift/cluster_log_forwarder.rb
  testdata/logging/clusterlogforwarder/multiple_receiver/clusterlogforwarder.yaml
  testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_configmap.yaml
Labels: approved, lgtm

#1582 Defaulting machinset values in vsphere cluster
  features/machine/machine.feature
  lib/openshift/machine.rb
  testdata/cloud/ms-vsphere/ms_default_values.yaml
Labels: approved, lgtm

#1567 add resource type "kubeletconfig"
  lib/openshift/kubelet_config.rb
Labels: approved, lgtm

#1591 update nodeport cases with localhost access
  features/networking/service.feature
Labels: approved, lgtm

#1593 add upi gcp automation test
  features/machine/upi_gcp.feature
  features/step_definitions/machine.rb
Labels: approved, lgtm

#1592 Use available tag for OCP-29693 and OCP-29693
  features/registry/registry.feature
Labels: approved, lgtm

#1596 Fix OVN tests: namespace, expect grep fail, pod(0) references
  features/networking/ovn.feature
Labels: approved, lgtm

#1586 OCP-34940 - test vsphere credential changes gets reflected
  features/machine/machine_misc.feature
  testdata/cloud/misc/PVC.yaml
  testdata/cloud/misc/nginx-pod.yaml
  testdata/cloud/misc/vsphere-creds_test.yaml
Labels: approved, lgtm

#807 Add option for remote selenium URL
  config/config.yaml
  doc/configuration.adoc
  features/step_definitions/web.rb
  lib/webauto/web4cucumber.rb
  lib/webauto/webconsole_executor.rb
Labels: approved, lgtm, lifecycle/stale

#1602 Finish rules for creation page automation of OCM for OCP-29669 and OCP-23526
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_detail_monitoring_tab.xyaml
  lib/rules/web/ocm_console/cluster_detail_networking_tab.xyaml
  lib/rules/web/ocm_console/cluster_detail_overview_tab.xyaml
  lib/rules/web/ocm_console/cluster_list_page.xyaml
  lib/rules/web/ocm_console/ocm_workflow.xyaml
  lib/rules/web/ocm_console/osd_creation_page.xyaml
  lib/rules/web/ocm_console/register_disconnected_cluster_page.xyaml
Labels: approved, lgtm

#1601 update the 300 to 600 second
  features/networking/service.feature
Labels: approved, lgtm

#1594 Fix test as it fails with ocp4.3
  features/upgrade/workloads/scheduler-upgrade.feature
Labels: approved, lgtm

#1605 MTU case fix
  features/networking/service.feature
Labels: lgtm

#1604 Fix type CredentialsRequest issue
  lib/openshift/credentials_request.rb
Labels: approved, lgtm

#1606 Fix frequent error for case OCP-12765
  features/cli/oc_import_image.feature
Labels: approved, lgtm

#1035 OCP-24488: debug VLAN errors by dumping info before
  features/networking/multus.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1595 Auto
  features/step_definitions/metering.rb
  lib/openshift/application.rb
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/monitoring.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/monitoring.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/monitoring.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/logs.xyaml
  lib/rules/web/admin_console/4.6/monitoring.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
  lib/rules/web/admin_console/4.6/route.xyaml
Labels: approved, lgtm

#1610 update test ingresscontroller to use NodePort instead of HostNetwork
  testdata/routing/operator/ingressctl-nsowner.yaml
Labels: approved, lgtm

#1611 update the nodeport pod and service with separate file
  features/networking/service.feature
  testdata/networking/nodeport_test_pod.yaml
  testdata/networking/nodeport_test_service.yaml
Labels: approved, lgtm

#1618 OCP-25787 quick fix
  features/networking/sdn.feature
Labels: approved, lgtm

#1612 OCP-24488: Fix for RHEL7 workers
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1608 automate 4 test cases
  features/step_definitions/pod.rb
  lib/openshift/pod.rb
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1617 update the image with new build
  testdata/networking/aosqe-pod-for-ping.json
  testdata/networking/generic_test_pod_with_replica.yaml
  testdata/networking/hostnetwork-pod.json
  testdata/networking/list_for_pods.json
  testdata/networking/nodeport_pod.json
  testdata/networking/nodeport_test_pod.yaml
  testdata/networking/pod-for-ping.json
  testdata/networking/pod_with_udp_port_4789.json
  testdata/networking/pod_with_udp_port_4789_nodename.json
Labels: approved, lgtm

#1620 Fix resource type MachineHealthCheck
  features/machine/machine_healthcheck.feature
  lib/openshift/machine_health_check.rb
Labels: approved, lgtm

#1623 update smoke tag for network edge cases
  features/routing/haproxy-router.feature
  features/routing/idle.feature
  features/routing/route.feature
Labels: approved, lgtm

#1613 rules added for OCP-28832
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
Labels: approved, lgtm

#1625 support getting AWS ARN and re-enable jenkins gem
  lib/launchers/amz.rb
  tools/Gemfile
Labels: approved, lgtm
