Repository openshift/verification-tests, pull requests merged in 2020-03, with the labels that each got.

#749 No need to not annotate machine after version 4.4
  features/step_definitions/machine_healthcheck.rb
Labels: approved, lgtm, size/S

#750 fix issue when credentials do not come from env variable
  lib/launchers/dyn/dynect.rb
Labels: size/XS

#746 helper for pr731
  lib/openshift/machine.rb
Labels: approved, lgtm, size/S

#751 Automated OCP-26029
  lib/openshift/image_manifest_vuln.rb
  lib/rules/web/admin_console/4.4/actions.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
Labels: approved, lgtm, size/M

#742 Automate clusterautoscaler test case
  features/machine/autoscaler.feature
  features/step_definitions/machine.rb
  features/step_definitions/machine_set.rb
  lib/openshift/cluster_autoscaler.rb
  lib/openshift/machine_set.rb
Labels: approved, lgtm, size/L

#731 OCP27627
  features/machine/machine.feature
Labels: approved, lgtm, size/XS

#748 Fix the step to get Azure file secret name and key
  features/step_definitions/secrets.rb
Labels: approved, lgtm, size/M

#747 fix warning introducted by PR 733
  lib/openshift/cron_job.rb
  lib/openshift/pod_replicator.rb
Labels: CoreAutomation, approved, size/XS

#758 Enhance machine healthcheck test for 4.3
  features/step_definitions/machine_healthcheck.rb
Labels: lgtm, size/XS

#646 Auto OCP-18995
  features/registry/registry.feature
Labels: lgtm, size/S

#754 Clearer error message when BUSHSLICER_CONFIG "browser" value is bad
  lib/webauto/web4cucumber.rb
Labels: approved, lgtm, size/XS

#756 Add liangxia as approver
  OWNERS
Labels: approved, lgtm, size/S

#728 Auto console case for upgrade
  features/upgrade/web/console-upgrade.feature
Labels: approved, lgtm, size/M

#757 OCP-26089: add step to find OVN Raft leader pod
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/M

#759 Use a cloned machineset to scale up and down
  features/machine/machine.feature
Labels: approved, lgtm, size/S

#762 Replace invalid version 4.0 with 4.1
  features/networking/multus.feature
  features/networking/operator.feature
  features/test/version_compare.feature
Labels: approved, lgtm

#763 Adding support for oc create_deployment
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/S

#768 Add CLI 4.5
  lib/rules/cli/4.5.yaml
  lib/rules/cli/kubectl-4.5.yaml
Labels: approved, lgtm, size/XS

#769 Fix author format
  features/upgrade/web/console-upgrade.feature
Labels: approved, lgtm, size/XS

#770 Adding support for oc create_deployment in 4.4+
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm, size/S

#766 pod-for-ping: switch to OPT_QUOTED
  features/step_definitions/helper_services.rb
Labels: approved, lgtm, size/XS

#771 remove the etcd-operator part from OLM
  features/upgrade/olm/upgrade.feature
Labels: size/M

#761 fix OCP-25762 OCP-25931
  lib/rules/web/admin_console/4.3/users.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/users.xyaml
Labels: approved, lgtm, size/XS

#755 Auto the upgrade of svcat
  features/upgrade/svcat/upgrade.feature
Labels: approved, lgtm, size/M

#734 add CAO cases
  features/machine/autoscaler.feature
Labels: approved, lgtm, size/L

#741 Automated OCP-27654
  lib/rules/web/admin_console/4.4/masthead.xyaml
Labels: approved, lgtm, size/M

#740 Auto OCP-20984
  lib/rules/web/admin_console/4.4/actions.xyaml
  lib/rules/web/admin_console/4.4/overview.xyaml
Labels: approved, lgtm, size/M

#705 update dnsmasq config file
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/XS

#777 Remove adm_diagnostics from 4.x as it is an 3.x command
  features/step_definitions/logging_metrics.rb
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm, size/M

#764 An example for 3rd operator upgrade automation
  features/step_definitions/operators.rb
  features/step_definitions/upgrade/3rd_operator.rb
  features/upgrade/tsb/upgrade.feature
Labels: size/L

#779 Update reviewers for storage
  features/storage/OWNERS
Labels: approved, lgtm, size/XS

#780 Register clean-up automatically
  features/machine/autoscaler.feature
  features/machine/machine.feature
  features/step_definitions/machine_set.rb
Labels: approved, lgtm, size/S

#773 Bug fix for nfs pv check data error
  features/storage/nfs.feature
Labels: approved, lgtm, size/XS

#778 installer in container fixes
  tools/launch_instance.rb
  tools/openshift-ci/Dockerfile.installer-example
  tools/openshift-ci/verification_tests_install_entrypoint.sh
Labels: approved, lgtm, size/XS

#739 add rules for OCP-26734
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/user_management.xyaml
  lib/rules/web/admin_console/4.4/users.xyaml
Labels: approved, lgtm, size/M

#789 Remove adm_registry from 4.x as it is an 3.x command
  features/test/registry.feature
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm, size/M

#790 helper step to close the current browser
  features/step_definitions/web.rb
Labels: approved, lgtm, size/XS

#772 fix OCP-20849 search_image for input_value xpath and search button removed issue
  lib/rules/web/admin_console/4.4/deployment.xyaml
Labels: approved, lgtm, size/S

#788 Automate test case OCP-26311
  features/machine/machine_healthcheck.feature
Labels: approved, lgtm, size/S

#783 allow resizing window for Chrome
  lib/webauto/web4cucumber.rb
Labels: approved, lgtm, size/XS

#782 Helper for PR#752
  lib/openshift/egress_network_policy.rb
Labels: approved, size/XS

#792 Add clusterrolebinding command option
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm, size/XS

#793 Ensure admin tag for NFS server as it needs SCC
  features/step_definitions/helper_services.rb
Labels: approved, lgtm, size/XS

#791 update clone machineset name
  features/machine/autoscaler.feature
Labels: approved, lgtm, size/M

#786 fix web cases
  lib/rules/web/admin_console/4.4/catalog.xyaml
  lib/rules/web/admin_console/4.4/check_links.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/deployment.xyaml
Labels: approved, lgtm, size/S

#752 Auto OCP-13506
  features/networking/egress-ingress.feature
Labels: approved, lgtm, size/M

#797 fix method to ignore garbage from stderr
  lib/host.rb
Labels: approved, lgtm, size/XS

#624 Add service externalIP
  features/networking/service.feature
Labels: approved, lgtm, size/L

#657 Multus Telemetry Adds capability to track usage of network attachment…
  features/networking/multus.feature
Labels: approved, lgtm, size/M

#794 Automate OCP-25734
  features/machine/machine_healthcheck.feature
Labels: approved, lgtm, size/S

#795 Add one rule for OCP-26841
  lib/rules/web/admin_console/4.4/browser_opts.yml
Labels: approved, lgtm, size/XS

#781 rules added for OCP-27901
  lib/rules/web/admin_console/4.1/overview.xyaml
  lib/rules/web/admin_console/4.2/overview.xyaml
  lib/rules/web/admin_console/4.3/overview.xyaml
  lib/rules/web/admin_console/4.4/dashboards.xyaml
  lib/rules/web/admin_console/4.4/overview.xyaml
Labels: approved, lgtm, size/L

#584 OCP-23543 fixes
  features/networking/sdn.feature
Labels: approved, lgtm, size/M

#799 Autoscaler enhancement
  features/machine/autoscaler.feature
  features/step_definitions/machine_set.rb
Labels: approved, lgtm, size/XS

#785 modify the status of upgradeable
  features/upgrade/svcat/upgrade.feature
Labels: lgtm, size/XS

#801 Helper for #745
  features/step_definitions/node.rb
  features/test/node.feature
Labels: approved, lgtm

#802 Fix rule check_binary_data_contains for 4.4
  lib/rules/web/admin_console/4.4/configmap.xyaml
Labels: approved, lgtm

#745 add fips verification tc for upgrade
  features/upgrade/security_compliance/fips.feature
Labels: approved, lgtm, size/M

#803 some rule fixes
  lib/rules/web/admin_console/4.4/user_management.xyaml
Labels: approved, lgtm

#805 Fix OCP-11767
  features/build/buildlogic.feature
Labels: approved, lgtm

#808 Add support to get pod nominatedNodeName
  lib/openshift/pod.rb
Labels: approved, lgtm

#804 Updtae: Fix OCP-11906
  features/cli/oc_volume.feature
Labels: approved, lgtm

#776 OCP27609 - Scaling machineset with PublicIp set to true
  features/machine/machine.feature
Labels: approved, lgtm, size/S

#800 Bug fix for volume attached failed when volume and pod are in different zones
  features/storage/security.feature
Labels: approved, lgtm, size/M

#809 Add support for resource type priority classes
  features/step_definitions/scheduler.rb
  lib/openshift/priority_class.rb
Labels: approved, lgtm

#811 Make time longer
  features/registry/is.feature
Labels: approved, lgtm

#814 Use team repo
  features/networking/pod.feature
  features/step_definitions/upgrade/3rd_operator.rb
  features/upgrade/tsb/upgrade.feature
Labels: approved, lgtm

#612 OCP-21574 and OCP-22504 automated
  features/networking/multus.feature
  features/networking/operator.feature
Labels: approved, lgtm, size/L

#709 add create poddisruptionbudget
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/S

#587 OCP-21846 and OCP-25787
  features/networking/pod.feature
  features/networking/sdn.feature
  features/networking/service.feature
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm, size/L

#753 Add upgrade case
  features/upgrade/build/build-upgrade.feature
Labels: approved, lgtm, size/M

#765 automated OCP-23967
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/yaml.xyaml
Labels: approved, lgtm, size/M

#715 update cases ocp-22202
  features/networking/operator.feature
Labels: approved, lgtm, size/M

#577 Added OCP-26822 (duplicate of OCP-19810) but works on 4.x
  features/networking/pod.feature
Labels: approved, lgtm, size/M

#796 Remove adm_ca from 4.x as it is an 3.x command
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm, size/M

#813 extend time to waiting for logging resources to appear
  features/step_definitions/logging.rb
Labels: approved, lgtm

#787 Hongyali common rules
  lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
Labels: approved, lgtm, size/L

#810 OCP-25856
  features/networking/operator.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm

#815 Fixing autoscaler test flakes
  features/machine/autoscaler.feature
  lib/openshift/machine_set.rb
Labels: approved, lgtm

#819 Fix OCP-20932
  lib/rules/web/admin_console/4.2/overview.xyaml
Labels: approved, lgtm

#822 Modified the func for teardown
  features/step_definitions/scheduler.rb
Labels: approved, lgtm

#817 update idp script
  lib/openshift/o_auth.rb
Labels: approved, lgtm

#818 Fix the path to logging test files
  features/test/logging_metrics.feature
Labels: approved, lgtm

#626 OCP-14354: add steps to restore deleted node from clipboard
  features/step_definitions/node.rb
Labels: approved, lgtm, size/M

#636 OCP-14985: re-create the node after deletion
  features/networking/sdn.feature
Labels: approved, lgtm, size/M

#775 add step to deploy syslog server
  features/step_definitions/logging.rb
Labels: approved, lgtm, size/L

#824 Fix step definition because #ready? returns a hash not a boolean
  features/step_definitions/machine.rb
Labels: approved, lgtm

#687 Auto OCP-11645
  features/networking/service.feature
Labels: approved, lgtm, size/M

#806 Marketplace upgrade test
  features/step_definitions/operators.rb
  features/upgrade/marketplace/upgrade.feature
  lib/openshift/catalog_source_config.rb
  lib/openshift/custom_resource_definition.rb
  lib/world.rb
Labels: lgtm

#825 update for ocp-13032 failed
  features/upgrade/workloads/oc-upgrade.feature
Labels: approved, lgtm

#727 add lib for scheduler cluster CR
  features/step_definitions/scheduler.rb
Labels: approved, lgtm, size/S

#774 auto OCP-23745
  features/machine/autoscaler.feature
Labels: approved, lgtm, size/S

#816 Auto OCP-27495
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
Labels: approved, lgtm

#743 Add rules for OCP-27550
  lib/rules/web/admin_console/3.11/search.xyaml
  lib/rules/web/admin_console/4.0/search.xyaml
  lib/rules/web/admin_console/4.1/search.xyaml
  lib/rules/web/admin_console/4.2/search.xyaml
  lib/rules/web/admin_console/4.3/search.xyaml
  lib/rules/web/admin_console/4.4/filters.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/projects.xyaml
  lib/rules/web/admin_console/4.4/search.xyaml
Labels: approved, lgtm, size/M

#828 fix service_project.exists? race condition
  lib/environment.rb
Labels: approved, lgtm

#829 Add an white space for readability
  features/build/dockerbuild.feature
  features/cli/deploy.feature
  features/cli/oc_set_deployment_hook.feature
  features/cli/oc_set_env.feature
  features/cli/oc_set_probe.feature
  features/cli/resources.feature
  features/cli/rolling_deploy.feature
  features/machine/machine.feature
  features/step_definitions/cli.rb
Labels: approved

#831 Bump up ruby24 to ruby26
  tools/openshift-ci/Dockerfile.centos
Labels: approved, lgtm

#784 Automated OCP-19675
  lib/rules/web/admin_console/4.3/check_links.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/check_links.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
Labels: approved, lgtm, size/M

#827 OCP-25294, OCP-25787 and OCP-26373
  features/networking/pod.feature
  features/networking/sdn.feature
Labels: approved, lgtm

#834 Add arp command to help debug
  features/step_definitions/networking.rb
Labels: approved, lgtm

#836 add some files for logging
  testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_configmap.yaml
  testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_deployment.yaml
  testdata/logging/logforwarding/rsyslog/rsyslogserver_svc.yaml
Labels: approved, lgtm

#830 Add lib to set all workers as unschedulable
  features/step_definitions/node.rb
Labels: approved, lgtm

#833 Automate OCP-25691
  features/machine/machine_healthcheck.feature
Labels: approved, lgtm

#840 [hotfix] Fix vars in step definitions
  features/step_definitions/clouds/azure.rb
  features/step_definitions/cluster_configuration/cluster_config.rb
  features/step_definitions/cluster_configuration/csi.rb
  features/step_definitions/cluster_configuration/localstorage.rb
  features/step_definitions/cluster_configuration/snapshot.rb
  features/step_definitions/helper_services.rb
  features/step_definitions/logging.rb
  features/step_definitions/logging_metrics.rb
  features/step_definitions/machine_healthcheck.rb
  features/step_definitions/metering.rb
  features/step_definitions/networking.rb
  features/step_definitions/pv.rb
  features/step_definitions/route.rb
  features/step_definitions/secrets.rb
  features/step_definitions/upgrade/3rd_operator.rb
  features/step_definitions/upgrade/etcd.rb
Labels: approved

#835 Fix admin/pod.feature after integrate test data
  features/admin/pod.feature
Labels: approved, lgtm

#842 Corrected test case ID and added an extra check
  features/networking/sdn.feature
Labels: approved, lgtm

#845 Fix OCP-13248
  features/routing/route.feature
Labels: approved, lgtm

#848 add hpa_rubyex testfile
  testdata/hpa/hpa_rubyex.yaml
Labels: approved, lgtm

#821 hongyli automate case OCP-28106 verification-tests
  lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
Labels: approved, lgtm

#853 Integrate test data and test scripts (follow up)
  features/machine/autoscaler.feature
  features/machine/machine_healthcheck.feature
  features/networking/pod.feature
  features/networking/service.feature
  features/upgrade/marketplace/upgrade.feature
  testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_configmap.yaml
  testdata/networking/ping_for_pod_containerPort.json
  testdata/networking/pod-for-ping-with-hostport.yml
  testdata/olm/csc-template.yaml
Labels: approved, lgtm

#849 Fix scenarios that use step download a file from
  features/cli/build.feature
  features/cli/policy.feature
Labels: approved, lgtm

#852 Revert "add hpa_rubyex testfile"
  testdata/hpa/hpa_rubyex.yaml
Labels: approved, lgtm

#846 solve comments from Yadan and fix 4 test failures
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
Labels: approved, lgtm

#851 [OSP] add proxy support for private OSP
  lib/launchers/openstack.rb
Labels: approved, lgtm

#843 Fix admin/scc.feature after integrate test data
  features/admin/scc.feature
  testdata/authorization/scc/scc_capabilities.yaml
  testdata/authorization/scc/scc_with_confilict_capabilities.yaml
Labels: approved, lgtm

#838 simplify OCP-22050
  features/logging/elasticsearch.feature
  features/step_definitions/logging.rb
  testdata/logging/clusterlogging/clusterlogging-storage-template.yaml
Labels: approved, lgtm

#596 Auto scripts
  features/registry/registry.feature
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/M

#839 update for failed
  features/cli/secrets.feature
Labels: approved, lgtm

#859 Verify node is drained when machine is deleted
  features/machine/machine_healthcheck.feature
Labels: approved, lgtm

#866 Fixing a step definition impacted by BUSHSLICER_HOME changes
  features/step_definitions/networking.rb
Labels: approved, lgtm

#860 Fix scenarios that use step create over ERB URL
  features/admin/quota.feature
  features/cli/limits.feature
  features/cli/pod.feature
  features/storage/dynamic_provisioning.feature
  features/test/admin.feature
  features/test/containers.feature
  testdata/limits/tc508038/limit.yaml
  testdata/limits/tc508039/limit.yaml
  testdata/limits/tc508040/limit.yaml
  testdata/limits/tc508041/limit.yaml
  testdata/limits/tc508042/limit.yaml
  testdata/limits/tc508043/limit.yaml
  testdata/limits/tc508044/limit.yaml
  testdata/limits/tc508045/limit.yaml
  testdata/limits/tc508046/limit.yaml
  testdata/limits/tc508047/limit.yaml
  testdata/limits/tc508048/limit.yaml
Labels: approved

#847 Fix download file step for route test cases
  features/routing/route.feature
Labels: approved

#870 Shorten the parameters
  features/build/buildconfig.feature
  features/build/buildlogic.feature
  features/build/stibuild.feature
  features/cli/build.feature
  features/routing/rate-limit.feature
  features/routing/wildcard-route.feature
Labels: approved, lgtm

#871 Remove debug step in scenario for OCP-14059
  features/routing/route.feature
Labels: approved, lgtm

#873 modify the wait time for secret
  features/svc-catalog_asb/svc-catalog.feature
Labels: approved, lgtm

#872 Remove debug step in scenario for OCP-24492
  features/networking/multus.feature
Labels: approved, lgtm

#868 Fix step that download file from relative path
  features/cli/policy.feature
  features/test/http.feature
Labels: approved, lgtm

#878 fix the template reference
  features/upgrade/tsb/upgrade.feature
Labels: approved, lgtm

#857 Fix browser exit for invalid session id
  lib/webauto/web4cucumber.rb
Labels: approved, lgtm

#875 Fix step registry with htpasswd
  features/step_definitions/helper_services.rb
Labels: approved, lgtm

#876 add lib for inspect command
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#874 use image digest
  features/support/clusterlogging_env.rb
  testdata/logging/logforwarding/elasticsearch/insecure/deployment.yaml
  testdata/logging/logforwarding/elasticsearch/secure/deployment.yaml
  testdata/logging/logforwarding/fluentd/insecure/fluentdserver_deployment.yaml
  testdata/logging/logforwarding/fluentd/secure/fluentdserver_deployment.yaml
  testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_deployment.yaml
  testdata/logging/loggen/container_json_log_template.json
  testdata/logging/loggen/container_json_unicode_log_template.json
Labels: approved, lgtm

#812 Add prepare for machines upgrade
  features/upgrade/machines/machines.feature
Labels: approved, lgtm

#879 fixes
  lib/base_helper.rb
  lib/host.rb
  lib/iaas/iaas.rb
  lib/launchers/cloud_helper.rb
  lib/launchers/openstack.rb
  lib/launchers/openstack10.rb
  lib/launchers/openstack4.rb
  tools/instance_summary.rb
  tools/launch_instance.rb
Labels: approved, lgtm

#880 backport fixes for v3 branch
  lib/base_helper.rb
  lib/iaas/iaas.rb
  lib/launchers/cloud_helper.rb
  lib/launchers/openstack.rb
  lib/launchers/openstack10.rb
  lib/launchers/openstack4.rb
  tools/launch_instance.rb
Labels: approved, lgtm

#826 4.3 fixes
  lib/rules/web/admin_console/4.3/catalog.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/yaml.xyaml
  lib/rules/web/admin_console/4.4/catalog.xyaml
Labels: approved, lgtm

#884 update the error message
  features/networking/operator.feature
Labels: approved, lgtm

#881 Add create_poddisruptionbudget for 4.4, sync oadm_inspect in 4.1/4.4
  lib/rules/cli/4.1.yaml
  lib/rules/cli/4.4.yaml
Labels: approved, lgtm

#882 Clean-up 3.x CLI rules from master/4.x branch
  lib/rules/cli/3.10.yaml
  lib/rules/cli/3.11.yaml
  lib/rules/cli/3.3.yaml
  lib/rules/cli/3.4.yaml
  lib/rules/cli/3.5.yaml
  lib/rules/cli/3.6.yaml
  lib/rules/cli/3.7.yaml
  lib/rules/cli/3.8.yaml
  lib/rules/cli/3.9.yaml
  lib/rules/cli/apb-3.10.yaml
  lib/rules/cli/apb-3.11.yaml
  lib/rules/cli/apb-3.7.yaml
  lib/rules/cli/apb-3.8.yaml
  lib/rules/cli/apb-3.9.yaml
  lib/rules/cli/apb-4.0.yaml
  lib/rules/cli/kubectl-3.10.yaml
  lib/rules/cli/kubectl-3.11.yaml
  lib/rules/cli/kubectl-4.0.yaml
  lib/rules/cli/kubectl-4.1.yaml
  lib/rules/cli/svcat-3.10.yaml
  lib/rules/cli/svcat-3.11.yaml
  lib/rules/cli/svcat-4.0.yaml
  lib/rules/cli/svcat-4.1.yaml
Labels: approved, lgtm

#885 fix clear issue for OCP-21250
  lib/rules/web/admin_console/4.1/catalog.xyaml
  lib/rules/web/admin_console/4.2/catalog.xyaml
  lib/rules/web/admin_console/4.3/catalog.xyaml
  lib/rules/web/admin_console/4.4/catalog.xyaml
Labels: approved, lgtm

#886 add rules for 4.5
  lib/rules/web/admin_console/4.5/actions.xyaml
  lib/rules/web/admin_console/4.5/browser_opts.yml
  lib/rules/web/admin_console/4.5/builds.xyaml
  lib/rules/web/admin_console/4.5/catalog.xyaml
  lib/rules/web/admin_console/4.5/check_links.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/configmap.xyaml
  lib/rules/web/admin_console/4.5/customizations.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.5/deployment.xyaml
  lib/rules/web/admin_console/4.5/environments.xyaml
  lib/rules/web/admin_console/4.5/explore.xyaml
  lib/rules/web/admin_console/4.5/filters.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/idp.xyaml
  lib/rules/web/admin_console/4.5/imagestream.xyaml
  lib/rules/web/admin_console/4.5/logs.xyaml
  lib/rules/web/admin_console/4.5/machine.xyaml
  lib/rules/web/admin_console/4.5/masthead.xyaml
  lib/rules/web/admin_console/4.5/monitoring.xyaml
  lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.5/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.5/node.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/overview.xyaml
  lib/rules/web/admin_console/4.5/projects.xyaml
  lib/rules/web/admin_console/4.5/quota.xyaml
  lib/rules/web/admin_console/4.5/route.xyaml
  lib/rules/web/admin_console/4.5/search.xyaml
  lib/rules/web/admin_console/4.5/secrets.xyaml
  lib/rules/web/admin_console/4.5/status.xyaml
  lib/rules/web/admin_console/4.5/storage.xyaml
  lib/rules/web/admin_console/4.5/user_management.xyaml
  lib/rules/web/admin_console/4.5/yaml.xyaml
Labels: approved, lgtm

#865 fix OCP-11023
  features/cli/build.feature
  testdata/deployment/skopeo-deployment.json
  testdata/templates/tc539699/build.yaml
Labels: approved, lgtm

#850 update image tag to digest
  testdata/networking/aosqe-pod-for-ping.json
  testdata/networking/hostnetwork-pod.json
  testdata/networking/list_for_pods.json
  testdata/networking/multus-cni/Pods/1interface-host-device.yaml
  testdata/networking/multus-cni/Pods/1interface-macvlan-bridge.yaml
  testdata/networking/multus-cni/Pods/1interface-macvlan-private.yaml
  testdata/networking/multus-cni/Pods/1interface-macvlan-vepa.yaml
  testdata/networking/multus-cni/Pods/2interface-hostdevice-hostdevice.yaml
  testdata/networking/multus-cni/Pods/2interface-macvlan-hostdevice.yaml
  testdata/networking/multus-cni/Pods/2interface-macvlan-macvlan.yaml
  testdata/networking/multus-cni/Pods/generic_multus_pod.yaml
  testdata/networking/multus-cni/Pods/multus-default-route-pod.yaml
  testdata/networking/multus-cni/Pods/runtimeconfig-pod-ip.yaml
  testdata/networking/multus-cni/Pods/runtimeconfig-pod-ipandmac.yaml
  testdata/networking/multus-cni/Pods/runtimeconfig-pod-mac.yaml
  testdata/networking/net_admin_cap_pod.yaml
  testdata/networking/nodeport_pod.json
  testdata/networking/pod-for-ping.json
  testdata/networking/pod_with_udp_port_4789.json
  testdata/networking/pod_with_udp_port_4789_nodename.json
Labels: approved, lgtm

#888 add prepare tag for OCP-25821
  features/upgrade/security_compliance/fips.feature
Labels: approved, lgtm

#887 rules added for fixing OCP-19532
  lib/rules/web/admin_console/4.1/filters.xyaml
  lib/rules/web/admin_console/4.1/search.xyaml
  lib/rules/web/admin_console/4.2/filters.xyaml
  lib/rules/web/admin_console/4.2/search.xyaml
  lib/rules/web/admin_console/4.3/filters.xyaml
  lib/rules/web/admin_console/4.3/search.xyaml
  lib/rules/web/admin_console/4.4/filters.xyaml
  lib/rules/web/admin_console/4.4/search.xyaml
  lib/rules/web/admin_console/4.5/filters.xyaml
  lib/rules/web/admin_console/4.5/search.xyaml
  lib/webauto/web4cucumber.rb
Labels: approved, lgtm

#883 Add rules for OCP-25761
  features/step_definitions/web.rb
  lib/openshift/cluster_version.rb
  lib/rules/web/admin_console/4.3/check_links.xyaml
  lib/rules/web/admin_console/4.4/check_links.xyaml
  lib/rules/web/admin_console/4.5/check_links.xyaml
Labels: approved, lgtm

#869 Automated OCP-19695
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/deployment.xyaml
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/deployment.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/deployment.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/deployment.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/deployment.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  testdata/hpa/hpa_rubyex.yaml
Labels: approved, lgtm
