Repository openshift/verification-tests, pull requests merged in 2020-11, with the labels that each got.

#1614 Reconciliation of MutatingWebhookConfiguration values should happen
  features/machine/machine_misc.feature
  features/step_definitions/deployment.rb
Labels: approved, lgtm

#1619 Add retry for oauth_bearer_token_challenge
  lib/login.rb
Labels: approved, lgtm

#1616 auto OCP-33618
  features/networking/ovn-egress-ip.feature
  features/step_definitions/networking.rb
  lib/openshift/egress_ip.rb
  testdata/networking/ovn-egressip/egressip1.yaml
Labels: approved, lgtm

#1627 Update multicast pod to use quay.io/openshifttest/mcast-pod
  testdata/networking/multicast-rc.json
Labels: approved, lgtm

#1607 Only check sctp module in worker nodes
  features/networking/sctp.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1621 auto ocp-33250
  features/step_definitions/catalog_source.rb
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
Labels: approved, lgtm

#1622 Imageupdate
  testdata/networking/multus-cni/Pods/1interface-host-device.yaml
  testdata/networking/multus-cni/Pods/1interface-macvlan-bridge.yaml
  testdata/networking/multus-cni/Pods/1interface-macvlan-private.yaml
  testdata/networking/multus-cni/Pods/1interface-macvlan-vepa.yaml
  testdata/networking/multus-cni/Pods/2interface-hostdevice-hostdevice.yaml
  testdata/networking/multus-cni/Pods/2interface-macvlan-hostdevice.yaml
  testdata/networking/multus-cni/Pods/2interface-macvlan-macvlan.yaml
  testdata/networking/multus-cni/Pods/IPv6/1interface-macvlan-bridge-v6.yaml
  testdata/networking/multus-cni/Pods/generic_multus_pod.yaml
  testdata/networking/multus-cni/Pods/multus-default-route-pod.yaml
  testdata/networking/multus-cni/Pods/runtimeconfig-pod-ip.yaml
  testdata/networking/multus-cni/Pods/runtimeconfig-pod-ipandmac.yaml
  testdata/networking/multus-cni/Pods/runtimeconfig-pod-mac.yaml
  testdata/networking/net_admin_cap_pod.yaml
Labels: approved, lgtm

#1624 Provision Windows machine on vsphere, default machineset values to cr…
  features/machine/machine.feature
  testdata/cloud/ms-vsphere/ms_default_values.yaml
Labels: approved, lgtm

#820 add automation scenario for logging upgrading
  features/logging/deploy_logging_operators_via_console.feature
  features/step_definitions/logging.rb
  features/upgrade/logging/upgrade.feature
  lib/openshift/cluster_service_version.rb
  lib/rules/web/admin_console/4.4/logging_kibana.xyaml
  lib/rules/web/admin_console/4.5/logging_kibana.xyaml
  testdata/logging/clusterlogging/clusterlogging-storage-template.yaml
Labels: approved, lgtm

#1628 Update egressip curl url to ipecho url
  features/networking/egress-ip.feature
Labels: approved, lgtm

#1629 OCP-24488: fix typo in bridge VLAN check step
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1632 Copy 4.7 rules for web cases
  lib/rules/web/admin_console/4.7/actions.xyaml
  lib/rules/web/admin_console/4.7/browser_opts.yml
  lib/rules/web/admin_console/4.7/builds.xyaml
  lib/rules/web/admin_console/4.7/catalog.xyaml
  lib/rules/web/admin_console/4.7/check_links.xyaml
  lib/rules/web/admin_console/4.7/clustersettings.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/configmap.xyaml
  lib/rules/web/admin_console/4.7/customizations.xyaml
  lib/rules/web/admin_console/4.7/dashboards.xyaml
  lib/rules/web/admin_console/4.7/deployment.xyaml
  lib/rules/web/admin_console/4.7/environments.xyaml
  lib/rules/web/admin_console/4.7/explore.xyaml
  lib/rules/web/admin_console/4.7/external_page.xyaml
  lib/rules/web/admin_console/4.7/filters.xyaml
  lib/rules/web/admin_console/4.7/goto.xyaml
  lib/rules/web/admin_console/4.7/idp.xyaml
  lib/rules/web/admin_console/4.7/imagestream.xyaml
  lib/rules/web/admin_console/4.7/logging_kibana.xyaml
  lib/rules/web/admin_console/4.7/logs.xyaml
  lib/rules/web/admin_console/4.7/machine.xyaml
  lib/rules/web/admin_console/4.7/masthead.xyaml
  lib/rules/web/admin_console/4.7/monitoring.xyaml
  lib/rules/web/admin_console/4.7/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.7/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.7/node.xyaml
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
  lib/rules/web/admin_console/4.7/overview.xyaml
  lib/rules/web/admin_console/4.7/pods.xyaml
  lib/rules/web/admin_console/4.7/projects.xyaml
  lib/rules/web/admin_console/4.7/quota.xyaml
  lib/rules/web/admin_console/4.7/route.xyaml
  lib/rules/web/admin_console/4.7/search.xyaml
  lib/rules/web/admin_console/4.7/secrets.xyaml
  lib/rules/web/admin_console/4.7/status.xyaml
  lib/rules/web/admin_console/4.7/storage.xyaml
  lib/rules/web/admin_console/4.7/style.xyaml
  lib/rules/web/admin_console/4.7/tables.xyaml
  lib/rules/web/admin_console/4.7/user_management.xyaml
  lib/rules/web/admin_console/4.7/yaml.xyaml
Labels: approved, lgtm

#1633 OCP-35454 can run on UPI installation as well , so not needed check f…
  features/machine/machine_misc.feature
Labels: approved, lgtm

#1636 Add CLI 4.8
  lib/rules/cli/4.8.yaml
  lib/rules/cli/kubectl-4.8.yaml
Labels: approved, lgtm

#1634 update ca to another file since there is same name exist
  features/routing/route.feature
  features/step_definitions/helper_services.rb
Labels: approved, lgtm

#1481 Wait for CRD to be running first before createing meteringconfig and do proper cleanup
  features/step_definitions/metering.rb
  features/step_definitions/resources.rb
Labels: approved, lgtm

#1215 OCP-26035: use service.url to generate URL
  features/networking/service.feature
Labels: approved, lgtm

#1635 update rules for case OCP-36102
  lib/rules/web/admin_console/4.5/logging_kibana.xyaml
  lib/rules/web/admin_console/4.6/logging_kibana.xyaml
Labels: approved, lgtm

#1626 add pod monitor resource
  lib/openshift/pod_monitor.rb
Labels: approved, lgtm

#1642 fix cirucular refrence in arg and indentation issue
  lib/openshift/cluster_service_version.rb
Labels: approved, lgtm

#1392 match test case based on absolute path
  lib/polarshift/test_case.rb
Labels: approved, lgtm

#1639 Non ping binaries use case to fix with NET_RAW and supported yamls/json files
  features/networking/multus.feature
  testdata/networking/pod-for-ping-net-raw.json
Labels: approved, lgtm

#1643 update the ip bin path
  features/networking/multus-ipv6.feature
  features/networking/multus.feature
  features/networking/sriov.feature
  features/step_definitions/networking.rb
  testdata/networking/net_admin_cap_pod.yaml
Labels: approved, lgtm

#1648 Added wait_for_tcp for ldap
  features/step_definitions/helper_services.rb
Labels: approved, lgtm

#1645 auto case OCP-36287
  features/networking/sdn.feature
Labels: approved, lgtm

#1637 Update for OCP-28630
  features/upgrade/storage/upgrade.feature
Labels: approved, lgtm

#1650 some rules changes
  lib/rules/web/admin_console/4.4/quota.xyaml
  lib/rules/web/admin_console/4.5/quota.xyaml
  lib/rules/web/admin_console/4.6/quota.xyaml
  lib/rules/web/admin_console/4.7/check_links.xyaml
  lib/rules/web/admin_console/4.7/masthead.xyaml
  lib/rules/web/admin_console/4.7/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
  lib/rules/web/admin_console/4.7/quota.xyaml
Labels: approved, lgtm

#1656 Use proper admin ensures/I ensure
  features/networking/ovn.feature
  features/networking/pod.feature
  features/networking/service.feature
  features/registry/registry.feature
  features/step_definitions/logging.rb
  features/step_definitions/upgrade/etcd.rb
  features/svc-catalog_asb/svc-catalog.feature
  features/upgrade/storage/upgrade.feature
Labels: approved, lgtm

#1654 Skip google-chrome repo if unavailable
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved, lgtm

#1655 accept insecure certs automatically for chrome
  lib/webauto/web4cucumber.rb
Labels: approved, lgtm

#1647 Auto OCP-35341
  features/networking/egress-ingress.feature
  testdata/networking/egressnetworkpolicy/egressnetworkpolicy_1000.yaml
  testdata/networking/egressnetworkpolicy/egressnetworkpolicy_1001.yaml
Labels: approved, lgtm

#1280 add step to get cloudcredential based on the cluster's platform
  features/step_definitions/secrets.rb
  features/test/creds.feature
Labels: approved, lgtm

#1665 replace click_tab with new actions
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
Labels: approved, lgtm

#1658 rules added for OCP-28203
  lib/rules/web/admin_console/4.4/machine.xyaml
  lib/rules/web/admin_console/4.5/machine.xyaml
  lib/rules/web/admin_console/4.6/machine.xyaml
  lib/rules/web/admin_console/4.7/machine.xyaml
Labels: approved, lgtm

#1663 sctp fix no nc file
  features/networking/sctp.feature
Labels: approved, lgtm

#1666 Fix OCP-11695
  features/cli/deploy.feature
Labels: approved, lgtm

#1662 Fix and add multi OCM ui cases
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_detail_support_tab.xyaml
  lib/rules/web/ocm_console/cluster_list_page.xyaml
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
  lib/rules/web/ocm_console/install_page.xyaml
Labels: approved, lgtm

#1669 Clean-up OCP-19875 (test case already removed in Polarion)
  features/logging/cluster_logging_operator.feature
Labels: approved, lgtm

#1670 remove iscsi test
  features/storage/iscsi.feature
Labels: approved, lgtm

#1667 fix rules related with click_one_dropdown_action
  lib/rules/web/admin_console/4.4/actions.xyaml
  lib/rules/web/admin_console/4.4/secrets.xyaml
  lib/rules/web/admin_console/4.5/actions.xyaml
  lib/rules/web/admin_console/4.5/secrets.xyaml
  lib/rules/web/admin_console/4.6/actions.xyaml
  lib/rules/web/admin_console/4.6/secrets.xyaml
  lib/rules/web/admin_console/4.7/actions.xyaml
  lib/rules/web/admin_console/4.7/secrets.xyaml
Labels: approved, lgtm

#1668 Remove trailing whitespace
  features/registry/registry.feature
Labels: approved, lgtm

#1672 add step I wait for the last background process to finish
  features/step_definitions/cli.rb
Labels: approved, lgtm

#1674 PolarShift payload should be JSON
  lib/polarshift/request.rb
Labels: approved, lgtm

#1675 Clean-up script which test case is removed in Polarion
  features/admin/pod.feature
  features/storage/nfs.feature
Labels: approved, lgtm

#1671 added support for testing report exipration parameter
  lib/openshift/report.rb
Labels: approved, lgtm

#1679 Clean-up duplicate case ID
  features/online/notification.feature
  features/online/quota.feature
Labels: approved, lgtm

#1681 proper method name
  lib/test_case_manager.rb
Labels: approved, lgtm

#1682 backports from master to v3 branch
  lib/openshift/resource.rb
  lib/polarshift/request.rb
  lib/test_case_manager.rb
Labels: approved

#1684 Map test case IDs from TCMS to Polarion
  features/cli/event.feature
  features/cli/pod.feature
  features/networking/pod.feature
  features/online/infra.feature
  testdata/pods/ocp10031/pod.json
  testdata/pods/ocp10142/pod_nodeSelector_infra.yaml
  testdata/pods/ocp10208/readiness-probe-exec.yaml
  testdata/pods/ocp10729/pod-supplementalGroups-invalid.yaml
  testdata/pods/ocp10729/pod-supplementalGroups-multi-cotainers.yaml
  testdata/pods/ocp10729/pod-supplementalGroups.yaml
  testdata/pods/ocp10813/hello-pod.json
Labels: approved, lgtm

#1677 update check_resource_details_key_and_value and click_one_operation_i…
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
Labels: approved, lgtm

#1678 Fix error for OCP-12765
  features/cli/oc_import_image.feature
  features/registry/is.feature
Labels: approved, lgtm

#1641 add rule for kibana
  lib/rules/web/admin_console/4.7/logging_kibana.xyaml
Labels: approved, lgtm

#1579 logging dashboard cases
  features/logging/cluster_logging_operator.feature
  features/logging/elasticsearch_operator.feature
  features/support/clusterlogging_env.rb
  lib/rules/web/admin_console/4.6/dashboards.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.7/dashboards.xyaml
  lib/rules/web/admin_console/4.7/goto.xyaml
Labels: approved, lgtm

#1676 Fix rules20201117
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_detail_access_control_tab.xyaml
  lib/rules/web/ocm_console/cluster_list_page.xyaml
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
  lib/rules/web/ocm_console/dropdown_items.xyaml
Labels: approved, lgtm

#1693 Add pdb
  lib/openshift/pod_disruption_budget.rb
Labels: approved, lgtm

#1692 remove outdated code
  features/logging/deploy_logging_operators_via_console.feature
Labels: approved, lgtm

#1689 replacement of caddy-docker
  features/routing/abrouting.feature
  features/routing/haproxy-router.feature
  features/routing/idle.feature
  features/routing/ingress-route.feature
  features/routing/operator.feature
  features/routing/route.feature
  testdata/routing/abrouting/abtest-websrv1.yaml
  testdata/routing/abrouting/abtest-websrv2.yaml
  testdata/routing/abrouting/abtest-websrv3.yaml
  testdata/routing/abrouting/abtest-websrv4.yaml
  testdata/routing/abrouting/abwithrc_pod1.json
  testdata/routing/abrouting/abwithrc_pod2.json
  testdata/routing/abrouting/abwithrc_pod3.json
  testdata/routing/abrouting/abwithrc_pod4.json
  testdata/routing/abrouting/caddy-docker-2.json
  testdata/routing/abrouting/caddy-docker.json
  testdata/routing/abrouting/reencrypt/service_secure-2.json
  testdata/routing/abrouting/reencrypt/service_secure.json
  testdata/routing/abrouting/unseucre/service_unsecure-2.json
  testdata/routing/abrouting/unseucre/service_unsecure.json
  testdata/routing/service_secure.yaml
  testdata/routing/service_unsecure.yaml
  testdata/routing/web-server-1.yaml
  testdata/routing/web-server-2.yaml
  testdata/routing/web-server-rc.yaml
Labels: approved, lgtm

#1696 fixes JIRA OCPQE-2814
  features/step_definitions/metering.rb
Labels: CoreAutomation, Metering, approved, lgtm

#1691 OCP-37031: OVN handles projects that start with a digit
  features/networking/ovn.feature
  features/step_definitions/project.rb
Labels: approved, lgtm

#1680 fix web rules
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.7/catalog.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/dashboards.xyaml
  lib/rules/web/admin_console/4.7/goto.xyaml
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
Labels: approved, lgtm

#1688 move the OCP-10216 to network path
  features/networking/service.feature
Labels: approved, lgtm

#1653 support kata operator installation and verification.
  features/step_definitions/kata.rb
  features/test/kata.feature
  lib/openshift/kata_config.rb
  testdata/kata/release-4.6/example-fedora.yaml
Labels: approved, lgtm

#1699 Fix case OCP-11762
  features/admin/scc.feature
Labels: approved, lgtm

#1700 Fix the resource mismatch issue between template and scenarios
  features/logging/cluster_logging_operator.feature
Labels: approved, lgtm

#1690 Automated rsyslog clusterlogforwarder test cases: #OCP-33627,32643,32967,32864
  features/logging/cluster_log_forwarder.feature
  testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_RFC3164.yaml
  testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_RFC5424.yaml
  testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_default.yaml
  testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_invalid_values.yaml
  testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_configmap.yaml
Labels: approved, lgtm

#1702 Modifying bridge deletion procedure via network pods
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1703 fix OCP-11903 etc - cookies related cases
  features/routing/haproxy-router.feature
Labels: approved, lgtm

#1704 for older OCP version, the label doesn't have take it out
  features/step_definitions/metering.rb
Labels: approved, lgtm

#1705 Using digest for disconnected
  testdata/pods/pod_with_special_fsGroup.json
Labels: approved, lgtm

#1657 Negative test for Azure Disconnected cluster to not allow publicIp
  features/machine/machine.feature
  testdata/cloud/ms-azure/ms_disconnected_env.yaml
Labels: approved, lgtm

#1644 Auto some ovn egress ip cases
  features/networking/ovn-egress-ip.feature
  features/step_definitions/networking.rb
  testdata/networking/ovn-egressip/egressip2.yaml
  testdata/networking/ovn-egressip/egressip3.yaml
Labels: approved, lgtm

#1698 Update dockerhub to use images in quay.io
  features/registry/registry.feature
Labels: approved, lgtm

#1708 fix web rules
  lib/rules/web/admin_console/4.1/actions.xyaml
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/secrets.xyaml
  lib/rules/web/admin_console/4.2/actions.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/secrets.xyaml
  lib/rules/web/admin_console/4.3/actions.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/secrets.xyaml
  lib/rules/web/admin_console/4.4/actions.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/secrets.xyaml
  lib/rules/web/admin_console/4.5/actions.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/secrets.xyaml
  lib/rules/web/admin_console/4.6/actions.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/secrets.xyaml
  lib/rules/web/admin_console/4.7/actions.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/environments.xyaml
  lib/rules/web/admin_console/4.7/goto.xyaml
  lib/rules/web/admin_console/4.7/overview.xyaml
  lib/rules/web/admin_console/4.7/secrets.xyaml
  lib/rules/web/admin_console/4.7/status.xyaml
  lib/rules/web/admin_console/base/login.xyaml
Labels: approved, lgtm

#1673 try to handle TERM/INT gracefully and generate vminfo.yml
  tools/launch_instance.rb
Labels: approved, lgtm
