Repository openshift/verification-tests, pull requests merged in 2020-01, with the labels that each got.

#561 add rule for OCP-19725
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
Labels: approved, lgtm, size/S

#581 Fix drain
  features/storage/node_operations.feature
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/S

#552 Multus DHCP definitions support and cases
  features/networking/multus.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/L

#565 rules for OCP-25800
  lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.0/actions.xyaml
  lib/rules/web/admin_console/4.1/actions.xyaml
  lib/rules/web/admin_console/4.2/actions.xyaml
  lib/rules/web/admin_console/4.3/actions.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/machine.xyaml
Labels: approved, lgtm, size/M

#580 update time to 200 second
  features/networking/build.feature
Labels: approved, lgtm, size/XS

#567 Fixes in various test cases
  features/networking/multus.feature
  features/networking/operator.feature
  features/networking/pod.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/M

#570 Auto OCP-21812 OCP-15473
  features/networking/egress-ip.feature
Labels: approved, lgtm, size/M

#591 add monitoring alerts/sliences url in console
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
Labels: approved, lgtm, size/S

#579 Update rules for OCP-25763
  lib/rules/cli/4.1.yaml
  lib/rules/web/admin_console/4.3/actions.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/user_management.xyaml
Labels: approved, lgtm, size/S

#583 add rule for OCP-23615
  lib/openshift/template_instance.rb
  lib/rules/web/admin_console/4.2/catalog.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/catalog.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
Labels: approved, lgtm, size/M

#593 Revert part of #PR579
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/XS

#557 Add steps for OCP-26732
  lib/openshift/daemon_set.rb
Labels: approved, lgtm, size/XS

#550 auto OCP-25765
  lib/openshift/package_manifest.rb
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/user_management.xyaml
Labels: approved, lgtm, size/M

#600 (Urgent)duplicated rules for console
  lib/rules/web/admin_console/4.3/goto.xyaml
Labels: approved, lgtm, size/XS

#589 fix for OCP-25792
  lib/rules/web/admin_console/4.3/overview.xyaml
Labels: approved, lgtm, size/S

#578 rules added for OCP-23688
  lib/openshift/machine_autoscaler.rb
  lib/rules/web/admin_console/4.2/actions.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.2/node.xyaml
  lib/rules/web/admin_console/4.3/actions.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/node.xyaml
  lib/rules/web/admin_console/base/login.xyaml
  lib/webauto/web4cucumber.rb
Labels: approved, lgtm, size/L

#597 Sort CLI cmd/options in alphanumeric order
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/L

#551 Update regexp to match new output format.
  features/containers/containers.feature
Labels: approved, lgtm, size/XS

#604 update OCP-11576
  features/cli/hpa.feature
Labels: approved, lgtm, size/XS

#569 rules added for OCP-25762
  lib/rules/web/admin_console/4.3/actions.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/users.xyaml
Labels: approved, lgtm, size/M

#598 some fixes
  lib/rules/web/admin_console/4.3/route.xyaml
Labels: approved, lgtm, size/XS

#605 add rule goto_one_dc_page for 3.11
  lib/rules/web/admin_console/3.11/goto.xyaml
Labels: approved, lgtm, size/XS

#606 Fix CLI format of "oc secrets new"
  features/build/buildlogic.feature
  features/cli/secrets.feature
  features/web/secrets.feature
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/M

#607 Adjusted timeouts to support various releases
  features/networking/operator.feature
Labels: approved, lgtm, size/S

#608 Remove CLI CMD oc_secrets_new_*, replaced by secrets_new_*
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/M

#582 rules for OCP-21111
  lib/rules/web/admin_console/4.1/catalog.xyaml
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.2/catalog.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/catalog.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
Labels: approved, lgtm, size/M

#599 Fix OCP-11171 for stable
  features/web/create.feature
Labels: approved, lgtm, size/XS

#611 turn off more logs
  lib/webauto/web4cucumber.rb
Labels: approved, lgtm, size/XS

#609 Added missing CMD policy in add/remove role/cluster-role
  features/cli/policy.feature
  features/cli/projects.feature
  features/step_definitions/policy.rb
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/M

#576 fix getting router subdomain
  lib/environment.rb
Labels: approved, lgtm, size/S

#494 Automate OCP-24106
  lib/rules/cli/4.1.yaml
  lib/rules/web/admin_console/4.2/catalog.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.3/actions.xyaml
  lib/rules/web/admin_console/4.3/catalog.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
Labels: approved, lgtm, size/L

#614 Remove CLI CMD oadm_add/remove, replaced by oadm_policy_add/remove
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/S

#615 Alert testing for machine-api operators
  features/machine/alerting.feature
Labels: approved, lgtm, size/M

#613 add option api_version for oc explain
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/XS

#617 OCP-25676
  features/networking/multus.feature
Labels: approved, lgtm, size/S

#585 Automate test case OCP-25909
  features/networking/multus.feature
Labels: approved, lgtm, size/M

#603 Use common PVC template to get rid of beta annotations
  features/step_definitions/secrets.rb
Labels: approved, lgtm, size/XS

#601 Auto OCP-15992
  features/networking/egress-ip.feature
Labels: approved, lgtm, size/M

#571 Show pod info when pod not ready
  features/step_definitions/pod.rb
  features/test/pod.feature
Labels: approved, lgtm, size/S

#618 a hot fix for merging resolving conflicts
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
Labels: approved, lgtm, size/XS

#620 Adding machine-approver alerts
  features/machine/alerting.feature
Labels: approved, lgtm, size/S

#594 Automate OCP-26879 till OCP-26884
  features/storage/persistent_volume.feature
Labels: approved, lgtm, size/L

#616 Auto OCP-19133
  features/build/buildlogic.feature
Labels: approved, lgtm, size/M

#625 Small optimizations and fixes found on CI runs
  features/networking/multus.feature
Labels: approved, lgtm

#622 auto upgrade case ocp-13032
  features/upgrade/workloads/oc-upgrade.feature
Labels: approved, lgtm, size/M

#619 Replace obsoleted "oc env" with "oc set env"
  features/cli/deploy.feature
  features/cli/oc_env.feature
  features/cli/oc_set_env.feature
  features/routing/haproxy-router.feature
  features/routing/logging.feature
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/S

#621 update the timeout of few routing cases
  features/routing/haproxy-router.feature
  features/routing/ingress.feature
  features/routing/route.feature
  features/routing/websocket.feature
Labels: approved, lgtm, size/M

#610 Add rules for OCP-24306
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/explore.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
  lib/rules/web/admin_console/4.2/projects.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/explore.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/projects.xyaml
Labels: approved, lgtm, size/L

#515 fix stderr output of shell commands in installer
  lib/local_process.rb
  tools/launch_instance.rb
Labels: approved, do-not-merge/hold, lgtm, size/XS

#516 fix stderr output of shell commands in installer
  lib/local_process.rb
  tools/launch_instance.rb
Labels: approved, do-not-merge/hold, lgtm, size/XS

#545 add methods and lib files for logging cases
  features/step_definitions/logging.rb
  lib/openshift/cluster_logging.rb
  lib/openshift/cron_job.rb
  lib/openshift/deployment.rb
  lib/openshift/elasticsearch.rb
  lib/openshift/log_forwarding.rb
  lib/openshift/prometheus_rule.rb
  lib/rules/web/images/logging/logging.xyaml
Labels: approved, lgtm, size/L

#630 some fixes
  lib/rules/web/admin_console/4.1/check_links.xyaml
  lib/rules/web/admin_console/4.2/catalog.xyaml
  lib/rules/web/admin_console/4.2/check_links.xyaml
  lib/rules/web/admin_console/4.3/catalog.xyaml
  lib/rules/web/admin_console/4.3/check_links.xyaml
  lib/rules/web/admin_console/4.3/operator_hub.xyaml
  lib/rules/web/admin_console/4.3/overview.xyaml
Labels: approved, lgtm, size/M

#642 add get-run for tools
  tools/polarshift.rb
Labels: approved, lgtm, size/S

#641 fix issue when executing case OCP-22492
  features/logging/cluster_logging_operator.feature
Labels: approved, lgtm, size/XS

#643 Fix clone from storage class without parameters
  features/step_definitions/storage_class.rb
Labels: approved, lgtm, size/XS

#566 Auto OCP-18994 and OCP-18998
  features/registry/registry.feature
  features/step_definitions/dc.rb
  features/step_definitions/registry.rb
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/L

#568 Auto OCP-19196 and OCP-16495
  features/registry/is.feature
Labels: approved, lgtm, size/M

#631 Add rules for idp cases
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/idp.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/idp.xyaml
Labels: approved, lgtm, size/L

#590 Update rules: Auto OCP-25802 and update OCP-24287
  features/step_definitions/admin_console.rb
  lib/rules/web/admin_console/4.2/check_links.xyaml
  lib/rules/web/admin_console/4.3/check_links.xyaml
Labels: approved, lgtm, size/M

#629 Rewrite scenarios to be non-destructive
  features/storage/persistent_volume.feature
  features/storage/reclaim_policy.feature
  features/storage/storage_class.feature
Labels: approved, lgtm, size/M

#645 Add rules for idp cases
  lib/rules/web/admin_console/4.2/idp.xyaml
  lib/rules/web/admin_console/4.3/idp.xyaml
Labels: approved, lgtm, size/L

#648 remove dup rule submit_changes, add rule from master to v3 check_page_match
  lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
  lib/rules/web/console/3.11/login.xyaml
  lib/rules/web/console/base/login.xyaml
Labels: approved, lgtm, size/S

#574 fix consoleexternalloglink class
  lib/openshift/console_external_log_link.rb
  lib/openshift/console_external_log_link_console_openshift_io.rb
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
Labels: approved, lgtm, size/S

#654 Fixing OCP-11925,picking a worker node to get unschedulable
  features/admin/pod.feature
Labels: approved, lgtm, size/XS

#638 Few fixes and optimizations
  features/networking/multus.feature
  features/networking/operator.feature
  features/networking/service.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/M

#510 OCM console testing support
  config/config.yaml
  features/step_definitions/ocm/ocm.rb
  lib/bushslicer.rb
  lib/environment.rb
  lib/rules/web/ocm_console/login.xyaml
  lib/user_manager.rb
Labels: approved, lgtm, size/L

#586 Automate test case OCP-25910
  features/networking/multus.feature
Labels: approved, lgtm, size/S

#653 rules added for OCP-21270
  lib/rules/web/admin_console/4.1/overview.xyaml
  lib/rules/web/admin_console/4.2/overview.xyaml
  lib/rules/web/admin_console/4.3/overview.xyaml
Labels: approved, lgtm, size/L

#623 Add multus default route overwrite
  features/networking/multus.feature
Labels: approved, lgtm, size/S

#652 Fix "oc create options"
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/XS

#531 rules for OCP-25793
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/goto.xyaml
Labels: approved, lgtm, size/S

#656 Fixing the issue pods try to get scheduled to master nodes
  features/admin/pod.feature
Labels: approved, lgtm, size/XS

#649 Add 60s waiting to fixing the issues, when hooks pods get into "running" late
  features/cli/deploy.feature
Labels: lgtm, size/S

#628 Add command "oc create user"
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/XS

#563 Added step to store resources in project/cluster to a clipboard
  features/step_definitions/resources.rb
  features/test/rc.feature
  features/test/storage.feature
Labels: approved, lgtm, size/S

#503 added ability to clone a polarion testrun given a testrun id
  tools/polarshift.rb
Labels: CoreAutomation, approved, lgtm, size/L, tools

#651 add dry-run options for 'oc debug' command
  lib/rules/cli/4.1.yaml
Labels: approved, lgtm, size/XS

#661 Changing definition to support mixed nodes
  features/step_definitions/networking.rb
Labels: approved, lgtm, size/S

#647 Remove useless version check in pvc steps
  features/step_definitions/pvc.rb
  features/step_definitions/secrets.rb
Labels: approved, lgtm, size/S

#658 add 4.4 rules for UI team
  lib/rules/web/admin_console/4.4/actions.xyaml
  lib/rules/web/admin_console/4.4/browser_opts.yml
  lib/rules/web/admin_console/4.4/builds.xyaml
  lib/rules/web/admin_console/4.4/catalog.xyaml
  lib/rules/web/admin_console/4.4/check_links.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/configmap.xyaml
  lib/rules/web/admin_console/4.4/customizations.xyaml
  lib/rules/web/admin_console/4.4/deployment.xyaml
  lib/rules/web/admin_console/4.4/environments.xyaml
  lib/rules/web/admin_console/4.4/explore.xyaml
  lib/rules/web/admin_console/4.4/filters.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/idp.xyaml
  lib/rules/web/admin_console/4.4/imagestream.xyaml
  lib/rules/web/admin_console/4.4/logs.xyaml
  lib/rules/web/admin_console/4.4/machine.xyaml
  lib/rules/web/admin_console/4.4/monitoring.xyaml
  lib/rules/web/admin_console/4.4/node.xyaml
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
  lib/rules/web/admin_console/4.4/overview.xyaml
  lib/rules/web/admin_console/4.4/projects.xyaml
  lib/rules/web/admin_console/4.4/quota.xyaml
  lib/rules/web/admin_console/4.4/route.xyaml
  lib/rules/web/admin_console/4.4/secrets.xyaml
  lib/rules/web/admin_console/4.4/status.xyaml
  lib/rules/web/admin_console/4.4/storage.xyaml
  lib/rules/web/admin_console/4.4/user_management.xyaml
  lib/rules/web/admin_console/4.4/users.xyaml
Labels: approved, lgtm, size/XXL
