Repository openshift/verification-tests, pull requests merged in 2021-08, with the labels that each got.

#2163 Fix OCP-33722
  features/build/metrics.feature
  features/images/rhel8_images.feature
Labels: lgtm

#2185 Auto secret volume cases
  features/build/dockerbuild.feature
  features/build/stibuild.feature
Labels: lgtm

#2187 Machine tests needs @admin
  features/machine/machine.feature
Labels: approved, lgtm

#2188 Fix and improve multiple @smoke tests
  features/online/create.feature
  features/online/images.feature
  features/online/sti.feature
  features/storage/add_update_delete_volume.feature
Labels: approved, lgtm

#2190 Remove aged tests
  features/images/jenkins.feature
  features/storage/add_update_delete_volume.feature
Labels: approved, lgtm

#2194 Add parallel_tests gem to support parallel execution in prow
  Gemfile
Labels: approved, lgtm

#2189 OCP-11286: don't restart kubelet to avoid test failures
  features/networking/sdn.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm

#2193 fix for web
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.9/check_links.xyaml
  lib/rules/web/admin_console/4.9/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.9/projects.xyaml
  lib/rules/web/admin_console/4.9/route.xyaml
  lib/rules/web/admin_console/4.9/search.xyaml
Labels: lgtm, approved

#2196 update scheme to tls
  features/logging/cluster_log_forwarder.feature
Labels: lgtm, approved

#2183 fix failure when testing fluentd metric on Logging 5.2
  features/logging/cluster_logging_operator.feature
  features/logging/elasticsearch_operator.feature
  features/logging/logging_acceptance.feature
  lib/openshift/service_monitor.rb
Labels: lgtm, approved

#2186 Update pod image for sctp testing
  testdata/networking/sctp/sctpclient.yaml
  testdata/networking/sctp/sctpserver.yaml
Labels: lgtm, approved

#2177 Make the service-ca upgrade case can be run in disconnected env
  features/upgrade/api_auth/upgrade.feature
Labels: lgtm, approved

#2197 Listen on both IPv4 and IPv6
  testdata/logging/clusterlogforwarder/fluentd/insecure/configmap.yaml
Labels: lgtm, approved

#1900 Auto OCP-38132
  features/networking/ovn.feature
  features/step_definitions/networking.rb
Labels: lgtm, approved

#2192 OCP-41926: view past logs
  lib/rules/web/admin_console/4.8/goto.xyaml
  lib/rules/web/admin_console/4.8/logs.xyaml
  lib/rules/web/admin_console/4.9/goto.xyaml
  lib/rules/web/admin_console/4.9/logs.xyaml
Labels: lgtm, approved

#2202 Update dockerfile to fit with prow CI
  tools/openshift-ci/Dockerfile
Labels: lgtm, approved

#2199 update 49 rules
  lib/rules/web/admin_console/4.5/check_links.xyaml
  lib/rules/web/admin_console/4.6/check_links.xyaml
  lib/rules/web/admin_console/4.6/clustersettings.xyaml
  lib/rules/web/admin_console/4.7/check_links.xyaml
  lib/rules/web/admin_console/4.7/clustersettings.xyaml
  lib/rules/web/admin_console/4.7/dashboards.xyaml
  lib/rules/web/admin_console/4.8/check_links.xyaml
  lib/rules/web/admin_console/4.8/clustersettings.xyaml
  lib/rules/web/admin_console/4.8/dashboards.xyaml
  lib/rules/web/admin_console/4.9/actions.xyaml
  lib/rules/web/admin_console/4.9/check_links.xyaml
  lib/rules/web/admin_console/4.9/clustersettings.xyaml
  lib/rules/web/admin_console/4.9/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.9/dashboards.xyaml
Labels: lgtm, approved

#2203 Allow writing to create Gemfile.lock
  tools/openshift-ci/Dockerfile
Labels: lgtm, approved

#2205 change Monitoring to Observe for 4.9 due to change
  lib/rules/web/admin_console/4.9/monitoring_metrics.xyaml
Labels: lgtm, approved

#2201 Removed inactive cases , they were failing
  features/machine/alerting.feature
Labels: lgtm, approved

#2207 update idp common rules
  lib/rules/web/admin_console/4.9/common_ui_elements.xyaml
Labels: lgtm, approved

#2208 update support rules
  lib/openshift/anzo.rb
  lib/openshift/subscription.rb
Labels: lgtm, approved

#2210 update for automation case 4.5-4.8
  lib/rules/web/admin_console/4.5/check_links.xyaml
  lib/rules/web/admin_console/4.6/check_links.xyaml
  lib/rules/web/admin_console/4.6/clustersettings.xyaml
  lib/rules/web/admin_console/4.7/check_links.xyaml
  lib/rules/web/admin_console/4.7/clustersettings.xyaml
  lib/rules/web/admin_console/4.7/dashboards.xyaml
  lib/rules/web/admin_console/4.8/check_links.xyaml
  lib/rules/web/admin_console/4.8/clustersettings.xyaml
  lib/rules/web/admin_console/4.8/dashboards.xyaml
Labels: lgtm, approved

#2211 Implement tools to add tags to scenario
  tools/case_id_splitter.rb
Labels: lgtm, approved

#2213 adding @inactive to deactivated test cases
  features/admin/pod.feature
  features/admin/quota.feature
  features/build/buildconfig.feature
  features/build/dockerbuild.feature
  features/cli/build.feature
  features/cli/configmap.feature
  features/cli/deploy.feature
  features/cli/downwardapi.feature
  features/cli/event.feature
  features/cli/job.feature
  features/cli/limits.feature
  features/cli/oc_delete.feature
  features/cli/oc_help.feature
  features/cli/oc_import_image.feature
  features/cli/pod.feature
  features/cli/rolling_deploy.feature
  features/images/rhel8_images.feature
  features/infrastructure/scheduler.feature
  features/logging/cluster_logging_operator.feature
  features/networking/build.feature
  features/networking/multus-ipv6.feature
  features/networking/ovn_ipsec.feature
  features/networking/pod.feature
  features/networking/sdn.feature
  features/networking/service.feature
  features/networking/sriov.feature
  features/node/node.feature
  features/node/seccomp.feature
  features/online/create.feature
  features/online/notification.feature
  features/quickstarts/quickstarts.feature
  features/service_catalog_tsb/tsb.feature
  features/storage/cloud_provider.feature
  features/storage/local-storage-operator.feature
  features/storage/persistent_volume.feature
  features/svc-catalog_asb/apb-update.feature
  features/svc-catalog_asb/asb.feature
  features/svc-catalog_asb/svc-catalog.feature
  features/upgrade/api_auth/upgrade.feature
  features/upgrade/samples_operator/upgrade.feature
  features/upgrade/svcat/upgrade.feature
  features/upgrade/tsb/upgrade.feature
Labels: lgtm, approved

#2212 Finish the osd cluster creation part with new wizard in OCM
  lib/rules/web/ocm_console/cluster_detail_monitoring_tab.xyaml
  lib/rules/web/ocm_console/cluster_detail_networking_tab.xyaml
  lib/rules/web/ocm_console/cluster_detail_overview_tab.xyaml
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
  lib/rules/web/ocm_console/ocm_workflow.xyaml
  lib/rules/web/ocm_console/osd_creation_page.xyaml
  lib/rules/web/ocm_console/osd_wizard.xyaml
  lib/rules/web/ocm_console/osd_wizard_billing_model.xyaml
  lib/rules/web/ocm_console/osd_wizard_cloud_provider.xyaml
  lib/rules/web/ocm_console/osd_wizard_cluster_details.xyaml
  lib/rules/web/ocm_console/osd_wizard_machine_pool.xyaml
  lib/rules/web/ocm_console/osd_wizard_networking.xyaml
  lib/rules/web/ocm_console/osd_wizard_review.xyaml
  lib/rules/web/ocm_console/osd_wizard_updates.xyaml
Labels: lgtm, approved

#2215 fix automation failure for tzhou's cases on 20210820
  lib/rules/web/ocm_console/cluster_list_page.xyaml
  lib/rules/web/ocm_console/install_page.xyaml
  lib/rules/web/ocm_console/subscription_page.xyaml
Labels: lgtm, approved

#2191 Automate upgrade case OCP-34223
  features/upgrade/api_auth/upgrade.feature
Labels: lgtm, approved

#2209 update rules for OCP-33743
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
  lib/rules/web/admin_console/4.9/operator_hub.xyaml
Labels: lgtm, approved

#2218 Add common step for authentication rolls out after config changes
  features/step_definitions/oauth.rb
Labels: lgtm, approved

#2220 Automate case OCP-40665 , BZ-1990432
  features/machine/machine_misc.feature
  testdata/cloud/misc/deployment-40665.yaml
  testdata/cloud/misc/pvc-40665.yaml
Labels: lgtm, approved

#2206 [ONEOCPDEPL-94] Wait until OSD cluster delete finishes
  lib/launchers/o_c_m_cluster.rb
Labels: lgtm, approved, needs-ok-to-test

#2175 Delete generated file (cluster.json) after cluster creation
  lib/launchers/o_c_m_cluster.rb
Labels: lgtm, approved, needs-ok-to-test

#2225 Fix wrong tierN location
  tools/openshift-ci/Dockerfile
Labels: lgtm, approved

#2227 Fix expected output
  features/cli/job.feature
Labels: lgtm, approved

#2226 Ocp 32004 fix
  features/step_definitions/metering.rb
Labels: lgtm, approved

#2228 Add shellyyang1989 as global reviewer
  OWNERS
Labels: lgtm, approved
