Repository openshift/verification-tests, pull requests merged in 2021-03, with the labels that each got.

#1870 add env vars for logging to set catsrc and channel
  features/step_definitions/logging.rb
  features/test/logging_metrics.feature
  lib/environment.rb
Labels: approved, lgtm

#1822 Adding tenant to allocated FIP addresses description
  lib/launchers/openstack.rb
Labels: approved, lgtm, needs-ok-to-test

#1882 add 4.8 on lib/rules/web/admin_console
  lib/rules/web/admin_console/4.8/actions.xyaml
  lib/rules/web/admin_console/4.8/browser_opts.yml
  lib/rules/web/admin_console/4.8/builds.xyaml
  lib/rules/web/admin_console/4.8/catalog.xyaml
  lib/rules/web/admin_console/4.8/check_links.xyaml
  lib/rules/web/admin_console/4.8/clustersettings.xyaml
  lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.8/configmap.xyaml
  lib/rules/web/admin_console/4.8/customizations.xyaml
  lib/rules/web/admin_console/4.8/dashboards.xyaml
  lib/rules/web/admin_console/4.8/deployment.xyaml
  lib/rules/web/admin_console/4.8/environments.xyaml
  lib/rules/web/admin_console/4.8/explore.xyaml
  lib/rules/web/admin_console/4.8/external_page.xyaml
  lib/rules/web/admin_console/4.8/filters.xyaml
  lib/rules/web/admin_console/4.8/goto.xyaml
  lib/rules/web/admin_console/4.8/idp.xyaml
  lib/rules/web/admin_console/4.8/imagestream.xyaml
  lib/rules/web/admin_console/4.8/logging_kibana.xyaml
  lib/rules/web/admin_console/4.8/logs.xyaml
  lib/rules/web/admin_console/4.8/machine.xyaml
  lib/rules/web/admin_console/4.8/masthead.xyaml
  lib/rules/web/admin_console/4.8/monitoring.xyaml
  lib/rules/web/admin_console/4.8/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.8/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.8/node.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/overview.xyaml
  lib/rules/web/admin_console/4.8/pods.xyaml
  lib/rules/web/admin_console/4.8/projects.xyaml
  lib/rules/web/admin_console/4.8/quota.xyaml
  lib/rules/web/admin_console/4.8/route.xyaml
  lib/rules/web/admin_console/4.8/search.xyaml
  lib/rules/web/admin_console/4.8/secrets.xyaml
  lib/rules/web/admin_console/4.8/status.xyaml
  lib/rules/web/admin_console/4.8/storage.xyaml
  lib/rules/web/admin_console/4.8/style.xyaml
  lib/rules/web/admin_console/4.8/tables.xyaml
  lib/rules/web/admin_console/4.8/user_management.xyaml
  lib/rules/web/admin_console/4.8/yaml.xyaml
Labels: approved, lgtm

#1880 New auto OCP-35327,OCP-38889, update OCP-21339,OCP-25189
  lib/rules/web/ocm_console/install_page.xyaml
  lib/rules/web/ocm_console/register_disconnected_cluster_page.xyaml
Labels: approved, lgtm

#1869 add support for OCP-37526
  features/step_definitions/container.rb
  lib/rules/web/admin_console/4.7/pods.xyaml
Labels: approved, lgtm

#1872 update case OCP-22202
  features/networking/operator.feature
Labels: approved, lgtm

#1881 Update iscsi prepare step
  features/step_definitions/helper_services.rb
  testdata/storage/iscsi/iscsi-target.json
  testdata/storage/iscsi/service.json
Labels: approved, lgtm

#1362 Update 9563
  features/cli/deploy.feature
Labels: approved, lgtm, lifecycle/stale

#1879 fix private registry
  features/step_definitions/helper_services.rb
Labels: approved, lgtm

#1884 Update xpath for multi OCM cases
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_detail_support_tab.xyaml
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
  lib/rules/web/ocm_console/install_page.xyaml
Labels: approved, lgtm

#1883 add rules for OCP-36912
  lib/rules/web/admin_console/4.7/dashboards.xyaml
  lib/rules/web/admin_console/4.8/dashboards.xyaml
Labels: approved, lgtm

#1886 fix for 27495
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
Labels: approved, lgtm

#1887 Fix xpath in OCM (#70)
  lib/rules/web/ocm_console/cluster_detail_networking_tab.xyaml
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
  lib/rules/web/ocm_console/dropdown_items.xyaml
  lib/rules/web/ocm_console/osd_creation_page.xyaml
Labels: approved, lgtm

#1874 Introduced FlexyEnvVariable and FlexyEnvFile helper classes
  lib/configuration.rb
Labels: approved, lgtm, needs-ok-to-test, tide/merge-method-squash

#1891 allow metering automation to run with other catalogsrc other than qe-…
  features/step_definitions/catalog_source.rb
  features/step_definitions/metering.rb
  testdata/metering/configs/metering_subscription.yaml
Labels: approved, lgtm

#1890 Replace deprecated call URI::decode with URI::decode_www_from
  tools/launch_instance.rb
Labels: approved, lgtm

#1892 hotfix the decoding fix
  tools/launch_instance.rb
Labels: approved

#1894 Revert the decoding fixes.
  tools/launch_instance.rb
Labels: approved

#1895 fix proxy test in ci agents
  features/node/proxy.feature
Labels: approved, lgtm

#1898 fix some rules
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.5/route.xyaml
  lib/rules/web/admin_console/4.6/dashboards.xyaml
  lib/rules/web/admin_console/4.6/route.xyaml
  lib/rules/web/admin_console/4.7/dashboards.xyaml
  lib/rules/web/admin_console/4.7/route.xyaml
  lib/rules/web/admin_console/4.8/dashboards.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/pods.xyaml
  lib/rules/web/admin_console/4.8/route.xyaml
Labels: approved, lgtm

#1899 added support for localvolumediscoveryresult
  features/step_definitions/local_storage.rb
  features/test/storage.feature
  lib/openshift/flakes/discovered_devices.rb
  lib/openshift/local_volume_discovery.rb
  lib/openshift/local_volume_discovery_result.rb
Labels: approved, lgtm

#1901 fix OCP-25762
  lib/rules/web/admin_console/4.8/user_management.xyaml
Labels: approved, lgtm

#1868 Add func to run commands on host after scenario
  features/step_definitions/node.rb
Labels: approved, lgtm

#1903 update idling cases
  features/routing/OWNERS
  features/routing/idle.feature
Labels: approved, lgtm

#1885 add rule for OCP-34268
  lib/openshift/volume_snapshot.rb
  lib/openshift/volume_snapshot_class.rb
  lib/openshift/volume_snapshot_content.rb
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/storage.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/goto.xyaml
  lib/rules/web/admin_console/4.7/storage.xyaml
  lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.8/goto.xyaml
  lib/rules/web/admin_console/4.8/storage.xyaml
Labels: approved, lgtm

#1853 added case OCP-38468, OCP-36508 and OCP-36509
  features/node/kata/install_uninstall.feature
  features/node/kata/pod.feature
  features/step_definitions/kata.rb
  lib/openshift/flakes/container.rb
  testdata/kata/OCP-38468/pod_with_init_container.yaml
  testdata/kata/OCP-38468/services.yaml
  testdata/kata/release-4.7/catalogsource.yaml
  testdata/kata/release-4.7/deployment.yaml
  testdata/kata/release-4.7/kata_operator_deployment.yaml
  testdata/kata/release-4.7/kata_operatorgroup.yaml
  testdata/kata/release-4.7/kata_subscription.yaml
  testdata/kata/release-4.7/kataconfiguration_v1_kataconfig.yaml
Labels: approved, lgtm

#1907 fix some rules in 4.8
  lib/rules/web/admin_console/4.5/logs.xyaml
  lib/rules/web/admin_console/4.6/logs.xyaml
  lib/rules/web/admin_console/4.7/logs.xyaml
  lib/rules/web/admin_console/4.8/dashboards.xyaml
Labels: approved, lgtm

#1902 files are base64 encoded and better string emulation
  config/config.yaml
  lib/configuration.rb
Labels: approved, lgtm

#1909 fix OCP-11639
  features/networking/egress-ingress.feature
Labels: approved, lgtm

#1906 OCP-20688-Fix the button name by removing space from the front.
  lib/rules/web/admin_console/4.8/logs.xyaml
Labels: approved, lgtm

#1914 Merge OCP-37827 with OCP-30787
  features/storage/csi.feature
Labels: approved, lgtm

#1861 Change storage v3-testfile to verification-tests/testdata
  features/storage/aws.feature
  features/storage/cinder.feature
  features/storage/cloud_provider.feature
  features/storage/dynamic_provisioning.feature
  features/storage/glusterfs.feature
  features/storage/hostpath.feature
  features/storage/nfs.feature
  features/storage/rbd.feature
  features/storage/reclaim_policy.feature
  features/storage/security.feature
  features/storage/storage_class.feature
  features/storage/storage_object_in_use_protection.feature
  features/storage/vsphere.feature
Labels: approved, lgtm

#1911 OCP-25817 fix-the-button-name and taking care of prior versions also
  lib/rules/web/admin_console/4.3/customizations.xyaml
  lib/rules/web/admin_console/4.4/customizations.xyaml
  lib/rules/web/admin_console/4.5/customizations.xyaml
  lib/rules/web/admin_console/4.6/customizations.xyaml
  lib/rules/web/admin_console/4.7/customizations.xyaml
  lib/rules/web/admin_console/4.8/customizations.xyaml
Labels: approved, lgtm

#1916 update ipsec packets with correct match
  features/networking/ovn_ipsec.feature
Labels: approved, lgtm

#1915 update the cniverion to 0.3.1
  features/networking/multus-ipv6.feature
  features/networking/multus.feature
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/IPv6/macvlan-bridge-v6.yaml
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/host-device.yaml
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/ipam-dhcp.yaml
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/ipam-static.yaml
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/macvlan-bridge.yaml
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/macvlan-conf-without-master.yaml
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/macvlan-private.yaml
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/macvlan-vepa.yaml
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/route-override.yaml
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/whereabouts-excludeIP.yaml
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/whereabouts-macvlan.yaml
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/whereabouts-overlapping.yaml
Labels: approved, lgtm

#1912 update apiVersion for the routes
  testdata/routing/edge/route_edge.json
  testdata/routing/reencrypt/reencrypt-without-all-cert.yaml
  testdata/routing/reencrypt/route_reencrypt.json
  testdata/routing/route_withouthost1.json
  testdata/routing/unsecure/route_unsecure.json
  testdata/routing/wildcard_route/route_edge.json
  testdata/routing/wildcard_route/route_pass.json
  testdata/routing/wildcard_route/route_reencrypt.json
Labels: approved, lgtm

#1918 Adding @flaky tag to the frequently failed tests
  features/admin/quota.feature
  features/build/buildlogic.feature
  features/build/dockerbuild.feature
  features/infrastructure/cluster-capacity.feature
  features/logging/cluster_logging_operator.feature
  features/logging/collector.feature
  features/logging/elasticsearch.feature
  features/logging/logging_acceptance.feature
  features/node/proxy.feature
Labels: approved, lgtm

#1910 fix rules for OCP-19817,OCP-25761
  lib/rules/web/admin_console/4.5/check_links.xyaml
  lib/rules/web/admin_console/4.6/check_links.xyaml
  lib/rules/web/admin_console/4.7/check_links.xyaml
  lib/rules/web/admin_console/4.8/check_links.xyaml
Labels: approved, lgtm

#1921 fix step to use cache: false
  features/step_definitions/local_storage.rb
Labels: approved, lgtm

#1922 Update upgrade case id for update-automation
  features/upgrade/storage/upgrade.feature
Labels: approved, lgtm

#1924 auto OCP-37139
  features/machine/machine_healthcheck.feature
Labels: approved, lgtm

#1904 rules added for OCP-39596
  lib/openshift/console_operator.rb
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
Labels: approved, lgtm

#1866 Removed code , which wasnt checking status , would have passed always
  features/machine/machine.feature
  lib/openshift/machine.rb
  testdata/cloud/ms-aws/ms_default_values.yaml
  testdata/cloud/ms-aws/ms_tenancy_dedicated.yaml
Labels: approved, lgtm

#1897 another take at URI::decode modernization
  tools/launch_instance.rb
Labels: approved, lgtm

#1925 Add OCP-39958 and update OCP-29426,OCP-21338,OCP-24973,28142
  lib/rules/web/ocm_console/archived_cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/install_page.xyaml
  lib/rules/web/ocm_console/osd_creation_page.xyaml
Labels: approved, lgtm

#1913 Ocp 24263 fix error sentence
  lib/rules/web/admin_console/4.2/imagestream.xyaml
  lib/rules/web/admin_console/4.3/imagestream.xyaml
  lib/rules/web/admin_console/4.4/imagestream.xyaml
  lib/rules/web/admin_console/4.5/imagestream.xyaml
  lib/rules/web/admin_console/4.6/imagestream.xyaml
  lib/rules/web/admin_console/4.7/imagestream.xyaml
  lib/rules/web/admin_console/4.8/imagestream.xyaml
Labels: approved, lgtm

#1917 update multus judgment in case DESIRED multus still not be updated when node remove
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1928 Fix case ID format
  features/machine/machine.feature
Labels: approved, lgtm

#1843 add cases to test different auth when forwarding logs to fluentd
  features/logging/cluster_log_forwarder.feature
  features/step_definitions/logging.rb
  testdata/logging/clusterlogforwarder/fluentd/secure/clusterlogforwarder.yaml
  testdata/logging/clusterlogforwarder/fluentd/secure/cm-mtls-share.yaml
  testdata/logging/clusterlogforwarder/fluentd/secure/cm-mtls.yaml
  testdata/logging/clusterlogforwarder/fluentd/secure/cm-serverauth-share.yaml
  testdata/logging/clusterlogforwarder/fluentd/secure/cm-serverauth.yaml
  testdata/logging/clusterlogforwarder/multiple_receiver/clusterlogforwarder.yaml
  testdata/logging/logforwarding/fluentd/secure/cm-mtls-share.yaml
  testdata/logging/logforwarding/fluentd/secure/cm-mtls.yaml
  testdata/logging/logforwarding/fluentd/secure/cm-serverauth-share.yaml
  testdata/logging/logforwarding/fluentd/secure/cm-serverauth.yaml
Labels: approved, lgtm

#1927 Disable all repos except several needed ones
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved, lgtm

#1934 add waiting time to make sure case stable
  features/networking/pod.feature
Labels: approved, lgtm

#1937 Add func to check if cluster is SNO
  features/step_definitions/env.rb
Labels: approved, lgtm

#1938 fix web rules
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.6/catalog.xyaml
  lib/rules/web/admin_console/4.6/dashboards.xyaml
  lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.8/storage.xyaml
Labels: approved, lgtm

#1933 Deprecate ruby:2.5
  features/build/buildconfig.feature
  features/build/dockerbuild.feature
  features/build/env.feature
  features/cli/build.feature
  features/cli/create.feature
  features/upgrade/build/build-upgrade.feature
  testdata/build/application-template-stibuild.json
  testdata/build/ruby20rhel7-template-sti.json
Labels: approved, lgtm

#1929 fix web rules
  lib/rules/web/admin_console/4.4/secrets.xyaml
  lib/rules/web/admin_console/4.5/secrets.xyaml
  lib/rules/web/admin_console/4.6/secrets.xyaml
  lib/rules/web/admin_console/4.7/secrets.xyaml
  lib/rules/web/admin_console/4.8/secrets.xyaml
  lib/rules/web/admin_console/4.8/status.xyaml
Labels: approved, lgtm

#1926 OCP-40430 automate the create secret with binary file scenario
  lib/rules/web/admin_console/4.7/secrets.xyaml
  lib/rules/web/admin_console/4.8/secrets.xyaml
  testdata/secrets/secret-binary-file.binary
Labels: approved, lgtm
