Repository openshift/verification-tests, pull requests merged in 2021-02, with the labels that each got.

#1835 Disable all repos by default
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved, lgtm

#1834 Fix pulling image limitation from docker
  features/cli/projects.feature
Labels: approved, lgtm

#1836 Add option skip_if_unavailable to all repos
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved

#1825 Fix OCP-19675
  lib/rules/web/admin_console/4.7/check_links.xyaml
Labels: approved, lgtm

#1830 update for auto-ocp-37363
  features/step_definitions/helper_services.rb
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1837 Remove quotes from conditions
  features/test/apiserver.feature
Labels: approved, lgtm

#1840 Change the pod image to a valid image
  testdata/pods/ocp10031/pod.json
Labels: approved, lgtm

#1839 fix web rules
  lib/rules/web/admin_console/4.7/actions.xyaml
  lib/rules/web/admin_console/4.7/check_links.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/dashboards.xyaml
  lib/rules/web/admin_console/4.7/deployment.xyaml
  lib/rules/web/admin_console/4.7/overview.xyaml
  lib/rules/web/admin_console/4.7/storage.xyaml
Labels: approved, lgtm

#1823 Check two available nodes first for running sctp
  features/networking/sctp.feature
  features/step_definitions/networking.rb
  features/test/sctp.feature
Labels: approved, lgtm

#1841 correct wrong configurations in secure fluentd server
  testdata/logging/clusterlogforwarder/fluentd/secure/configmap.yaml
  testdata/logging/logforwarding/fluentd/secure/configmap.yaml
Labels: approved, lgtm

#1652 ONEOCPDEPL-43: Add support for OSD4
  lib/bushslicer.rb
  lib/http.rb
  lib/launchers/amz.rb
  lib/launchers/o_c_m_cluster.rb
  test/lib/launchers/o_c_m_cluster_test.rb
Labels: approved, lgtm, tide/merge-method-merge

#1838 enhancce OCP-38812 to support private cluster
  features/upgrade/routing/upgrade.feature
  testdata/routing/operator/ingressctl-ns-shards.yaml
Labels: approved, lgtm

#1824 update rules for OCP-25816
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/monitoring.xyaml
  lib/rules/web/admin_console/4.5/monitoring.xyaml
  lib/rules/web/admin_console/4.6/monitoring.xyaml
  lib/rules/web/admin_console/4.7/monitoring.xyaml
Labels: approved, lgtm

#1842 fix OCP-32152
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
Labels: approved, lgtm

#1827 Update rules in OCM due to new change of cluster creation and taints …
  lib/rules/web/ocm_console/cluster_detail_addons_tab.xyaml
  lib/rules/web/ocm_console/cluster_detail_machinepool_tab.xyaml
  lib/rules/web/ocm_console/cluster_detail_networking_tab.xyaml
  lib/rules/web/ocm_console/creation_cards_page.xyaml
  lib/rules/web/ocm_console/osd_creation_page.xyaml
Labels: approved, lgtm

#1844 Kernel#open is deprecated, use URI.open instead...also update the rel…
  tools/find_image.rb
Labels: approved, lgtm

#1845 Fix deleting OSD cluster via OCM
  lib/launchers/o_c_m_cluster.rb
Labels: approved, lgtm

#1846 fix OCP-21772
  lib/rules/web/admin_console/4.7/status.xyaml
Labels: approved, lgtm

#1848 URI.escape is deprecated, replace with encode_www_form_component instead
  features/support/cucu_formatter.rb
Labels: approved, lgtm

#1850 Interruptible instances scaling , mostly by using existing clusteraut…
  features/machine/machine.feature
Labels: approved, lgtm

#1851 Update OCM rules because of the new changes
  lib/rules/web/ocm_console/archived_cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_list_page.xyaml
  lib/rules/web/ocm_console/install_page.xyaml
Labels: approved, lgtm

#1751 Ovn metrics
  features/networking/metrics.feature
Labels: approved, lgtm

#1852 update the eventrouter image to match logging 5.0
  features/step_definitions/logging.rb
Labels: approved, lgtm

#1858 Move this case to be a '@destructive' case
  features/networking/multus.feature
Labels: approved, lgtm

#1854 IPsec automation and supported code
  features/networking/ovn_ipsec.feature
  features/step_definitions/networking.rb
  lib/openshift/network_operator.rb
Labels: approved, lgtm

#1857 add feature for OCP-33402
  features/step_definitions/web.rb
  lib/openshift/cluster_operator.rb
  lib/rules/web/admin_console/4.6/clustersettings.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.7/clustersettings.xyaml
  lib/rules/web/admin_console/4.7/goto.xyaml
Labels: approved, lgtm

#1867 update more time for checking build logs
  features/networking/build.feature
Labels: approved, lgtm

#1865 Debug multus daemonset failures
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1856 remove username and password
  testdata/logging/logforwarding/elasticsearch/secure/configmap.yaml
  testdata/logging/logforwarding/elasticsearch/secure/deployment.yaml
Labels: approved, lgtm

#1864 Add OCP-38887,OCP-38888 and update OCP-21090,OCP-22101,OCP-24973,OCP-25175
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_list_page.xyaml
  lib/rules/web/ocm_console/creation_cards_page.xyaml
  lib/rules/web/ocm_console/install_page.xyaml
Labels: approved, lgtm

#1859 auto some ovn egress ip cases
  features/networking/ovn-egress-ip.feature
Labels: approved, lgtm

#1860 test machine with spec securityProfile encryption at rest as "true"
  features/machine/machine.feature
  testdata/cloud/ms-azure/ms_encrypt_at_rest.yaml
Labels: approved, lgtm

#1873 Update og to org
  features/networking/ovn-egress-ip.feature
  testdata/networking/ovn-egressip/egressip1.yaml
  testdata/networking/ovn-egressip/egressip2.yaml
  testdata/networking/ovn-egressip/egressip3.yaml
Labels: approved, lgtm

#1599 increase service project wait timeout to 60s
  lib/environment.rb
Labels: approved, lgtm, lifecycle/rotten

#1871 Update rules for archive, add-on, cluster creation cases in OCM
  lib/rules/web/ocm_console/archived_clusters.xyaml
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_detail_addons_tab.xyaml
  lib/rules/web/ocm_console/cluster_list_page.xyaml
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
  lib/rules/web/ocm_console/ocm_workflow.xyaml
  lib/rules/web/ocm_console/osd_creation_page.xyaml
Labels: approved, lgtm

#1877 fixes issue 1876
  features/step_definitions/operators.rb
Labels: approved, lgtm
