Repository openshift/verification-tests, pull requests merged in 2021-04, with the labels that each got.

#1812 Use new cronjob names according to BZ1919075
  features/logging/elasticsearch.feature
  features/step_definitions/logging.rb
Labels: approved, lgtm

#1889 Automation of Log_644
  features/logging/cluster_log_forwarder.feature
  testdata/logging/clusterlogforwarder/multiple_receiver/clf_fluent_es.yaml
Labels: approved, lgtm

#1936 Verify the token are encrypted in kibana log
  features/logging/kibana.feature
Labels: lgtm

#1815 Adding RVM info
  README.adoc
Labels: approved, lgtm

#1920 OCP-38751-[Bug 1914284] The namespace networkpolicy for an application is functional post upgrade
  features/step_definitions/networking.rb
  features/upgrade/sdn/policy-upgrade.feature
  testdata/networking/networkpolicy/allow-ns-and-pod.yaml
Labels: approved, lgtm

#1944 added methods to support getting daemon set properties
  lib/openshift/daemon_set.rb
Labels: approved, lgtm

#1896 Automation of LOG-742
  features/logging/cluster_logging_operator.feature
  testdata/logging/clusterlogging/cl_fluentd-buffer.yaml
  testdata/logging/clusterlogging/cl_fluentd-buffer_Invalid.yaml
  testdata/logging/clusterlogging/cl_fluentd-buffer_default.yaml
Labels: approved, lgtm

#1949 Remove OCP-24776 as it's no longer valid
  features/networking/sriov.feature
Labels: approved, lgtm

#1948 Add tag flaky to sync back to polarion
  tools/polarshift.rb
Labels: approved, lgtm

#1945 fix some cases
  lib/openshift/deployment.rb
  lib/rules/web/admin_console/4.4/deployment.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/deployment.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/deployment.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/deployment.xyaml
  lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.8/deployment.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
Labels: approved, lgtm

#1950 Scenario name change to avoid conflict
  features/upgrade/sdn/policy-upgrade.feature
Labels: approved, lgtm

#1951 Modify source build using latest tag, docker build using quay.io images
  features/build/buildconfig.feature
  features/build/dockerbuild.feature
  features/build/env.feature
  features/cli/build.feature
  features/cli/create.feature
  features/registry/is.feature
  features/registry/registry.feature
  features/registry/remote.feature
  testdata/build/application-template-dockerbuild.json
  testdata/build/ruby22rhel7-template-docker.json
  testdata/templates/ocp11552/ruby22rhel7-template-docker.json
  testdata/templates/ocp12041-s2i.json
Labels: approved, lgtm

#1923 Update step `I pick a random machineset to scale`
  features/step_definitions/machine_set.rb
  lib/openshift/machine_set.rb
Labels: lgtm

#1955 Add tool to sync tags back to polarion in batch
  tools/sync_tc_tags_to_polarion.sh
Labels: approved, lgtm

#1935 add upgrade case to test clusterlogforwarder
  features/step_definitions/logging.rb
  features/upgrade/logging/upgrade_with_clf.feature
  lib/openshift/cluster_logging.rb
  lib/openshift/subscription.rb
  testdata/logging/clusterlogforwarder/clf-multiple-external-logstore-template.yaml
Labels: approved, lgtm

#1956 fix web rules
  lib/rules/web/admin_console/4.8/clustersettings.xyaml
  lib/rules/web/admin_console/4.8/goto.xyaml
  lib/rules/web/admin_console/4.8/secrets.xyaml
Labels: approved, lgtm

#1957 remove flack and destructive cases
  features/logging/logging_acceptance.feature
  features/step_definitions/logging.rb
Labels: approved, lgtm

#1953 fix error when there's no CustomField in the original testrun
  tools/polarshift.rb
Labels: approved, lgtm

#1960 Fix small mtu test
  features/networking/service.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm

#1930 add get ipv6 address for pod and service
  features/networking/ipv6_dualstack.feature
  lib/openshift/pod.rb
  lib/openshift/service.rb
  testdata/networking/list_for_pods_ipv6.json
  testdata/networking/networkpolicy/multitenant_policy.yaml
Labels: approved, lgtm

#1961 Update feature owners/reviewers
  features/cli/OWNERS
  features/infrastructure/OWNERS
  features/online/OWNERS
  lib/rules/web/admin_console/OWNERS
Labels: approved, lgtm

#1946 Auto case OCP-40366
  features/build/buildlogic.feature
  features/step_definitions/helper_services.rb
  features/step_definitions/registry.rb
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1932 Automate OCP-40569 Allow enablement/disablement ipsec at runtime
  features/networking/ovn_ipsec.feature
Labels: approved, lgtm, needs-ok-to-test

#1962 Auto OCP-41132 OCP-41179
  features/networking/egress-ingress.feature
  features/networking/sdn.feature
  testdata/networking/ovn-egressfirewall/egressfirewall-policy5.yaml
Labels: approved, lgtm

#1952 Fix scheduler
  features/step_definitions/scheduler.rb
  features/upgrade/workloads/scheduler-upgrade.feature
Labels: approved, lgtm

#1963 update case OCP-25933
  features/networking/sdn.feature
Labels: approved, lgtm

#1965 Fix the automation issue found in aws test
  features/storage/NoDiskConflict.feature
  features/storage/storage_class.feature
Labels: approved, lgtm

#1966 fix failure
  features/logging/collector.feature
Labels: approved, lgtm

#1968 use new supported version 2.6
  testdata/logging/clusterlogforwarder/kafka/amq/04_kafka_my-cluster_amqstreams_template.yaml
Labels: approved, lgtm

#1967 replace upgrade ruby image
  features/upgrade/build/build-upgrade.feature
  testdata/templates/ocp12041-s2i.json
Labels: approved, lgtm

#1969 Customize the function so that it can be used with any CR
  features/step_definitions/scheduler.rb
Labels: approved, lgtm

#1972 fix failures in logging 5.1
  features/logging/OWNERS
  features/logging/elasticsearch.feature
  features/logging/logging_acceptance.feature
  features/step_definitions/logging.rb
  testdata/logging/clusterlogging/cl-storage-with-im-template.yaml
Labels: approved, lgtm

#1954 fix kibana cases
  features/logging/kibana.feature
Labels: approved, lgtm

#1959 fix OCP-28832 OCP-33125
  lib/rules/web/admin_console/4.8/clustersettings.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
Labels: approved, lgtm

#1974 Update OWNERS
  OWNERS
Labels: approved, lgtm

#1973 fix OCP-41179
  features/networking/egress-ingress.feature
Labels: approved, lgtm

#1971 kata automation support for 4.8 release
  features/step_definitions/kata.rb
  features/step_definitions/resources.rb
  lib/openshift/kata_config.rb
  testdata/kata/release-4.8/deployment.yaml
  testdata/kata/release-4.8/kataconfiguration_v1_kataconfig.yaml
Labels: approved, lgtm

#1977 auto OCP-34697
  features/machine/upi_gcp.feature
Labels: approved, lgtm

#1978 Update pv_metering.yaml
  testdata/metering/configs/pv_metering.yaml
Labels: approved, lgtm

#1975 Update multi ocm cases due to new features
  lib/rules/web/ocm_console/install_page.xyaml
  lib/rules/web/ocm_console/osd_creation_page.xyaml
Labels: approved, lgtm

#1970 added support for NFD OLM CLI installation
  features/step_definitions/nfd.rb
Labels: approved, lgtm

#1979 Fix OCP-18962
  features/cli/build.feature
Labels: approved, lgtm

#1981 Add CLI 4.9
  lib/rules/cli/4.9.yaml
  lib/rules/cli/kubectl-4.9.yaml
Labels: approved, lgtm

#1976 Added CLI OLM installation for Kata and other fixes.
  features/node/kata/install_uninstall.feature
  features/step_definitions/kata.rb
  lib/openshift/kata_config.rb
  testdata/kata/catalogsource.yaml
  testdata/kata/example-fedora-kata.yaml
  testdata/kata/namespace.yaml
  testdata/kata/operatorgroup.yaml
  testdata/kata/release-4.7/catalogsource.yaml
  testdata/kata/release-4.7/deployment.yaml
  testdata/kata/release-4.7/kata_operator_deployment.yaml
  testdata/kata/release-4.7/kata_operatorgroup.yaml
  testdata/kata/release-4.7/kata_subscription.yaml
  testdata/kata/release-4.7/kataconfiguration_v1_kataconfig.yaml
  testdata/kata/release-4.8/deployment.yaml
  testdata/kata/subscription.yaml
Labels: approved, lgtm

#1982 Fix multi ocm cases
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_list_page.xyaml
  lib/rules/web/ocm_console/install_page.xyaml
  lib/rules/web/ocm_console/osd_creation_page.xyaml
  lib/rules/web/ocm_console/register_disconnected_cluster_page.xyaml
Labels: approved, lgtm

#1814 report portal support
  Gemfile
  config/cucumber.yml
  features/step_definitions/debug.rb
  features/step_definitions/transform.rb
  features/support/cucu_formatter.rb
  features/support/env.rb
  features/support/save_to_dir_embedding_formatter.rb
  features/test/debug.feature
  features/test/transformations.feature
  lib/log.rb
  lib/manager.rb
  lib/polarshift/scenario_wrapper.rb
  lib/polarshift/test_case.rb
  lib/polarshift/test_record.rb
  lib/polarshift/test_suite.rb
  lib/test_case_manager.rb
  lib/test_case_manager_filter.rb
  lib/world.rb
Labels: approved, lgtm, tide/merge-method-merge

#1984 Opt out the time consuming steps in base image's dockerfile
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved, lgtm

#1985 [hotfix] skip scenario skipping on conflict
  features/support/env.rb
  lib/manager.rb
  lib/polarshift/test_suite.rb
  lib/test_case_manager_filter.rb
Labels: approved, lgtm, tide/merge-method-merge

#1986 [hotfix] for scenario skipping fix
  lib/manager.rb
  tools/openshift-ci/Dockerfile.centos
Labels: approved, lgtm, tide/merge-method-merge
