Repository openshift/verification-tests, pull requests merged in 2021-01, with the labels that each got.

#1772 fix web rules
  lib/rules/web/admin_console/4.3/user_management.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/user_management.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/user_management.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/user_management.xyaml
  lib/rules/web/admin_console/4.7/actions.xyaml
  lib/rules/web/admin_console/4.7/catalog.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/dashboards.xyaml
  lib/rules/web/admin_console/4.7/environments.xyaml
  lib/rules/web/admin_console/4.7/explore.xyaml
  lib/rules/web/admin_console/4.7/node.xyaml
  lib/rules/web/admin_console/4.7/user_management.xyaml
Labels: approved, lgtm

#1765 deploy external log stores in different projects and other fixes
  features/logging/cluster_log_forwarder.feature
  features/step_definitions/logging.rb
  testdata/logging/clusterlogforwarder/elasticsearch/insecure/clusterlogforwarder.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/secure/clusterlogforwarder.yaml
  testdata/logging/clusterlogforwarder/fluentd/insecure/clusterlogforwarder.yaml
  testdata/logging/clusterlogforwarder/fluentd/secure/clusterlogforwarder.yaml
  testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_RFC3164.yaml
  testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_RFC5424.yaml
  testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_default.yaml
Labels: approved, lgtm

#1776 replace image with quay
  features/cli/deploy.feature
Labels: approved, lgtm

#1774 update rules
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/route.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/route.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/route.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/route.xyaml
Labels: approved, lgtm

#1775 Automated cco upgrade test case
  features/upgrade/cloudcredential/upgrade.feature
Labels: approved, lgtm

#1762 Auto OCP-37827
  features/storage/csi.feature
Labels: approved, lgtm

#1777 fix failure when finding the index patterns in kibana
  features/logging/kibana.feature
  lib/rules/web/admin_console/4.7/logging_kibana.xyaml
Labels: approved, lgtm

#1780 Remove trailing white spaces
  features/build/buildconfig.feature
  features/build/buildlogic.feature
  features/build/metrics.feature
  features/build/stibuild.feature
  features/cli/configmap.feature
  features/cli/create.feature
  features/cli/job.feature
  features/cli/oc_import_image.feature
  features/cli/oc_process.feature
  features/cli/oc_registry.feature
  features/cli/oc_set_build_hook.feature
  features/cli/oc_set_deployment_hook.feature
  features/cli/secrets.feature
  features/images/jenkins.feature
  features/images/rhel8_images.feature
  features/logging/collector.feature
  features/logging/elasticsearch.feature
  features/machine/machine.feature
  features/machine/machine_healthcheck.feature
  features/machine/machine_misc.feature
  features/networking/egress-ingress.feature
  features/networking/metrics.feature
  features/networking/multicast.feature
  features/networking/multus-ipv6.feature
  features/networking/operator.feature
  features/networking/ovn_winc.feature
  features/networking/pod.feature
  features/networking/sctp.feature
  features/networking/sriov.feature
  features/online/accountant.feature
  features/online/create.feature
  features/online/imagestreams.feature
  features/online/quota.feature
  features/online/subscription_plan.feature
  features/registry/registry.feature
  features/routing/abrouting.feature
  features/routing/ingress-route.feature
  features/service_catalog_tsb/tsb.feature
  features/storage/csi.feature
  features/storage/security.feature
  features/svc-catalog_asb/apb-update.feature
  features/svc-catalog_asb/asb.feature
  features/svc-catalog_asb/svc-catalog.feature
  features/test/registry.feature
  features/test/sctp.feature
  features/upgrade/cloudcredential/upgrade.feature
  features/upgrade/etcd/upgrade.feature
  features/upgrade/jenkins/upgrade.feature
  features/upgrade/logging/upgrade.feature
  features/upgrade/node/hpa/upgrade.feature
  features/upgrade/node/node-upgrade.feature
  features/upgrade/node/scc.feature
  features/upgrade/routing/upgrade.feature
  features/upgrade/samples_operator/upgrade.feature
  features/upgrade/sdn/policy-upgrade.feature
  features/upgrade/security_compliance/fips.feature
  features/upgrade/storage/upgrade.feature
  features/upgrade/tsb/upgrade.feature
  features/upgrade/web/console-upgrade.feature
  features/upgrade/workloads/oc-upgrade.feature
Labels: approved, lgtm

#1752 do not polute logs too much
  lib/environment.rb
Labels: approved

#1781 do not polute logs too much
  features/step_definitions/policy.rb
Labels: approved

#1734 OCPQE-2773: Create one logging acceptance cases for all cluster
  features/logging/cluster_logging_operator.feature
  features/logging/logging_acceptance.feature
  lib/rules/web/admin_console/4.5/catalog.xyaml
  lib/rules/web/admin_console/4.6/catalog.xyaml
  lib/rules/web/admin_console/4.7/catalog.xyaml
Labels: approved, lgtm

#1706 handle Unable to locate element collection
  lib/webauto/web4cucumber.rb
Labels: approved, lgtm

#1782 revert changes in web4cucumber
  lib/webauto/web4cucumber.rb
Labels: approved, lgtm

#1784 fix ocp-11645
  features/networking/service.feature
Labels: approved, lgtm

#1719 Make sure some conditions of the operator are ready
  features/step_definitions/_constants.rb
  features/step_definitions/operators.rb
  features/test/apiserver.feature
Labels: approved, lgtm

#1785 rename fix for promethues_metrics_data
  features/step_definitions/logging_metrics.rb
  lib/prometheus_metrics_data.rb
Labels: approved, lgtm

#1779 47fix
  features/step_definitions/admin_console.rb
  features/upgrade/web/console-upgrade.feature
  lib/rules/cli/4.4.yaml
  lib/rules/cli/4.5.yaml
  lib/rules/web/admin_console/4.3/goto.xyaml
  lib/rules/web/admin_console/4.3/user_management.xyaml
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/user_management.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/user_management.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/user_management.xyaml
  lib/rules/web/admin_console/4.7/dashboards.xyaml
  lib/rules/web/admin_console/4.7/goto.xyaml
  lib/rules/web/admin_console/4.7/imagestream.xyaml
  lib/rules/web/admin_console/4.7/monitoring.xyaml
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
  lib/rules/web/admin_console/4.7/style.xyaml
  lib/rules/web/admin_console/4.7/user_management.xyaml
Labels: approved, lgtm

#1783 Space issue fixed by dev a extra space was there earlier
  features/machine/machine.feature
Labels: approved, lgtm

#1787 fix rules for OCP-21685 OCP-28661 OCP-23707 OCP-24006
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_idp.xyaml
Labels: approved, lgtm

#1638 Fix scenarioname
  features/upgrade/workloads/scheduler-upgrade.feature
Labels: approved, lgtm

#1789 Use new YAML file for externalip_pod
  features/networking/service.feature
  testdata/networking/externalip_pod.yaml
  testdata/networking/externalip_service1.json
Labels: approved, lgtm

#1786 better testfile copy
  features/step_definitions/file.rb
Labels: approved, lgtm, tide/merge-method-merge

#1793 Fix OCP-11523
  testdata/build/httpd-ex.git/refs/heads/test
  testdata/build/httpd-ex.git/refs/tags/test
Labels: approved, lgtm

#1790 fix failure when deploy operators
  features/step_definitions/logging.rb
Labels: approved, lgtm

#1792 fix web rules
  lib/rules/web/admin_console/4.7/dashboards.xyaml
  lib/rules/web/admin_console/4.7/filters.xyaml
Labels: approved, lgtm

#1795 get vCenter version to telemetry
  features/machine/machine_misc.feature
Labels: approved, lgtm

#1778 Add debug steps for SCTP
  features/test/sctp.feature
Labels: approved, lgtm

#1796 fix web cases
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
Labels: approved, lgtm

#1797 Fix ImagePullBackOff for "I have LDAP service in my project" cases
  features/step_definitions/helper_services.rb
Labels: approved, lgtm

#1798 Stablized some test and fixed some xpaths
  lib/rules/web/admin_console/4.7/monitoring_alerts.xyaml
Labels: approved, lgtm

#1802 hotfix AWS IAM client
  lib/launchers/amz.rb
Labels: approved, lgtm

#1803 backport AWS and Azure changes from master
  Gemfile
  lib/launchers/amz.rb
  lib/launchers/azure.rb
Labels: approved, lgtm

#1801 fix web rules
  lib/rules/web/admin_console/4.3/operator_hub.xyaml
  lib/rules/web/admin_console/4.4/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/dashboards.xyaml
  lib/rules/web/admin_console/4.7/goto.xyaml
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
  lib/rules/web/admin_console/4.7/user_management.xyaml
Labels: approved, lgtm

#1794 Replace docker image
  features/build/buildlogic.feature
Labels: approved, lgtm

#1805 fix OCP-31249
  features/images/rhel8_images.feature
Labels: approved, lgtm

#1806 z-stream fixes
  lib/rules/web/admin_console/4.4/goto.xyaml
  lib/rules/web/admin_console/4.4/overview.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/overview.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/overview.xyaml
Labels: approved, lgtm

#1807 Update rules for machine pool creation in OCM
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_detail_machinepool_tab.xyaml
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
Labels: approved, lgtm

#1800 Modify to use registry.access.redhat.com/rhscl/ruby-22-rhel7:latst ba…
  testdata/build/ruby20rhel7-context-docker.json
Labels: approved, lgtm

#1799 support added for OCP-37098
  lib/openshift/catalog_source.rb
  lib/rules/web/admin_console/4.7/clustersettings.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/goto.xyaml
Labels: approved, lgtm

#1791 Auto some egressfirewall cases for dnsname
  features/networking/egress-ingress.feature
  testdata/networking/ovn-egressfirewall/egressfirewall-policy4.yaml
Labels: approved, lgtm

#1810 rules update
  lib/rules/web/admin_console/4.4/user_management.xyaml
  lib/rules/web/admin_console/4.5/user_management.xyaml
  lib/rules/web/admin_console/4.6/user_management.xyaml
  lib/rules/web/admin_console/4.7/user_management.xyaml
Labels: approved, lgtm

#1816 update rules for OCP-21685 OCP-26823 OCP-26641
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_idp.xyaml
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
Labels: approved, lgtm

#1817 update channel name
  features/logging/cluster_logging_operator.feature
  features/step_definitions/logging.rb
Labels: approved, lgtm

#1788 fix rules for multi ocm cases
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/install_page.xyaml
Labels: approved, lgtm

#1811 Fix case 12144
  features/cli/oc_delete.feature
Labels: approved, lgtm

#1809 Fix upgrade failures
  features/upgrade/workloads/scheduler-upgrade.feature
Labels: approved, lgtm

#1804 Automate OCP-38521 Whereabouts should exclude IPv6 ranges
  features/networking/multus-ipv6.feature
  testdata/networking/multus-cni/Pods/IPv6/ipv6-pod.yaml
Labels: approved, lgtm

#1818 some rule updates
  lib/rules/web/admin_console/4.5/node.xyaml
  lib/rules/web/admin_console/4.6/node.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/goto.xyaml
  lib/rules/web/admin_console/4.7/node.xyaml
Labels: approved, lgtm

#1820 update windows machine template
  features/machine/machine.feature
Labels: approved, lgtm

#1813 Provide AWS credentials as envvar
  lib/launchers/amz.rb
Labels: approved, lgtm, needs-ok-to-test

#1819 auto OCP-38812
  features/upgrade/routing/upgrade.feature
  testdata/routing/operator/ingressctl-ns-shards.yaml
Labels: approved, lgtm

#1821 Fix OCP-24106
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
Labels: approved, lgtm

#1826 Provide AWS credentials as envvar
  lib/launchers/amz.rb
Labels: approved, lgtm, needs-ok-to-test

#1829 replace docker image
  features/cli/serviceaccount.feature
Labels: approved, lgtm

#1831 update rule to make checkbox for monitoring optional
  lib/rules/web/admin_console/4.5/catalog.xyaml
  lib/rules/web/admin_console/4.6/catalog.xyaml
  lib/rules/web/admin_console/4.7/catalog.xyaml
Labels: approved, lgtm
