Repository openshift/verification-tests, pull requests merged in 2021-06, with the labels that each got.

#2052 vpshere version gets changed, ex- as now it is 7.0.1
  features/machine/machine_misc.feature
Labels: approved, lgtm

#2051 Add step to create VolumeSnapshotClass
  features/step_definitions/volume_snapshot.rb
  testdata/storage/snapshot/volumesnapshotclass-aws.yaml
Labels: approved, lgtm

#2053 Add code to remove forcedeploymentreason
  features/step_definitions/scheduler.rb
Labels: approved, lgtm

#2004 Auto case OCP-41789
  features/networking/multus.feature
  testdata/networking/multus-cni/NetworkAttachmentDefinitions/Bug-1944678.yaml
Labels: approved, lgtm, ok-to-test

#1919 [ONEOCPDEPL-10] Added configuration block of environment variables
  config/config.yaml
  doc/configuration.adoc
  tools/launch_instance.rb
Labels: approved, lgtm, needs-ok-to-test

#2059 Add ability to exclude test cases for sync
  tools/sync_tc_tags_to_polarion.sh
Labels: approved, lgtm

#2060 update OCP-18482 to workaround OCPQE-4147
  features/routing/rate-limit.feature
  testdata/routing/routetimeout/edge-service_unsecure.json
  testdata/routing/routetimeout/edge/service_unsecure.json
  testdata/routing/routetimeout/reencrypt/service_secure.json
  testdata/routing/routetimeout/service_secure.json
  testdata/routing/routetimeout/service_unsecure.json
  testdata/routing/routetimeout/unsecure-route.json
  testdata/routing/routetimeout/unsecure-route_unsecure.json
  testdata/routing/routetimeout/unsecure-service_unsecure.json
  testdata/routing/routetimeout/unsecure/service_unsecure.json
Labels: approved, lgtm

#2033 Automate for OCP-27689 and OCP-27690
  features/storage/csi_clone.feature
  testdata/storage/csi/pvc-clone.yaml
Labels: approved, lgtm

#2061 Add localvolume cases into ignore list
  tools/sync_tc_tags_to_polarion.sh
Labels: approved, lgtm

#2062 fix automation error for tzhou's cases
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_detail_support_tab.xyaml
  lib/rules/web/ocm_console/cluster_list_page.xyaml
  lib/rules/web/ocm_console/install_page.xyaml
  lib/rules/web/ocm_console/osd_creation_page.xyaml
  lib/rules/web/ocm_console/subscription_page.xyaml
Labels: approved, lgtm

#2038 rules added for OCP-40405
  lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.8/goto.xyaml
Labels: approved, lgtm

#2063 Add OWNERS file for OCM
  lib/rules/web/ocm_console/OWNERS
Labels: approved, lgtm

#2065 Automate OCP-30315
  features/storage/csi_clone.feature
Labels: approved, lgtm

#2057 update the step to deploy logging pods
  features/logging/elasticsearch.feature
  features/step_definitions/logging.rb
  features/upgrade/logging/upgrade.feature
  testdata/logging/clusterlogging/clusterlogging-storage-template.yaml
Labels: approved, lgtm

#2042 helper step to check for number of replicas for a cluster resource
  features/step_definitions/replicas.rb
Labels: approved, lgtm

#2067 add support for OCP-41056
  lib/rules/web/admin_console/4.8/check_links.xyaml
  testdata/templates/ui/acm-console-link.yaml
Labels: approved, lgtm

#2069 extend timeout for install and uninstall
  features/step_definitions/kata.rb
Labels: approved

#2070 add rules for ocp-40533
  lib/rules/web/admin_console/4.8/actions.xyaml
  lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.8/deployment.xyaml
Labels: approved, lgtm

#2075 allow setting stdin in flexy launcher commands
  .gitignore
  tools/launch_instance.rb
Labels: approved

#2077 fix volume_snapshot readiness check
  lib/openshift/volume_snapshot.rb
Labels: approved, lgtm

#2076 [v3] update pod-for-ping to use image from quay.io
  features/step_definitions/helper_services.rb
Labels: approved, lgtm

#2074 Fix image issues
  features/build/dockerbuild.feature
  features/cli/oc_import_image.feature
Labels: approved, lgtm

#2078 fix missing update of iterations variable.
  lib/openshift/volume_snapshot.rb
Labels: approved, lgtm

#2079 longer kata deletion/installation timeout
  features/step_definitions/kata.rb
Labels: approved, lgtm

#1947 Auto OCP-22490 customize login page
  features/step_definitions/admin_console.rb
  features/step_definitions/cli.rb
  features/step_definitions/oauth.rb
  lib/rules/cli/4.5.yaml
Labels: approved, lgtm

#1996 Add jianli as a global reviewer in verification-tests
  OWNERS
Labels: approved, lgtm

#2068 JIRA OCPQE-3814: Automate the case OCP-39786
  features/logging/cluster_log_forwarder.feature
  testdata/logging/clusterlogforwarder/fluentd/secure/secure-forward-cm.yaml
Labels: approved, lgtm

#2071 Fixing for BZ-1879241
  features/networking/multicast.feature
Labels: approved, lgtm

#2066 fix for web rules
  lib/rules/web/admin_console/4.8/check_links.xyaml
  lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/search.xyaml
  lib/rules/web/admin_console/4.8/storage.xyaml
Labels: approved, lgtm

#1958 fix OCP-34718
  features/machine/machine.feature
Labels: approved, lgtm

#2081 add support for OCP-33656
  lib/base_helper.rb
Labels: approved, lgtm

#2086 Add jhou1 as global approver
  OWNERS
Labels: approved, lgtm

#2085 Automate OCP-27617 and OCP-27686
  features/storage/csi_clone.feature
  testdata/storage/csi/pvc-clone.yaml
Labels: approved, lgtm

#2040 Auto some sdn-1282 EgressIP cases
  features/networking/egress-ip.feature
Labels: approved, lgtm

#2088 Fix resource type for NetworkPolicy
  lib/openshift/network_policy.rb
Labels: approved, lgtm

#2084 a few fixes for kata testing.
  features/step_definitions/kata.rb
  lib/openshift/pod.rb
  testdata/kata/webhook/example-fedora.yaml
Labels: approved, lgtm

#2090 set resource check as false instead of raising exception when 'Unabl…
  lib/openshift/resource.rb
Labels: CoreAutomation, approved, lgtm

#2049 SDN-1340 test case step definition
  features/step_definitions/networking.rb
Labels: approved, lgtm

#2091 Fix nc connection refused issue
  features/networking/sctp.feature
Labels: approved, lgtm

#2095 Auto OSP smoke test case
  features/storage/csi.feature
Labels: approved, lgtm

#2092 fix web rules
  lib/openshift/subscription.rb
  lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.8/dashboards.xyaml
  lib/rules/web/admin_console/4.8/route.xyaml
  lib/rules/web/admin_console/4.8/style.xyaml
Labels: approved, lgtm

#2096 more verbose eval print
  features/step_definitions/common.rb
Labels: approved, lgtm

#2100 Update Storage OWNERS
  features/storage/OWNERS
Labels: approved, lgtm

#2098 Keep dir /var/tmp/ in image cucushift-public
  tools/jenkins/slaves/Dockerfile.rhel7
Labels: approved, lgtm

#2101 formatting changes and use '&&' instead of 'and' for comparison
  features/build/buildlogic.feature
  features/cli/oc_portforward.feature
  features/networking/multus.feature
  features/networking/operator.feature
  features/networking/sdn.feature
Labels: approved, lgtm

#2097 rules updated
  lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.5/dashboards.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.5/node.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/dashboards.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.6/node.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/dashboards.xyaml
  lib/rules/web/admin_console/4.7/goto.xyaml
  lib/rules/web/admin_console/4.7/node.xyaml
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.8/dashboards.xyaml
  lib/rules/web/admin_console/4.8/goto.xyaml
  lib/rules/web/admin_console/4.8/node.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
Labels: approved, lgtm

#2102 add a pre-check for pods running with kata before kataconfig deletion
  features/step_definitions/kata.rb
Labels: approved, lgtm

#2082 update lib for OCP-40533
  lib/openshift/deployment.rb
  lib/openshift/deployment_config.rb
Labels: approved, lgtm

#2089 Hongyli fix 4.8 failure
  lib/rules/web/admin_console/4.8/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.8/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.8/style.xyaml
Labels: approved, lgtm

#2087 Adding wait for log acceptance feature on webconsole validation
  features/logging/logging_acceptance.feature
Labels: approved, lgtm

#2011 update for ocp38262
  lib/rules/web/admin_console/4.7/dashboards.xyaml
  lib/rules/web/admin_console/4.8/dashboards.xyaml
Labels: approved, lgtm

#2064 Auto TC OCP-37479
  features/storage/csi_resize.feature
Labels: approved, lgtm

#2109 Add resize case for OSP and AWS
  features/storage/csi_resize.feature
Labels: approved, lgtm

#2104 Automate OCP-37564/OCP-24546/OCP-24572
  features/storage/csi.feature
Labels: approved, lgtm

#2112 avoid conflict with http gem
  .gitignore
  features/test/transformations.feature
  lib/cucuhttp.rb
  lib/environment.rb
  lib/launchers/alicloud.rb
  lib/launchers/o_c_m_cluster.rb
  lib/launchers/openstack.rb
  lib/login.rb
  lib/ownthat.rb
  lib/platform/master_service.rb
  lib/polarshift/request.rb
  lib/rest_helper.rb
  tools/aws.rb
  tools/cloud_usage.rb
  tools/launch_instance.rb
Labels: approved, lgtm

#2113 Update multicast cases
  features/networking/multicast.feature
Labels: approved, lgtm

#2103 fix some rules
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
  testdata/olm/catalogsource-template.yaml
Labels: approved, lgtm

#2106 Adding test for BZ-1953063
  features/machine/machine.feature
Labels: approved, lgtm

#2108 rewrite the case OCP-25353
  lib/rules/web/ocm_console/subscription_page.xyaml
Labels: approved, lgtm

#2116 fix syntax error
  features/networking/egress-ip.feature
Labels: approved, lgtm

#2120 avoid conflict with http gem
  .gitignore
  lib/cucuhttp.rb
  lib/environment.rb
  lib/launchers/alicloud.rb
  lib/launchers/openstack.rb
  lib/login.rb
  lib/ownthat.rb
  lib/platform/master_service.rb
  lib/polarshift/request.rb
  lib/rest_helper.rb
  tools/aws.rb
  tools/launch_instance.rb
Labels: approved, lgtm

#2125 update channel name
  features/step_definitions/logging.rb
Labels: approved, lgtm

#2115 fix some automation issues
  features/logging/cluster_logging_operator.feature
  features/logging/elasticsearch.feature
  features/logging/elasticsearch_operator.feature
  features/step_definitions/logging.rb
Labels: approved, lgtm

#2118 added support to remove all kata pods in a cluster
  features/step_definitions/kata.rb
  features/test/kata.feature
  lib/openshift/project_resource.rb
Labels: approved, lgtm

#2114 fix destructive rules
  lib/openshift/image_stream.rb
  lib/rules/web/admin_console/4.5/imagestream.xyaml
  lib/rules/web/admin_console/4.6/imagestream.xyaml
  lib/rules/web/admin_console/4.7/imagestream.xyaml
  lib/rules/web/admin_console/4.8/imagestream.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/storage.xyaml
Labels: approved, lgtm

#1878 Fix OCP-22596
  features/build/stibuild.feature
Labels: approved, lgtm, lifecycle/rotten

#2117 Add steps to modify the policy post upgrade to verify it works well
  features/upgrade/sdn/policy-upgrade.feature
Labels: approved, lgtm

#2126 Automate OCP-37557/OCP-34144/OCP-37474
  features/storage/csi.feature
Labels: approved, lgtm

#2127 Change location of policy files to public repo and use multus pod from naster node
  features/step_definitions/networking.rb
  testdata/networking/networkpolicy/allow-from-hostnetwork.yaml
  testdata/networking/networkpolicy/allow-from-router-ingress.yaml
  testdata/networking/networkpolicy/allow-from-router.yaml
Labels: approved, lgtm
