Repository openshift/verification-tests, pull requests merged in 2021-07, with the labels that each got.

#2128 we should skip eval if the expression is a single statement that does…
  features/step_definitions/common.rb
Labels: approved, lgtm

#2130 Chgu working (#3)
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_detail_access_control_tab.xyaml
  lib/rules/web/ocm_console/cluster_idp.xyaml
  lib/rules/web/ocm_console/cluster_list_page.xyaml
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
Labels: approved, lgtm

#2131 Add xueli181114 and yasun1 as OCM approvers
  lib/rules/web/ocm_console/OWNERS
Labels: approved, lgtm

#2136 SA warning prevents , node creation , adding that to default machineset
  features/machine/machine.feature
  lib/openshift/machine.rb
  testdata/cloud/ms-gcp/ms_default_values.yaml
Labels: approved, lgtm

#2137 method `query_test_cases_smart` only accepts 4 parameters `[:project_…
  lib/polarshift/request.rb
Labels: approved, lgtm

#2138 remove rules for ocp38262 for version 4.7
  lib/rules/web/admin_console/4.7/dashboards.xyaml
Labels: approved, lgtm

#2134 OCP-40620 - allow from router and allow from host network policy in upgrade scenario
  features/upgrade/sdn/policy-upgrade.feature
Labels: approved, lgtm

#2132 Fix OCP-33058
  features/machine/machine.feature
Labels: approved, lgtm

#2141 fix string.scan check
  features/step_definitions/common.rb
Labels: approved, lgtm

#2140 fix web rule
  lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.8/dashboards.xyaml
Labels: approved, lgtm

#2142 fix: Error from server (NotFound): namespaces "aos-qe-ci" not found
  features/logging/cluster_logging_operator.feature
  features/step_definitions/logging.rb
Labels: approved, lgtm

#2144 Add tc OCP-37511 and OCP-37478
  features/storage/csi.feature
Labels: approved, lgtm

#2139 Automate OCP-37568/OCP-37569/OCP-27727 and some fix
  features/step_definitions/volume_snapshot.rb
  features/storage/csi_snapshot.feature
  testdata/storage/csi/volumesnapshotclass-aws.yaml
  testdata/storage/csi/volumesnapshotclass-cinder.yaml
Labels: approved, lgtm

#2146 fix failure 'You are not a member of project openshift-marketplace.'
  features/logging/logging_acceptance.feature
Labels: approved, lgtm

#2150 Fix docker.io pull limitation issue for v3
  features/storage/security.feature
Labels: approved, lgtm

#2148 remove the registered 'clean up' from ocm
  lib/rules/web/ocm_console/archived_cluster_detail.xyaml
  lib/rules/web/ocm_console/archived_clusters.xyaml
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
  lib/rules/web/ocm_console/ocm_workflow.xyaml
  lib/rules/web/ocm_console/subscription_page.xyaml
Labels: approved, lgtm

#2151 update rules
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/catalog.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
Labels: approved, lgtm

#2152 Fix the v3 script to use the same args with 4.x
  features/step_definitions/pv.rb
  features/storage/fsType.feature
Labels: lgtm

#2145 fix the node-upgrade project not deleted issue
  features/upgrade/node/hpa/upgrade.feature
Labels: approved, lgtm

#2153 Add dockerfile for unify CI
  tools/openshift-ci/Dockerfile
Labels: approved, lgtm

#2154 AOS -> OCP
  tools/jenkins/slaves/Dockerfile.centos
  tools/jenkins/slaves/Dockerfile.rhel7
  tools/jenkins/slaves/Dockerfile.rhel8
  tools/openshift-ci/Dockerfile
  tools/openshift-ci/Dockerfile.centos
  tools/openshift-ci/Dockerfile.installer-example
Labels: approved, lgtm

#2155 extend timeout for kataconfig deletion
  features/step_definitions/kata.rb
Labels: approved, lgtm

#2149 fix ocp-29198 4.6 rule
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
Labels: approved, lgtm

#2156 Remove smoke tag
  features/storage/persistent_volume.feature
  features/storage/quota.feature
  features/storage/reclaim_policy.feature
Labels: lgtm

#2160 Adding cucushift
  tools/openshift-ci/Dockerfile
Labels: approved, lgtm

#2056 add auto case 41666
  features/networking/pod.feature
  testdata/networking/custom_kubelet.yaml
  testdata/networking/max-pods-without-consume-memory.yaml
Labels: approved, lgtm

#2165 allow user to specify how much information to extract from a test-run
  tools/polarshift.rb
Labels: approved, lgtm

#2166 Add dis016 as global reviewer
  OWNERS
Labels: approved, lgtm

#2167 fix rule for console upgrade case
  lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
Labels: approved, lgtm

#1631 added IB cases
  features/networking/ib-sriov.feature
  features/networking/sriov.feature
  features/step_definitions/sriov.rb
  lib/openshift/sriov_i_b_network.rb
  testdata/networking/sriov/ib/cx4/cx4-ib.yaml
  testdata/networking/sriov/ib/cx4/pod_ib.yaml
  testdata/networking/sriov/ib/cx4/pod_iboip.yaml
  testdata/networking/sriov/ib/cx4/sriovibnetwork-cx4.yaml
  testdata/networking/sriov/ib/cx5/cx5-ib.yaml
  testdata/networking/sriov/ib/cx5/sriovibnetwork-cx5.yaml
  testdata/networking/sriov/ib/cx6/cx6-ib.yaml
  testdata/networking/sriov/ib/cx6/pod-guid.yaml
  testdata/networking/sriov/ib/cx6/sriovibnetwork-cx6.yaml
  testdata/networking/sriov/ib/cx6/sriovibnetwork-static.yaml
Labels: approved, lgtm, lifecycle/rotten

#2170 Adding htpasswd
  tools/openshift-ci/Dockerfile
Labels: approved

#2171 add wait for ldapserver pod Running status
  features/step_definitions/helper_services.rb
Labels: approved, lgtm

#2173 added yamls for kata-4.9 and web rules for 4.9
  lib/rules/web/admin_console/4.9/actions.xyaml
  lib/rules/web/admin_console/4.9/browser_opts.yml
  lib/rules/web/admin_console/4.9/builds.xyaml
  lib/rules/web/admin_console/4.9/catalog.xyaml
  lib/rules/web/admin_console/4.9/check_links.xyaml
  lib/rules/web/admin_console/4.9/clustersettings.xyaml
  lib/rules/web/admin_console/4.9/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.9/configmap.xyaml
  lib/rules/web/admin_console/4.9/customizations.xyaml
  lib/rules/web/admin_console/4.9/dashboards.xyaml
  lib/rules/web/admin_console/4.9/deployment.xyaml
  lib/rules/web/admin_console/4.9/environments.xyaml
  lib/rules/web/admin_console/4.9/explore.xyaml
  lib/rules/web/admin_console/4.9/external_page.xyaml
  lib/rules/web/admin_console/4.9/filters.xyaml
  lib/rules/web/admin_console/4.9/goto.xyaml
  lib/rules/web/admin_console/4.9/idp.xyaml
  lib/rules/web/admin_console/4.9/imagestream.xyaml
  lib/rules/web/admin_console/4.9/logging_kibana.xyaml
  lib/rules/web/admin_console/4.9/logs.xyaml
  lib/rules/web/admin_console/4.9/machine.xyaml
  lib/rules/web/admin_console/4.9/masthead.xyaml
  lib/rules/web/admin_console/4.9/monitoring.xyaml
  lib/rules/web/admin_console/4.9/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.9/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.9/node.xyaml
  lib/rules/web/admin_console/4.9/operator_hub.xyaml
  lib/rules/web/admin_console/4.9/overview.xyaml
  lib/rules/web/admin_console/4.9/pods.xyaml
  lib/rules/web/admin_console/4.9/projects.xyaml
  lib/rules/web/admin_console/4.9/quota.xyaml
  lib/rules/web/admin_console/4.9/route.xyaml
  lib/rules/web/admin_console/4.9/search.xyaml
  lib/rules/web/admin_console/4.9/secrets.xyaml
  lib/rules/web/admin_console/4.9/status.xyaml
  lib/rules/web/admin_console/4.9/storage.xyaml
  lib/rules/web/admin_console/4.9/style.xyaml
  lib/rules/web/admin_console/4.9/tables.xyaml
  lib/rules/web/admin_console/4.9/user_management.xyaml
  lib/rules/web/admin_console/4.9/yaml.xyaml
  testdata/kata/release-4.9/deployment.yaml
  testdata/kata/release-4.9/kataconfiguration_v1_kataconfig.yaml
  testdata/kata/release-4.9/subscription.yaml
Labels: approved, lgtm

#2178 [ONEOCPDEPL-96] Update OCM CLI to version 0.1.54
  lib/launchers/o_c_m_cluster.rb
Labels: approved, lgtm, needs-ok-to-test

#2174 add checkpoint from worker to access service
  features/networking/sdn.feature
Labels: approved, lgtm

#2179 Remove IPI check, as test runs on UPI too
  features/machine/machine_healthcheck.feature
Labels: approved, lgtm

#2172 Execute all multicast cases in verification-tests
  features/networking/multicast.feature
  features/step_definitions/networking.rb
Labels: approved, lgtm

#2181 OCP-41601-wrapLogs
  lib/rules/web/admin_console/4.9/logs.xyaml
Labels: approved, lgtm

#2182 OCP-41601 add 4.8 rules for wrap logs
  lib/rules/web/admin_console/4.8/logs.xyaml
Labels: approved, lgtm

#2162 merge some logging cases
  features/logging/cluster_logging_operator.feature
  features/logging/collector.feature
  features/logging/elasticsearch.feature
  features/logging/elasticsearch_operator.feature
  features/logging/logging_acceptance.feature
  testdata/logging/clusterlogging/cl-storage-with-im-template.yaml
Labels: approved, lgtm

#2180 update channel name and fix some issue when deleting clusterlogging
  features/step_definitions/logging.rb
Labels: approved, lgtm
