Repository openshift/verification-tests, pull requests merged in 2021-05, with the labels that each got.

#1988 Fix image name
  testdata/quota/pod-completed.yaml
Labels: approved, lgtm

#1990 Use OCP4 by default and as examples
  doc/configuration.adoc
Labels: approved, lgtm

#1989 avoid printing report outline by default
  config/cucumber.yml
Labels: approved, lgtm

#1993 Add NoDiskConflicts label to the worker node only
  features/storage/NoDiskConflict.feature
Labels: approved, lgtm

#1992 Cucumber built-in parameter types happen before our transform hack and confuse our code with numeric values
  lib/world.rb
Labels: approved, lgtm

#1995 fix automation to work with new kata plugin image
  features/node/kata/install_uninstall.feature
  features/step_definitions/kata.rb
  features/test/kata.feature
  lib/openshift/kata_config.rb
  testdata/kata/release-4.8/deployment.yaml
  testdata/kata/release-4.8/subscription.yaml
Labels: approved, lgtm

#1999 Fix update-automation of polarshift.rb
  lib/gherkin_parse.rb
Labels: approved, lgtm

#1997 update rules
  lib/rules/web/admin_console/4.5/deployment.xyaml
  lib/rules/web/admin_console/4.6/deployment.xyaml
  lib/rules/web/admin_console/4.7/deployment.xyaml
  lib/rules/web/admin_console/4.8/deployment.xyaml
  lib/rules/web/admin_console/4.8/filters.xyaml
  lib/rules/web/admin_console/4.8/route.xyaml
  lib/rules/web/admin_console/4.8/style.xyaml
Labels: approved, lgtm

#2002 Update perl to use latest tag
  features/build/buildlogic.feature
Labels: approved, lgtm

#2001 Add wait before validating to ensure the policy has been applied
  features/upgrade/sdn/policy-upgrade.feature
Labels: approved, lgtm

#2006 Fix update-automation in polarshift.rb
  lib/gherkin_parse.rb
Labels: approved, lgtm

#1941 update env var for logging testing
  features/logging/cluster_log_forwarder.feature
  features/logging/logging_acceptance.feature
  features/step_definitions/logging.rb
  features/test/logging_metrics.feature
  lib/environment.rb
Labels: approved, lgtm

#1987 backporting of Cucumber 5, ReportPortal and other recent changes
  Gemfile
  OWNERS
  config/config.yaml
  config/cucumber.yml
  features/step_definitions/debug.rb
  features/step_definitions/transform.rb
  features/support/cucu_formatter.rb
  features/support/env.rb
  features/support/save_to_dir_embedding_formatter.rb
  features/test/debug.feature
  features/test/transformations.feature
  lib/configuration.rb
  lib/log.rb
  lib/manager.rb
  lib/polarshift/scenario_wrapper.rb
  lib/polarshift/test_case.rb
  lib/polarshift/test_record.rb
  lib/polarshift/test_suite.rb
  lib/test_case_manager.rb
  lib/test_case_manager_filter.rb
  lib/world.rb
  tools/launch_instance.rb
  tools/openshift-ci/Dockerfile.centos
Labels: approved, lgtm, tide/merge-method-merge

#2005 skip installation steps if there's an existing kataconfig
  features/node/kata/install_uninstall.feature
  features/step_definitions/kata.rb
Labels: approved, lgtm

#2007 fix regexp incompatibilty
  features/step_definitions/resources.rb
Labels: approved, lgtm

#1983 Add supports if the default scheduler is set
  features/step_definitions/helper_services.rb
  lib/environment.rb
Labels: approved, lgtm

#1994 automate OCP-27615: Clone a pvc with filesystem VolumeMode in the same namespace is successfully
  features/storage/csi_clone.feature
  testdata/storage/csi/pod_clone.yaml
  testdata/storage/csi/pod_pvc_sc.yaml
Labels: approved, lgtm

#2008 fix some rules
  lib/rules/web/admin_console/4.5/check_links.xyaml
  lib/rules/web/admin_console/4.5/goto.xyaml
  lib/rules/web/admin_console/4.6/check_links.xyaml
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.7/check_links.xyaml
  lib/rules/web/admin_console/4.7/goto.xyaml
  lib/rules/web/admin_console/4.8/check_links.xyaml
  lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.8/deployment.xyaml
  lib/rules/web/admin_console/4.8/goto.xyaml
  lib/rules/web/admin_console/4.8/idp.xyaml
  lib/rules/web/admin_console/4.8/imagestream.xyaml
  lib/rules/web/admin_console/4.8/machine.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/storage.xyaml
Labels: approved, lgtm

#2010 ONEOCPDEPL-92: Reflect the latest changes in OCM
  lib/launchers/o_c_m_cluster.rb
  test/lib/launchers/o_c_m_cluster_test.rb
Labels: approved, lgtm

#2016 [upgrade] Spot/preemptible instances should not block upgrade
  features/upgrade/machines/machines.feature
Labels: lgtm

#1964 New test case for Node Tuning Operator OCP-27491
  features/node/nto.feature
  lib/openshift/profile.rb
  lib/openshift/tuned.rb
  testdata/node/tuned-nf-conntrack-max.yaml
Labels: approved, lgtm

#2017 OCP-22504 quick fix
  features/networking/multus.feature
Labels: approved, lgtm

#2019 Fix issue OCPQE-3994
  features/machine/machine_healthcheck.feature
  features/networking/egress-ip.feature
Labels: approved, lgtm

#2022 Add subteam approvers
  features/routing/OWNERS
Labels: approved, lgtm

#2020 workaround for OCPQE-4052
  Gemfile
Labels: approved, lgtm

#2026 Fix restore logic of scheduler
  features/step_definitions/scheduler.rb
Labels: approved, lgtm

#2024 [v3] update some critical routing cases to use images from quay
  features/routing/haproxy-router.feature
  features/routing/route.feature
Labels: approved, lgtm

#2015 Get config infrastructure
  lib/openshift/infrastructure.rb
Labels: approved, lgtm

#2023 fix "could not find all scenarios"
  features/upgrade/machines/machines.feature
Labels: approved, lgtm

#2014 fix failure when checking data
  features/upgrade/logging/upgrade_with_clf.feature
Labels: approved, lgtm

#1980 OVN: error if no leader
  features/step_definitions/networking.rb
Labels: approved, lgtm

#2021 Execute nc at background for sctp server pod
  features/networking/sctp.feature
Labels: approved, lgtm, needs-ok-to-test

#2012 added case OCP-41813 and check for qe-app-registry
  features/cluster_configuration/create_index_catalog.feature
  features/node/kata/install_uninstall.feature
  features/step_definitions/cluster_configuration/cluster_config.rb
  features/step_definitions/kata.rb
  testdata/catalogsource/catalog_source.yaml
  testdata/catalogsource/image_content_soruce_policy.yaml
Labels: approved, lgtm

#2031 kata_smoke_test_suite
  features/node/kata/smoke_tests.feature
Labels: approved, lgtm

#2032 add a working reporportal gem version
  tools/jenkins/slaves/Dockerfile.rhel7
  tools/jenkins/slaves/Dockerfile.rhel8
Labels: approved, lgtm

#2025 Use attach to replace deprecated embed
  features/support/save_to_dir_embedding_formatter.rb
  lib/log.rb
  lib/webauto/web4cucumber.rb
Labels: approved, lgtm

#2027 Update OCP-37744 to workaround OCPQE-3994
  features/machine/machine_misc.feature
Labels: approved, lgtm

#2034 Reorder the log info
  features/support/save_to_dir_embedding_formatter.rb
  lib/log.rb
  lib/webauto/web4cucumber.rb
Labels: approved, lgtm

#2037 update the steps to deploy external log receivers
  features/logging/cluster_log_forwarder.feature
  features/logging/cluster_logging_operator.feature
  features/logging/forward_logs_to_external_elasticsearch.feature
  features/step_definitions/logging.rb
  features/upgrade/logging/upgrade_with_clf.feature
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/insecure/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/insecure/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/transport_tls/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/transport_tls/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/user_auth/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/user_auth/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/user_auth_with_transport_tls/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/user_auth_with_transport_tls/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/insecure/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/insecure/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/transport_tls/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/transport_tls/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/user_auth/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/user_auth/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/user_auth_with_transport_tls/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/user_auth_with_transport_tls/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/http/insecure/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/http/insecure/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/http/transport_tls/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/http/transport_tls/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/http/user_auth/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/http/user_auth/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/http/user_auth_with_transport_tls/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/http/user_auth_with_transport_tls/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/https/insecure/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/https/insecure/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/https/transport_tls/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/https/transport_tls/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/https/user_auth/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/https/user_auth/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/https/user_auth_with_transport_tls/configmap.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/7.12/https/user_auth_with_transport_tls/deployment.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/clf-insecure.yaml
  testdata/logging/clusterlogforwarder/elasticsearch/clf-with-secret.yaml
Labels: approved, lgtm

#2035 Add csi auto cases about Retain
  features/storage/csi.feature
Labels: approved, lgtm

#2036 rules added for OCP-36165
  lib/rules/web/admin_console/4.7/actions.xyaml
  lib/rules/web/admin_console/4.7/style.xyaml
  lib/rules/web/admin_console/4.8/actions.xyaml
  lib/rules/web/admin_console/4.8/style.xyaml
Labels: approved, lgtm

#2041 [ONEOCPDEPL-93] Class names renamed as requested
  config/config.yaml
  lib/configuration.rb
Labels: approved, lgtm, needs-ok-to-test

#2044 Test the bot
  features/routing/abrouting.feature
Labels: approved, lgtm

#2045 Add yapei as approver for web cases
  lib/rules/web/admin_console/OWNERS
Labels: approved, lgtm

#2046 Test OWNERS in sub-folder
  lib/rules/web/admin_console/4.8/builds.xyaml
  lib/rules/web/admin_console/4.8/catalog.xyaml
  lib/rules/web/admin_console/4.8/check_links.xyaml
  lib/rules/web/admin_console/4.8/dashboards.xyaml
  lib/rules/web/admin_console/4.8/environments.xyaml
  lib/rules/web/admin_console/4.8/filters.xyaml
  lib/rules/web/admin_console/4.8/goto.xyaml
  lib/rules/web/admin_console/4.8/idp.xyaml
  lib/rules/web/admin_console/4.8/machine.xyaml
  lib/rules/web/admin_console/4.8/monitoring.xyaml
  lib/rules/web/admin_console/4.8/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.8/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.8/node.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/pods.xyaml
  lib/rules/web/admin_console/4.8/projects.xyaml
  lib/rules/web/admin_console/4.8/quota.xyaml
  lib/rules/web/admin_console/4.8/route.xyaml
  lib/rules/web/admin_console/4.8/search.xyaml
  lib/rules/web/admin_console/4.8/status.xyaml
  lib/rules/web/admin_console/4.8/storage.xyaml
  lib/rules/web/admin_console/4.8/style.xyaml
  lib/rules/web/admin_console/4.8/tables.xyaml
  lib/rules/web/admin_console/4.8/user_management.xyaml
Labels: approved, lgtm

#2043 update steps
  features/logging/elasticsearch.feature
  features/step_definitions/logging.rb
  features/upgrade/logging/upgrade.feature
Labels: approved, lgtm

#2039 added option to selective clone of run
  tools/polarshift.rb
Labels: approved, lgtm

#2030 Fix scheduler restore logic
  features/step_definitions/scheduler.rb
Labels: approved, lgtm

#2047 add smoke tag
  features/cli/policy.feature
  features/storage/dynamic_provisioning.feature
  features/storage/fsType.feature
  features/storage/persistent_volume.feature
  features/storage/quota.feature
  features/storage/reclaim_policy.feature
  features/storage/security.feature
  features/storage/storage_class.feature
  features/storage/vsphere.feature
Labels: approved, lgtm

#2048 kata subscription needs to be updated with the latest build
  features/step_definitions/kata.rb
  testdata/kata/release-4.8/deployment.yaml
  testdata/kata/release-4.8/subscription.yaml
Labels: approved
