Repository openshift/verification-tests, pull requests merged in 2021-09, with the labels that each got.

#2230 Add stage-only tags
  features/networking/ptp_operator.feature
  features/networking/sriov.feature
  features/storage/csi.feature
  features/upgrade/logging/upgrade_with_clf.feature
Labels: lgtm, approved

#2231 auto OCP-43052 and fixed some cases and supplement OCP-26380
  lib/rules/web/ocm_console/install_page.xyaml
Labels: lgtm, approved

#2232 Add proxy tag
  features/build/buildconfig.feature
  features/build/buildlogic.feature
  features/build/dockerbuild.feature
  features/build/env.feature
  features/build/stibuild.feature
  features/cli/build.feature
  features/cli/create.feature
  features/cli/deploy.feature
  features/cli/oc_env.feature
  features/cli/oc_process.feature
  features/cli/oc_set_build_hook.feature
  features/cli/oc_set_deployment_hook.feature
  features/cli/pod.feature
  features/cli/policy.feature
  features/cli/projects.feature
  features/cli/route.feature
  features/cli/scale.feature
  features/cli/secrets.feature
  features/cli/serviceaccount.feature
  features/images/rhel8_images.feature
  features/node/proxy.feature
  features/registry/registry.feature
  features/rest/webhook.feature
  features/upgrade/build/build-upgrade.feature
Labels: approved

#2233 Add CLI 4.10
  lib/rules/cli/4.10.yaml
  lib/rules/cli/kubectl-4.10.yaml
Labels: lgtm, approved

#2235 Avoid printing report outline with profile polarshift
  config/cucumber.yml
Labels: lgtm, approved

#2234 Add admin console web rules for v4.10
  lib/rules/web/admin_console/4.10/actions.xyaml
  lib/rules/web/admin_console/4.10/browser_opts.yml
  lib/rules/web/admin_console/4.10/builds.xyaml
  lib/rules/web/admin_console/4.10/catalog.xyaml
  lib/rules/web/admin_console/4.10/check_links.xyaml
  lib/rules/web/admin_console/4.10/clustersettings.xyaml
  lib/rules/web/admin_console/4.10/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.10/configmap.xyaml
  lib/rules/web/admin_console/4.10/customizations.xyaml
  lib/rules/web/admin_console/4.10/dashboards.xyaml
  lib/rules/web/admin_console/4.10/deployment.xyaml
  lib/rules/web/admin_console/4.10/environments.xyaml
  lib/rules/web/admin_console/4.10/explore.xyaml
  lib/rules/web/admin_console/4.10/external_page.xyaml
  lib/rules/web/admin_console/4.10/filters.xyaml
  lib/rules/web/admin_console/4.10/goto.xyaml
  lib/rules/web/admin_console/4.10/idp.xyaml
  lib/rules/web/admin_console/4.10/imagestream.xyaml
  lib/rules/web/admin_console/4.10/logging_kibana.xyaml
  lib/rules/web/admin_console/4.10/logs.xyaml
  lib/rules/web/admin_console/4.10/machine.xyaml
  lib/rules/web/admin_console/4.10/masthead.xyaml
  lib/rules/web/admin_console/4.10/monitoring.xyaml
  lib/rules/web/admin_console/4.10/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.10/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.10/node.xyaml
  lib/rules/web/admin_console/4.10/operator_hub.xyaml
  lib/rules/web/admin_console/4.10/overview.xyaml
  lib/rules/web/admin_console/4.10/pods.xyaml
  lib/rules/web/admin_console/4.10/projects.xyaml
  lib/rules/web/admin_console/4.10/quota.xyaml
  lib/rules/web/admin_console/4.10/route.xyaml
  lib/rules/web/admin_console/4.10/search.xyaml
  lib/rules/web/admin_console/4.10/secrets.xyaml
  lib/rules/web/admin_console/4.10/status.xyaml
  lib/rules/web/admin_console/4.10/storage.xyaml
  lib/rules/web/admin_console/4.10/style.xyaml
  lib/rules/web/admin_console/4.10/tables.xyaml
  lib/rules/web/admin_console/4.10/user_management.xyaml
  lib/rules/web/admin_console/4.10/yaml.xyaml
Labels: lgtm, approved

#2237 add disconnected tag
  features/build/stibuild.feature
  features/machine/machine.feature
  features/networking/pod.feature
  features/registry/registry.feature
Labels: lgtm, approved

#2238 Add pkg rsync
  tools/openshift-ci/Dockerfile
Labels: lgtm, approved

#2236 fix upgrade failure
  features/step_definitions/logging.rb
Labels: lgtm, approved

#2239 Rewrite rules for the new ocm creation wizard
  lib/rules/web/ocm_console/cluster_detail.xyaml
  lib/rules/web/ocm_console/cluster_detail_overview_tab.xyaml
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
  lib/rules/web/ocm_console/osd_creation_page.xyaml
  lib/rules/web/ocm_console/osd_wizard.xyaml
  lib/rules/web/ocm_console/osd_wizard_billing_model.xyaml
  lib/rules/web/ocm_console/osd_wizard_cloud_provider.xyaml
  lib/rules/web/ocm_console/osd_wizard_cluster_details.xyaml
  lib/rules/web/ocm_console/osd_wizard_machine_pool.xyaml
  lib/rules/web/ocm_console/osd_wizard_networking.xyaml
  lib/rules/web/ocm_console/osd_wizard_review.xyaml
  lib/rules/web/ocm_console/osd_wizard_updates.xyaml
Labels: lgtm, approved

#2240 update routing owners
  features/routing/OWNERS
Labels: lgtm, approved

#2242 fix OCP-20932 rules
  lib/rules/web/admin_console/4.8/overview.xyaml
  lib/rules/web/admin_console/4.9/overview.xyaml
Labels: lgtm, approved

#2246 fix ocp-39779&ocp-40585&ocp-41817
  lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
Labels: lgtm, approved

#2245 Inactive some old cases.
  features/storage/storage_class.feature
Labels: lgtm, approved

#2247 refactoring part one
  lib/rules/web/ocm_console/install_page.xyaml
Labels: lgtm, approved

#2250 add console tag
  features/logging/logging_acceptance.feature
Labels: approved

#2248 Fix lastTriggeredImageID issue
  features/cli/oc_import_image.feature
Labels: lgtm, approved

#2252 Fix invalid project name in some rarely cases
  lib/environment.rb
Labels: lgtm, approved

#2255 Extend debug project wait time
  lib/environment.rb
Labels: lgtm, approved

#2253 fix for web
  lib/rules/web/admin_console/4.6/goto.xyaml
  lib/rules/web/admin_console/4.7/goto.xyaml
  lib/rules/web/admin_console/4.9/catalog.xyaml
Labels: lgtm, approved

#2256 Make sure EXECUTOR_NAME always end with proper char
  lib/bushslicer.rb
  lib/environment.rb
Labels: lgtm, approved

#2258 print browser and driver version for debugging
  lib/webauto/web4cucumber.rb
Labels: lgtm, approved

#2260 Add serial tag
  features/networking/multus.feature
Labels: lgtm, approved

#2261 use serial tag
  features/logging/logging_acceptance.feature
Labels: approved

#2263 tag unsable tests in Prow
  features/logging/logging_acceptance.feature
Labels: approved

#2262 fix OCP-12086
  features/admin/quota.feature
Labels: lgtm, approved

#2257 Sync owners from cucushift repo
  features/build/OWNERS
  features/machine/OWNERS
  features/networking/OWNERS
  features/online/OWNERS
  features/registry/OWNERS
  features/routing/OWNERS
  features/storage/OWNERS
Labels: lgtm, approved

#2264 Fix warning: already initialized constant BushSlicer::EXECUTOR_NAME
  lib/bushslicer.rb
Labels: lgtm, approved

#2251 Hongyli stablize and fix test failures sep7
  lib/rules/web/admin_console/4.6/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.7/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.7/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.8/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.8/monitoring_metrics.xyaml
  lib/rules/web/admin_console/4.9/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.9/goto.xyaml
  lib/rules/web/admin_console/4.9/monitoring_alerts.xyaml
  lib/rules/web/admin_console/4.9/monitoring_metrics.xyaml
Labels: lgtm, approved

#2271 reconsitution install page, update login
  lib/rules/web/ocm_console/install_page.xyaml
  lib/rules/web/ocm_console/login.xyaml
Labels: lgtm, approved

#2275 fix for ocp-24478
  lib/openshift/knative_serving.rb
Labels: lgtm, approved

#2268 Fix validation of output
  features/cli/job.feature
Labels: lgtm, approved

#2277 Adjust owners for CLI
  features/cli/OWNERS
Labels: lgtm, approved

#2278 Moving Kata features under features folder
  features/kata/install_uninstall.feature
  features/kata/pod.feature
  features/kata/smoke_tests.feature
Labels: lgtm, approved

#2273 fix failure: can not switch to project openshift-logging
  features/logging/logging_acceptance.feature
Labels: lgtm, approved

#2282 auto OCP-43331
  features/upgrade/machines/machines.feature
Labels: lgtm, approved

#2283 make the output checkpoint more robust
  features/cli/job.feature
Labels: lgtm, approved

#2287 Remove 3.x only scenarios from master branch (which is for 4.x)
  features/svc-catalog_asb/asb.feature
Labels: lgtm, approved

#2241 Auto upgrade case for egressip and egressfirewall
  features/upgrade/sdn/egress-upgrade.feature
Labels: lgtm, approved

#2284 Add for new case ocp42112
  lib/rules/web/admin_console/4.8/deployment.xyaml
  lib/rules/web/admin_console/4.8/goto.xyaml
  lib/rules/web/admin_console/4.9/deployment.xyaml
  lib/rules/web/admin_console/4.9/goto.xyaml
  testdata/templates/ocp42112/buildconfig.yaml
Labels: lgtm, approved

#2276 Auto multicast upgrade case
  features/upgrade/sdn/multicast-upgrade.feature
Labels: lgtm, approved

#2288 Add OWNERS for SDN upgrade
  features/upgrade/sdn/OWNERS
Labels: lgtm, approved

#2290 Fix several failures in PROW
  features/cli/oc_set_probe.feature
  features/routing/ingress-route.feature
Labels: lgtm, approved

#2269 Update for OCP-36165,OCP-32152,OCP-27550,OCP-19675
  lib/rules/web/admin_console/4.9/projects.xyaml
  lib/rules/web/admin_console/4.9/search.xyaml
  lib/rules/web/admin_console/4.9/style.xyaml
Labels: lgtm, approved

#2265 Documenting the tags added to cucushift
  doc/tags.adoc
Labels: lgtm, approved

#2292 Fix several failures in PROW
  features/images/jenkins.feature
  features/service_catalog_tsb/tsb.feature
Labels: lgtm, approved

#2286 change xpath and function due to 4.9 change
  lib/rules/web/admin_console/4.9/monitoring_metrics.xyaml
Labels: lgtm, approved

#2291 Simplify docker build
  features/build/dockerbuild.feature
Labels: lgtm, approved

#2184 add cases OCP-43146
  features/networking/sdn.feature
  features/upgrade/sdn/service-upgrade.feature
Labels: lgtm, approved

#2243 Fix restore descheduler func to handle more cases
  features/step_definitions/descheduler.rb
Labels: lgtm, approved

#2289 add rules to create visualize on kibana
  lib/rules/web/admin_console/4.7/logging_kibana.xyaml
  lib/rules/web/admin_console/4.8/logging_kibana.xyaml
  lib/rules/web/admin_console/4.9/logging_kibana.xyaml
Labels: lgtm, approved

#2281 update support
  lib/openshift/subscription.rb
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
  lib/rules/web/admin_console/4.9/operator_hub.xyaml
Labels: lgtm, approved

#2267 snapshot for AWS platform
  features/upgrade/storage/upgrade.feature
Labels: lgtm, approved

#2301 Updated OCP-18482 on IPv6 Cluster
  features/routing/rate-limit.feature
Labels: lgtm, approved

#1855 Cloud usage enhanced
  lib/launchers/amz.rb
  lib/launchers/azure.rb
  lib/launchers/openstack.rb
  lib/launchers/packet.rb
  lib/launchers/v_sphere.rb
  tools/cloud_usage.rb
  tools/instance_summary.rb
  tools/jenkins.rb
  tools/jenkins_mongo.rb
  tools/openshift_qe_slack.rb
Labels: lgtm, approved, lifecycle/stale

#2303 Using console tags
  doc/tags.adoc
  features/images/jenkins.feature
  features/logging/logging_acceptance.feature
Labels: lgtm, approved

#2304 update pod with ReplicationControllor in order to upgrade
  testdata/networking/nodeport_test_pod.yaml
Labels: lgtm, approved

#2298 update rules
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/status.xyaml
  lib/rules/web/admin_console/4.6/storage.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/status.xyaml
  lib/rules/web/admin_console/4.7/storage.xyaml
  lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.8/status.xyaml
  lib/rules/web/admin_console/4.8/storage.xyaml
  lib/rules/web/admin_console/4.9/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.9/dashboards.xyaml
  lib/rules/web/admin_console/4.9/route.xyaml
  lib/rules/web/admin_console/4.9/status.xyaml
  lib/rules/web/admin_console/4.9/storage.xyaml
Labels: lgtm, approved

#2308 fix slack class name collision
  Gemfile
  tools/instance_summary.rb
  tools/openshift_qe_slack.rb
Labels: lgtm, approved

#2305 add rule for upgrade case
  lib/rules/web/admin_console/4.1/goto.xyaml
  lib/rules/web/admin_console/4.2/goto.xyaml
Labels: lgtm, approved

#2299 [Automate-storage] [OCP-44578] [AWS-EBS-CSI] [Snapshot operator]
  features/upgrade/storage/upgrade.feature
Labels: lgtm, approved

#2300 [Automate][OCP-41452][Azure CSI Resize] offline volume expansion
  features/storage/csi_resize.feature
Labels: lgtm, approved

#2313 check pod with label
  features/networking/service.feature
Labels: lgtm, approved

#2315 Tag network-multitenant test case
  features/networking/isolation.feature
Labels: lgtm, approved

#2317 Simplify OCP-17515
  features/cli/job.feature
  lib/openshift/cron_job.rb
Labels: lgtm, approved

#2294 Automate OCP-44790 externalIP-upgrade-test
  features/upgrade/sdn/externalIP-upgrade.feature
  testdata/networking/externalip_pod.yaml
Labels: lgtm, approved

#2302 Automate sctp-upgrade test
  features/upgrade/sdn/sctp-upgrade.feature
  testdata/networking/sctp/sctpclient-upgrade.yaml
  testdata/networking/sctp/sctpserver-upgrade.yaml
Labels: lgtm, approved

#2318 update tag for multitenant cases
  features/networking/isolation.feature
  features/networking/sdn.feature
  features/networking/service.feature
Labels: lgtm, approved

#2314 [Automate][OCP-41449][Azure-csi-snapshot]with default parameters
  features/storage/csi_snapshot.feature
  testdata/storage/csi/volumesnapshotclass-azure.yaml
Labels: lgtm, approved

#2321 Fix prow gcp rehearse tests
  doc/tags.adoc
  features/networking/ovn.feature
  features/networking/ovn_ipsec.feature
  features/networking/pod.feature
  features/networking/sdn.feature
Labels: lgtm, approved

#2296 Add more Kibana verification in upgrade
  features/logging/kibana.feature
  features/step_definitions/logging.rb
  features/upgrade/logging/upgrade.feature
  lib/rules/web/admin_console/4.5/logging_kibana.xyaml
  lib/rules/web/admin_console/4.6/logging_kibana.xyaml
  lib/rules/web/admin_console/4.7/logging_kibana.xyaml
  lib/rules/web/admin_console/4.8/logging_kibana.xyaml
  lib/rules/web/admin_console/4.9/logging_kibana.xyaml
Labels: lgtm, approved

#2316 fix operator related rules
  lib/rules/web/admin_console/4.6/actions.xyaml
  lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
  lib/rules/web/admin_console/4.7/actions.xyaml
  lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/actions.xyaml
  lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
  lib/rules/web/admin_console/4.9/actions.xyaml
  lib/rules/web/admin_console/4.9/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.9/operator_hub.xyaml
Labels: lgtm, approved

#2323 update image nginx-alpine digest for ARM arch
  testdata/routing/abrouting/abtest-websrv1.yaml
  testdata/routing/abrouting/abtest-websrv2.yaml
  testdata/routing/abrouting/abtest-websrv3.yaml
  testdata/routing/abrouting/abtest-websrv4.yaml
  testdata/routing/web-server-1.yaml
  testdata/routing/web-server-rc.yaml
Labels: lgtm, approved

#2324 Fix OCP-11139 failure in PROW
  features/cli/build.feature
Labels: lgtm, approved

#2325 Fix a possible test flake in 4.9
  features/storage/regression.feature
Labels: lgtm, approved

#2319 [4.9-4.10] IBMCLOUD addition (alpha)
  lib/bushslicer.rb
  lib/launchers/cloud_helper.rb
  lib/launchers/ibmcloud.rb
Labels: lgtm, approved

#2331 fix psap automation failures
  features/step_definitions/nfd.rb
Labels: lgtm, approved

#2329 Update sctp to check nodes state
  features/networking/sctp.feature
Labels: lgtm, approved

#2320 ocp-41964
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
  lib/rules/web/admin_console/4.9/operator_hub.xyaml
Labels: lgtm, approved

#2333 fix OCP-37496
  features/networking/egress-ingress.feature
Labels: lgtm, approved

#2334 Fix docker image
  features/build/stibuild.feature
Labels: lgtm, approved

#2327 Add tag console to support tests in Prow
  features/logging/cluster_logging_operator.feature
  features/logging/elasticsearch_operator.feature
  features/test/webconsole.feature
  features/upgrade/web/console-upgrade.feature
Labels: lgtm, approved

#2332 Fix CSI failures for AWS IPI tests in Prow
  features/storage/csi.feature
Labels: lgtm, approved

#2336 simplify choose_project_from_dropdown_list
  lib/rules/web/admin_console/4.6/catalog.xyaml
  lib/rules/web/admin_console/4.7/catalog.xyaml
  lib/rules/web/admin_console/4.8/catalog.xyaml
  lib/rules/web/admin_console/4.9/catalog.xyaml
Labels: lgtm, approved

#2340 added ability to clone run with filter by subteams
  tools/polarshift.rb
Labels: lgtm, approved

#2341 Add ensure_console_tagged
  features/logging/cluster_logging_operator.feature
  features/logging/elasticsearch_operator.feature
  features/step_definitions/admin_console.rb
  features/step_definitions/web.rb
  features/test/webconsole.feature
  lib/world.rb
Labels: lgtm, approved

#2307 Optimize OCP-36165
  lib/rules/web/admin_console/4.7/style.xyaml
  lib/rules/web/admin_console/4.8/style.xyaml
  lib/rules/web/admin_console/4.9/style.xyaml
Labels: lgtm, approved

#2343 missing a step to deploy logging operators
  features/upgrade/logging/upgrade.feature
Labels: lgtm, approved

#2345 Update the OWNER of Logging team
  features/logging/OWNERS
Labels: lgtm, approved

#2342 Force steps that update SCC to tag destructive
  features/step_definitions/scc.rb
Labels: lgtm, approved

#2335 Support Logging5.3
  features/logging/cluster_log_forwarder.feature
  features/logging/cluster_logging_operator.feature
  features/logging/collector.feature
  features/logging/logging_acceptance.feature
  features/step_definitions/logging.rb
  lib/openshift/cluster_logging.rb
Labels: lgtm, approved

#2347 collector name update in OCP-30084
  features/logging/collector.feature
Labels: lgtm, approved
