Repository openshift/verification-tests, pull requests merged in 2022-12, with the labels that each got.

#3149 storage-fixplatformname
  features/step_definitions/storage_class.rb
Labels: lgtm, approved

#3150 removed @hypershift-hosted cluster tag
  features/machine/autoscaler.feature
  features/machine/machine.feature
  features/machine/machine_healthcheck.feature
  features/machine/machine_misc.feature
  features/machine/upi_gcp.feature
Labels: lgtm, approved

#3143 use normal deployment instead of new-app
  features/storage/cloud_provider.feature
Labels: lgtm, approved

#3152 remove unused rules
  lib/rules/web/admin_console/4.10/operator_hub.xyaml
  lib/rules/web/admin_console/4.11/operator_hub.xyaml
  lib/rules/web/admin_console/4.12/operator_hub.xyaml
  lib/rules/web/admin_console/4.13/operator_hub.xyaml
  lib/rules/web/admin_console/4.5/operator_hub.xyaml
  lib/rules/web/admin_console/4.6/operator_hub.xyaml
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
  lib/rules/web/admin_console/4.9/operator_hub.xyaml
Labels: lgtm, approved

#3153 add label to logging namespaces
  features/step_definitions/logging.rb
Labels: lgtm, approved

#3118 Cloud watch utilty to give a warning to the team when vpc & s3 buckets are approach to the max.
  lib/launchers/amz.rb
  tools/cloud_watch.rb
  tools/resource_monitor.rb
Labels: lgtm, approved

#3154 Update three cases supported in sdn2ovn migration
  features/step_definitions/networking.rb
  features/upgrade/sdn/egress-upgrade.feature
Labels: lgtm, approved

#3155 And the appropriate pod security labels for multus cases
  features/networking/multus.feature
Labels: lgtm, approved

#3147 update upgrade case
  features/upgrade/monitoring/monitoring-upgrade.feature
Labels: lgtm, approved

#3156 fix OCP-33743
  lib/rules/web/admin_console/4.10/operator_hub.xyaml
  lib/rules/web/admin_console/4.11/operator_hub.xyaml
  lib/rules/web/admin_console/4.12/operator_hub.xyaml
  lib/rules/web/admin_console/4.13/operator_hub.xyaml
  lib/rules/web/admin_console/4.7/operator_hub.xyaml
  lib/rules/web/admin_console/4.8/operator_hub.xyaml
  lib/rules/web/admin_console/4.9/operator_hub.xyaml
Labels: lgtm, approved

#3137 Add wait time so that descheduler operator pod comes up fine
  features/upgrade/workloads/descheduler-upgrade.feature
Labels: lgtm, approved

#3157 fix 11877
  features/cli/deploy.feature
Labels: lgtm, approved

#3159 remove version 4.9 from logging upgrade case
  features/upgrade/logging/upgrade.feature
Labels: lgtm, approved

#3160 update httpbin image to support fips
  features/routing/timeout.feature
  testdata/routing/routetimeout/httpbin-pod-2.json
  testdata/routing/routetimeout/httpbin-pod.json
Labels: lgtm, approved

#3158 Fix OCPQE-13180
  features/upgrade/sdn/egress-upgrade.feature
  features/upgrade/sdn/multicast-upgrade.feature
Labels: lgtm, approved

#3161 add new rules
  lib/rules/web/admin_console/4.10/goto.xyaml
  lib/rules/web/admin_console/4.11/goto.xyaml
  lib/rules/web/admin_console/4.12/goto.xyaml
  lib/rules/web/admin_console/4.13/goto.xyaml
  lib/rules/web/admin_console/4.8/goto.xyaml
  lib/rules/web/admin_console/4.9/goto.xyaml
Labels: lgtm, approved

#3162 added CLI support to sync run from Polarion to Polarshift
  lib/polarshift/request.rb
  tools/polarshift.rb
Labels: lgtm, approved

#3165 storage-identifyplatform fix
  features/step_definitions/storage_class.rb
Labels: lgtm, approved

#3166 Update OCP-11619 for stability
  features/routing/haproxy-router.feature
Labels: lgtm, approved

#3167 added step to check all clusters operators are ready
  features/step_definitions/operators.rb
  features/test/operators.feature
  lib/openshift/cluster_operator.rb
Labels: lgtm, approved

#3168 text check update
  features/machine/machine.feature
Labels: lgtm, approved

#3106 Fixes OCP-11543
  features/build/env.feature
Labels: lgtm, approved, needs-ok-to-test

#3094 Fixes OCP-24154 and OCP-24158
  features/build/buildlogic.feature
Labels: lgtm, approved, ok-to-test

#3173 adding disconnected tag for httpbin related cases
  features/routing/rate-limit.feature
  features/routing/timeout.feature
Labels: lgtm, approved

#3171 Update pod.feature
  features/admin/pod.feature
Labels: lgtm, approved
