Repository openshift/verification-tests, pull requests merged in 2023-05, with the labels that each got.

#3315 Backport change of PR3292
  lib/rules/web/admin_console/4.12/catalog.xyaml
  lib/rules/web/admin_console/4.13/catalog.xyaml
Labels: lgtm, approved

#3316 Make-OCP22504-flaky
  features/networking/multus.feature
Labels: lgtm, approved

#3312 To add proper privilege to projects
  features/admin/scc.feature
  features/cli/create.feature
  features/storage/nfs.feature
Labels: lgtm, approved

#3320 improve auto
  lib/rules/web/admin_console/4.10/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.11/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.12/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.13/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.14/common_ui_elements.xyaml
Labels: lgtm, approved

#3317 disable FIPS_MODE in amq-streams-cluster-operator when FIPS is enabled in the cluster
  features/step_definitions/logging.rb
Labels: lgtm, approved

#3321 Add storage tag
  features/storage/NoDiskConflict.feature
  features/storage/cinder.feature
  features/storage/cloud_provider.feature
  features/storage/csi.feature
  features/storage/csi_clone.feature
  features/storage/csi_resize.feature
  features/storage/csi_snapshot.feature
  features/storage/dynamic_provisioning.feature
  features/storage/fsType.feature
  features/storage/hostpath.feature
  features/storage/local-storage-operator.feature
  features/storage/negative.feature
  features/storage/nfs.feature
  features/storage/node_operations.feature
  features/storage/persistent_volume.feature
  features/storage/pre-bind.feature
  features/storage/quota.feature
  features/storage/reclaim_policy.feature
  features/storage/regression.feature
  features/storage/security.feature
  features/storage/storage_class.feature
  features/storage/storage_object_in_use_protection.feature
  features/storage/vsphere.feature
Labels: lgtm, approved

#3323 fix OCP-19722 rules
  lib/rules/web/admin_console/4.10/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.11/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.12/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.13/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.14/common_ui_elements.xyaml
  lib/rules/web/admin_console/4.9/common_ui_elements.xyaml
Labels: lgtm, approved

#3324 Remove static users for multus upgrade case
  features/upgrade/sdn/multus-upgrade.feature
Labels: lgtm, approved

#3325 add another pfname
  testdata/networking/sriov/ib/cx5/cx5-ib.yaml
Labels: lgtm, approved

#3326 Remove CCO Upgrade test for Hypershift hosted cluster
  features/upgrade/cloudcredential/upgrade.feature
Labels: lgtm, approved

#3327 Revert "Remove static users for multus upgrade case"
  features/upgrade/sdn/multus-upgrade.feature
Labels: lgtm

#3331 disable hypershift for OCP-13022
  features/upgrade/node/node-upgrade.feature
Labels: lgtm, approved

#3333 OCPQE-15438: Add subteam and case ID info to scenario name for storage
  features/upgrade/storage/upgrade.feature
Labels: lgtm, approved, jira/valid-reference

#3328 remove @hypershift-hosted tag
  features/upgrade/machines/machines.feature
Labels: lgtm, approved

#3335 Remove OCP-44578 and add storage tag for upgrade case
  features/upgrade/storage/upgrade.feature
Labels: lgtm, approved

#3336 Backport PR3233 for fail case
  lib/rules/web/admin_console/4.12/route.xyaml
Labels: lgtm, approved

#3334 remove flake/inactive cases
  features/networking/multus.feature
Labels: lgtm, approved
