Repository openshift/verification-tests, pull requests merged in 2024-04, with the labels that each got.

#3574 Add level0 tag
  doc/prow/query_level0.json
  features/admin/scheduler.feature
  features/cli/serviceaccount.feature
  features/machine/autoscaler.feature
  features/machine/machine.feature
  features/upgrade/machines/machines.feature
  features/upgrade/monitoring/monitoring-upgrade.feature
  features/upgrade/security_compliance/fips.feature
Labels: lgtm, approved, do-not-merge/hold

#3567 Update dashboard URL for OCP 4.16
  lib/rules/web/admin_console/4.16/goto.xyaml
Labels: lgtm, approved

#3575 Removing 4.15 and 4.16 tags
  features/upgrade/workloads/descheduler-upgrade.feature
Labels: lgtm, approved

#3576 this is converted to ginkgo from 4.14 onwards
  features/machine/machine.feature
Labels: lgtm, approved

#3577 removing ocp-27594 from 4.12+ branches
  features/routing/operator.feature
Labels: lgtm, approved

#3568 Updating OCP-25933 for ppc64le
  features/networking/sdn.feature
Labels: lgtm, approved

#3578 replace raise error with skip cases
  features/step_definitions/networking.rb
Labels: lgtm, approved

#3579 limit 37704 until 4.13
  features/networking/metrics.feature
Labels: lgtm, approved

#3581 Fix OCP-36156 script issue
  lib/rules/web/admin_console/4.15/style.xyaml
Labels: lgtm, approved

#3584 Move OCP-26091 from scenario outline to scenario
  features/networking/ovn.feature
Labels: lgtm, approved

#3583 fix OCP-19722
  lib/rules/web/admin_console/4.10/node.xyaml
  lib/rules/web/admin_console/4.11/node.xyaml
  lib/rules/web/admin_console/4.12/node.xyaml
  lib/rules/web/admin_console/4.13/node.xyaml
  lib/rules/web/admin_console/4.14/node.xyaml
  lib/rules/web/admin_console/4.15/node.xyaml
  lib/rules/web/admin_console/4.16/node.xyaml
Labels: lgtm, approved

#3585 update Kakfa version
  features/logging/OWNERS
  testdata/logging/clusterlogforwarder/kafka/amq/04_kafka_my-cluster_amqstreams_template.yaml
Labels: lgtm, approved

#3587 Transfer storage test case owner
  features/cli/policy.feature
  features/cluster_configuration/snapshot.feature
  features/storage/NoDiskConflict.feature
  features/storage/cloud_provider.feature
  features/storage/dynamic_provisioning.feature
  features/storage/hostpath.feature
  features/storage/local-storage-operator.feature
  features/storage/negative.feature
  features/storage/nfs.feature
  features/storage/persistent_volume.feature
  features/storage/pre-bind.feature
  features/storage/reclaim_policy.feature
  features/storage/security.feature
  features/storage/storage_class.feature
  features/storage/storage_object_in_use_protection.feature
Labels: lgtm, approved

#3588 OCPQE-21203: Fix get_secret_names undefined method `map' for nil when image registry is disabled
  lib/openshift/service_account.rb
Labels: lgtm, approved, jira/valid-reference

#3586 fix OCP-22308
  lib/rules/web/admin_console/4.11/goto.xyaml
  lib/rules/web/admin_console/4.12/goto.xyaml
  lib/rules/web/admin_console/4.13/goto.xyaml
  lib/rules/web/admin_console/4.14/goto.xyaml
  lib/rules/web/admin_console/4.15/goto.xyaml
  lib/rules/web/admin_console/4.16/goto.xyaml
Labels: lgtm, approved

#3589 Add case ID and subteam info
  features/networking/isolation.feature
  features/networking/ovn.feature
Labels: lgtm, approved
